const vocabData = [
  {
    id: 1,
    title: "Tea Cart",
    bangla: "টি কার্ট",
    synonymous: "Tea wagon, Beverage trolley",
    sentence: "The waiter brought the tea on a tea cart.",
  },
  {
    id: 2,
    title: "Stool",
    bangla: "স্টুল",
    synonymous: "Seat, Footstool",
    sentence: "She sat on a stool by the counter.",
  },
  {
    id: 3,
    title: "Jar",
    bangla: "জার",
    synonymous: "Container, Pot",
    sentence: "He kept the cookies in a glass jar.",
  },
  {
    id: 4,
    title: "Teacup",
    bangla: "টি কাপ",
    synonymous: "Cup, Mug",
    sentence: "She poured tea into the teacup.",
  },
  {
    id: 5,
    title: "Condensed milk",
    bangla: "কনডেন্সড মিল্ক",
    synonymous: "Evaporated milk, Sweetened milk",
    sentence: "He added condensed milk to his coffee for extra sweetness.",
  },
  {
    id: 6,
    title: "Stove",
    bangla: "স্টোভ",
    synonymous: "Cooker, Range",
    sentence: "She heated the water on the stove.",
  },
  {
    id: 7,
    title: "Kettle",
    bangla: "কেটল",
    synonymous: "Tea kettle, Water boiler",
    sentence: "The kettle whistled when the water boiled.",
  },
  {
    id: 8,
    title: "Filter",
    bangla: "ফিল্টার",
    synonymous: "Strainer, Sieve",
    sentence: "She used a filter to remove the tea leaves.",
  },
  {
    id: 9,
    title: "Buns",
    bangla: "বানস",
    synonymous: "Muffin, Bread roll",
    sentence: "They served fresh buns with breakfast.",
  },
  {
    id: 10,
    title: "Black tea",
    bangla: "ব্ল্যাক টি",
    synonymous: "Tea, Plain tea",
    sentence: "He prefers black tea without any milk.",
  },
  {
    id: 1,
    title: "Gridlock",
    bangla: "গ্রিডলক",
    synonymous: "Congestion, Traffic jam",
    sentence: "The city center is often in gridlock during rush hours.",
  },
  {
    id: 2,
    title: "Intersection",
    bangla: "ইন্টারসেকশন",
    synonymous: "Junction, Crossroad",
    sentence: "Turn left at the intersection to reach the highway.",
  },
  {
    id: 3,
    title: "Traffic warden",
    bangla: "ট্রাফিক ওয়ার্ডেন",
    synonymous: "Traffic police, Traffic officer",
    sentence: "The traffic warden directed vehicles during peak hours.",
  },
  {
    id: 4,
    title: "Motorway",
    bangla: "মোটরওয়ে",
    synonymous: "Highway, Expressway",
    sentence: "They took the motorway to reach the city faster.",
  },
  {
    id: 5,
    title: "Zebra crossing",
    bangla: "জেব্রা ক্রসিং",
    synonymous: "Pedestrian crossing, Crosswalk",
    sentence: "Pedestrians should use the zebra crossing to cross the road.",
  },
  {
    id: 6,
    title: "Footpath",
    bangla: "ফুটপাথ",
    synonymous: "Sidewalk, Pavement",
    sentence: "People walk along the footpath to stay safe from traffic.",
  },
  {
    id: 7,
    title: "Street vendor",
    bangla: "স্ট্রিট ভেন্ডর",
    synonymous: "Hawker, Peddler",
    sentence: "Street vendors sell a variety of goods along the footpath.",
  },
  {
    id: 8,
    title: "Roundabout",
    bangla: "রাউন্ডঅ্যাবাউট",
    synonymous: "Traffic circle, Rotary",
    sentence: "Take the first exit at the roundabout to stay on Main Street.",
  },
  {
    id: 9,
    title: "Overbridge",
    bangla: "ওভারব্রিজ",
    synonymous: "Foot overbridge, Pedestrian bridge",
    sentence: "Pedestrians use the overbridge to cross the busy road.",
  },
  {
    id: 10,
    title: "Flyover",
    bangla: "ফ্লাইওভার",
    synonymous: "Overpass, Elevated road",
    sentence: "The flyover helps reduce traffic congestion in the city.",
  },

  {
    id: 1,
    title: "Escalator",
    bangla: "এসকেলেটর",
    synonymous: "Moving staircase, Moving stairs",
    sentence: "They used the escalator to reach the second floor.",
  },
  {
    id: 2,
    title: "Arcade",
    bangla: "আর্কেড",
    synonymous: "Shopping arcade, Mall section",
    sentence: "The arcade was filled with various gaming and shopping stalls.",
  },
  {
    id: 3,
    title: "Fitting room",
    bangla: "ফিটিং রুম",
    synonymous: "Dressing room, Changing room",
    sentence: "She went to the fitting room to try on the dress.",
  },
  {
    id: 4,
    title: "Food court",
    bangla: "ফুড কোর্ট",
    synonymous: "Food stalls, Dining area",
    sentence: "The food court offers a variety of cuisines.",
  },
  {
    id: 5,
    title: "Cashier",
    bangla: "ক্যাশিয়ার",
    synonymous: "Money collector, Checkout clerk",
    sentence: "The cashier processed her payment quickly.",
  },
  {
    id: 6,
    title: "Shelf",
    bangla: "শেলফ",
    synonymous: "Ledge, Rack",
    sentence: "Products were arranged neatly on each shelf.",
  },
  {
    id: 7,
    title: "Cash counter",
    bangla: "ক্যাশ কাউন্টার",
    synonymous: "Checkout counter, Cash register",
    sentence: "Customers lined up at the cash counter to pay.",
  },
  {
    id: 8,
    title: "Elevator",
    bangla: "এলিভেটর",
    synonymous: "Lift, Escalator",
    sentence: "They took the elevator to the top floor.",
  },
  {
    id: 9,
    title: "Window shopping",
    bangla: "উইন্ডো শপিং",
    synonymous: "Browsing, Looking around",
    sentence: "They enjoyed window shopping without buying anything.",
  },
  {
    id: 10,
    title: "Ladies' Room",
    bangla: "লেডিস রুম",
    synonymous: "Women's restroom, Powder room",
    sentence: "She went to the ladies' room to freshen up.",
  },

  {
    id: 1,
    title: "Playground",
    bangla: "খেলার মাঠ",
    synonymous: "Field, Sports ground",
    sentence: "Children play games on the playground after school.",
  },
  {
    id: 2,
    title: "Assembly",
    bangla: "সমাবেশ",
    synonymous: "Gathering, Meeting",
    sentence: "The assembly was held in the school hall.",
  },
  {
    id: 3,
    title: "Blackboard",
    bangla: "ব্ল্যাকবোর্ড",
    synonymous: "Chalkboard, Writing board",
    sentence: "The teacher wrote the lesson on the blackboard.",
  },
  {
    id: 4,
    title: "Desk",
    bangla: "টেবিল",
    synonymous: "Table, Workstation",
    sentence:
      "He placed his books on the desk before starting the study session.",
  },
  {
    id: 5,
    title: "Exercise copy",
    bangla: "ব্যায়াম কপি",
    synonymous: "Practice book, Notebook",
    sentence: "She used the exercise copy to complete her homework.",
  },
  {
    id: 6,
    title: "Library",
    bangla: "গ্রন্থাগার",
    synonymous: "Book room, Study room",
    sentence: "The library is where students can borrow books.",
  },
  {
    id: 7,
    title: "Locker",
    bangla: "লকার",
    synonymous: "Cabinet, Safe",
    sentence: "She kept her books in the locker during gym class.",
  },
  {
    id: 8,
    title: "Basketball court",
    bangla: "বাস্কেটবল কোর্ট",
    synonymous: "Basketball arena, Court",
    sentence: "The basketball court was busy with practice sessions.",
  },
  {
    id: 9,
    title: "Canteen",
    bangla: "ক্যানটিন",
    synonymous: "Cafeteria, Dining hall",
    sentence: "Students have lunch at the canteen during breaks.",
  },
  {
    id: 10,
    title: "Noticeboard",
    bangla: "বিজ্ঞপ্তি বোর্ড",
    synonymous: "Bulletin board, Information board",
    sentence: "The noticeboard displayed important announcements for students.",
  },
  {
    id: 11,
    title: "Playing field",
    bangla: "খেলার মাঠ",
    synonymous: "Sports field, Game area",
    sentence: "The school organized a football match in the playing field.",
  },
  {
    id: 12,
    title: "Assemblage",
    bangla: "সমাবেশ",
    synonymous: "Gathering, Assembly",
    sentence: "The students gathered for the morning assemblage.",
  },
  {
    id: 13,
    title: "Chalkboard",
    bangla: "চাকবোর্ড",
    synonymous: "Blackboard, Writing board",
    sentence: "The teacher explained the math problem on the chalkboard.",
  },
  {
    id: 14,
    title: "Table",
    bangla: "টেবিল",
    synonymous: "Desk, Surface",
    sentence: "He placed the papers on the table for review.",
  },
  {
    id: 15,
    title: "Notebook",
    bangla: "নোটবুক",
    synonymous: "Exercise book, Writing pad",
    sentence: "She took detailed notes in her notebook during the lecture.",
  },
  {
    id: 16,
    title: "Book room",
    bangla: "বই রুম",
    synonymous: "Library, Reading room",
    sentence:
      "The book room is where you can find textbooks and reference books.",
  },
  {
    id: 17,
    title: "Cupboard",
    bangla: "কাবিনেট",
    synonymous: "Cabinet, Storage unit",
    sentence: "The teacher stored the extra materials in the cupboard.",
  },
  {
    id: 18,
    title: "Basketball arena",
    bangla: "বাস্কেটবল অঙ্গন",
    synonymous: "Basketball court, Sports arena",
    sentence: "The basketball arena was packed with fans for the final match.",
  },
  {
    id: 19,
    title: "Cafeteria",
    bangla: "ক্যান্টিন",
    synonymous: "Canteen, Dining hall",
    sentence: "The cafeteria served a variety of meals during lunchtime.",
  },
  {
    id: 20,
    title: "Bulletin board",
    bangla: "বিজ্ঞপ্তি বোর্ড",
    synonymous: "Noticeboard, Information board",
    sentence: "The bulletin board has notices about upcoming events.",
  },

  {
    id: 1,
    title: "Presentation",
    bangla: "প্রেজেন্টেশন",
    synonymous: "Demonstration, Display",
    sentence: "The professor gave a detailed presentation on climate change.",
  },
  {
    id: 2,
    title: "Projector",
    bangla: "প্রজেক্টর",
    synonymous: "Slide projector, Video projector",
    sentence:
      "The projector was set up to display the slides for the presentation.",
  },
  {
    id: 3,
    title: "Dormitory",
    bangla: "ডর্মিটরি",
    synonymous: "Hostel, Residence hall",
    sentence: "Students live in the dormitory during the academic year.",
  },
  {
    id: 4,
    title: "Lecture notes",
    bangla: "লেকচার নোটস",
    synonymous: "Class notes, Lecture material",
    sentence: "She reviewed her lecture notes before the exam.",
  },
  {
    id: 5,
    title: "Professor",
    bangla: "প্রফেসর",
    synonymous: "Instructor, Lecturer",
    sentence: "The professor gave a fascinating lecture on modern literature.",
  },
  {
    id: 6,
    title: "Essay",
    bangla: "প্রবন্ধ",
    synonymous: "Article, Paper",
    sentence: "He wrote a 500-word essay on the impact of technology.",
  },
  {
    id: 7,
    title: "Textbook",
    bangla: "টেক্সটবুক",
    synonymous: "Course book, Study book",
    sentence: "The textbook covered all the necessary topics for the exam.",
  },
  {
    id: 8,
    title: "Bench",
    bangla: "বেঞ্চ",
    synonymous: "Seat, Long chair",
    sentence: "The students sat on the bench during the outdoor lecture.",
  },
  {
    id: 9,
    title: "Handout",
    bangla: "হ্যান্ডআউট",
    synonymous: "Pamphlet, Flyer",
    sentence:
      "The teacher distributed handouts to the class with additional study materials.",
  },
  {
    id: 10,
    title: "Dais",
    bangla: "ডায়াস",
    synonymous: "Platform, Podium",
    sentence: "The speaker stood on the dais to address the audience.",
  },
  {
    id: 11,
    title: "Demonstration",
    bangla: "ডেমোনস্ট্রেশন",
    synonymous: "Exhibition, Presentation",
    sentence: "The scientist gave a live demonstration of the experiment.",
  },
  {
    id: 12,
    title: "Slide projector",
    bangla: "স্লাইড প্রজেক্টর",
    synonymous: "Overhead projector, Film projector",
    sentence:
      "The slide projector was used to display historical images during the lecture.",
  },
  {
    id: 13,
    title: "University accommodation",
    bangla: "বিশ্ববিদ্যালয় আবাসন",
    synonymous: "Campus housing, Dormitory",
    sentence:
      "University accommodation is available for international students.",
  },
  {
    id: 14,
    title: "Hand notes",
    bangla: "হ্যান্ড নোটস",
    synonymous: "Written notes, Jotted down notes",
    sentence: "She took hand notes during the class to help with her study.",
  },
  {
    id: 15,
    title: "Faculty member",
    bangla: "ফ্যাকালটি সদস্য",
    synonymous: "Teacher, Staff member",
    sentence: "Each faculty member is assigned a specific course to teach.",
  },
  {
    id: 16,
    title: "Write-up",
    bangla: "লেখা",
    synonymous: "Article, Composition",
    sentence:
      "The student submitted a write-up on the history of the university.",
  },
  {
    id: 17,
    title: "Course book",
    bangla: "কোর্স বই",
    synonymous: "Textbook, Course material",
    sentence:
      "The course book contains all the chapters we need for the semester.",
  },
  {
    id: 18,
    title: "Chair",
    bangla: "চেয়ার",
    synonymous: "Seat, Armchair",
    sentence: "Please take a chair and join the meeting.",
  },
  {
    id: 19,
    title: "Printed notes",
    bangla: "প্রিন্ট করা নোটস",
    synonymous: "Printed material, Photocopies",
    sentence: "The professor provided printed notes for the students.",
  },
  {
    id: 20,
    title: "Podium",
    bangla: "পডিয়াম",
    synonymous: "Lectern, Stage",
    sentence:
      "The speaker stood behind the podium to deliver the keynote address.",
  },

  {
    id: 1,
    title: "Hospital bed",
    bangla: "হাসপাতাল বিছানা",
    synonymous: "Patient bed, Medical bed",
    sentence:
      "The hospital bed was adjusted to a sitting position for the patient.",
  },
  {
    id: 2,
    title: "Bed pan",
    bangla: "বিছানা প্যান",
    synonymous: "Urine pan, Medical pan",
    sentence: "The nurse brought a bed pan to assist the patient.",
  },
  {
    id: 3,
    title: "I.V.",
    bangla: "আই.ভি.",
    synonymous: "Intravenous, Drip",
    sentence: "The patient was given fluids through an I.V. drip.",
  },
  {
    id: 4,
    title: "Medical chart",
    bangla: "মেডিকেল চার্ট",
    synonymous: "Patient record, Health chart",
    sentence:
      "The doctor reviewed the patient's medical chart before making a diagnosis.",
  },
  {
    id: 5,
    title: "Hospital gown",
    bangla: "হাসপাতাল গাউন",
    synonymous: "Patient gown, Hospital robe",
    sentence: "The patient changed into a hospital gown for the surgery.",
  },
  {
    id: 6,
    title: "Walker",
    bangla: "ওয়াকার",
    synonymous: "Walking aid, Support walker",
    sentence: "He used a walker to move around after the surgery.",
  },
  {
    id: 7,
    title: "Oxygen tank",
    bangla: "অক্সিজেন ট্যাংক",
    synonymous: "Oxygen cylinder, Respiratory tank",
    sentence: "The patient was given an oxygen tank to help with breathing.",
  },
  {
    id: 8,
    title: "X-ray",
    bangla: "এক্স-রে",
    synonymous: "Radiograph, Imaging scan",
    sentence: "The doctor ordered an X-ray to check for any fractures.",
  },
  {
    id: 9,
    title: "Patient",
    bangla: "রোগী",
    synonymous: "Sick person, Client",
    sentence: "The patient was resting comfortably in the room.",
  },
  {
    id: 10,
    title: "Crutches",
    bangla: "ক্রাচ",
    synonymous: "Walking aids, Cane",
    sentence: "The doctor gave him crutches to help him walk after the injury.",
  },
  {
    id: 11,
    title: "Roll-away bed",
    bangla: "রোল-অ্যাওয়ে বিছানা",
    synonymous: "Portable bed, Folding bed",
    sentence: "The hospital provided a roll-away bed for visitors to rest.",
  },
  {
    id: 12,
    title: "Portable commode",
    bangla: "পোর্টেবল কমোড",
    synonymous: "Mobile toilet, Travel toilet",
    sentence:
      "A portable commode was placed beside the patient's bed for convenience.",
  },
  {
    id: 13,
    title: "Intravenous injection",
    bangla: "ইনট্রাভেনাস ইনজেকশন",
    synonymous: "IV shot, IV medication",
    sentence: "The nurse administered an intravenous injection to the patient.",
  },
  {
    id: 14,
    title: "Case history",
    bangla: "কেস ইতিহাস",
    synonymous: "Patient history, Medical background",
    sentence:
      "The doctor reviewed the patient's case history before starting treatment.",
  },
  {
    id: 15,
    title: "Hospital apron",
    bangla: "হাসপাতাল অ্যাপ্রন",
    synonymous: "Medical apron, Protective apron",
    sentence:
      "The nurse wore a hospital apron to protect herself during the procedure.",
  },
  {
    id: 16,
    title: "Stroller",
    bangla: "স্ট্রোলার",
    synonymous: "Baby carriage, Pushchair",
    sentence: "The mother pushed the stroller through the park.",
  },
  {
    id: 17,
    title: "Oxygen cylinder",
    bangla: "অক্সিজেন সিলিন্ডার",
    synonymous: "Oxygen tank, Respiratory cylinder",
    sentence: "The hospital used oxygen cylinders for emergency patients.",
  },
  {
    id: 18,
    title: "Radiograph",
    bangla: "রেডিওগ্রাফ",
    synonymous: "X-ray, Imaging scan",
    sentence: "The radiograph showed no signs of fractures.",
  },
  {
    id: 19,
    title: "Hospital occupant",
    bangla: "হাসপাতালের বাসিন্দা",
    synonymous: "Patient, Inmate",
    sentence: "The hospital occupant was treated for a severe infection.",
  },
  {
    id: 20,
    title: "Cane, walking stick",
    bangla: "কেন, হাঁটার লাঠি",
    synonymous: "Walking aid, Stick",
    sentence: "He used a cane to help him walk after the surgery.",
  },
  {
    id: 21,
    title: "Masala",
    bangla: "মশলা",
    synonymous: "Spices, Seasoning",
    sentence: "The masala gave the curry a rich and aromatic flavor.",
  },
  {
    id: 22,
    title: "Water filter",
    bangla: "পানি ফিল্টার",
    synonymous: "Water purifier, Filtration system",
    sentence:
      "We use a water filter to ensure the water is clean and safe to drink.",
  },
  {
    id: 23,
    title: "Saucepan",
    bangla: "সসপ্যান",
    synonymous: "Cooking pot, Frying pan",
    sentence: "She heated the soup in a large saucepan.",
  },
  {
    id: 24,
    title: "Rack",
    bangla: "র্যাক",
    synonymous: "Shelf, Stand",
    sentence: "The rack in the kitchen holds the spices and condiments.",
  },
  {
    id: 25,
    title: "Kitchen sink",
    bangla: "কিচেন সিঙ্ক",
    synonymous: "Dishwasher sink, Wash basin",
    sentence: "She washed the vegetables in the kitchen sink.",
  },
  {
    id: 26,
    title: "Grater",
    bangla: "কুরিয়ে ফেলার যন্ত্র",
    synonymous: "Shredder, Zester",
    sentence: "I was sitting in the kitchen with a grater in my hand.",
  },
  {
    id: 27,
    title: "Kitchen cabinet",
    bangla: "কিচেন ক্যাবিনেট",
    synonymous: "Cupboard, Kitchen storage",
    sentence: "The kitchen cabinet stores all my cooking ingredients.",
  },
  {
    id: 28,
    title: "Cooking pots",
    bangla: "রান্নার পট",
    synonymous: "Cookware, Stew pot",
    sentence: "The cooking pots are kept inside the kitchen cabinet.",
  },
  {
    id: 7,
    title: "Bulb",
    bangla: "বাল্ব",
    synonymous: "Light bulb",
    sentence: "The light bulb in the room needs to be replaced.",
  },
  {
    id: 8,
    title: "Fridge",
    bangla: "ফ্রিজ",
    synonymous: "Refrigerator",
    sentence: "I placed the drinks in the fridge to cool them down.",
  },
  {
    id: 9,
    title: "Microwave",
    bangla: "মাইক্রোওয়েভ",
    synonymous: "Oven",
    sentence: "The food was heated in the microwave for two minutes.",
  },
  {
    id: 10,
    title: "Fruit bowl",
    bangla: "ফল পাত্র",
    synonymous: "Bowl",
    sentence: "The fruit bowl was filled with fresh apples and oranges.",
  },
  {
    id: 11,
    title: "Tube light",
    bangla: "টিউব লাইট",
    synonymous: "Light",
    sentence: "The tube light in the office is flickering.",
  },
  {
    id: 12,
    title: "Cutlery",
    bangla: "কাটেলি",
    synonymous: "Tableware",
    sentence: "The cutlery was neatly arranged on the dining table.",
  },
  {
    id: 13,
    title: "Sink",
    bangla: "সিঙ্ক",
    synonymous: "Wash basin",
    sentence: "I washed the dishes in the kitchen sink.",
  },
  {
    id: 14,
    title: "Glass",
    bangla: "গ্লাস",
    synonymous: "Mug",
    sentence: "She filled the glass with water.",
  },
  {
    id: 15,
    title: "Table cloth",
    bangla: "টেবিল কাপড়",
    synonymous: "Table mat",
    sentence: "The table cloth was stained after dinner.",
  },
  {
    id: 16,
    title: "Napkin",
    bangla: "ন্যাপকিন",
    synonymous: "Handkerchief",
    sentence: "She wiped her hands with a napkin after the meal.",
  },
  {
    id: 17,
    title: "Working desk",
    bangla: "ওয়ার্কিং ডেস্ক",
    synonymous: "Desk",
    sentence: "She sat at her working desk, organizing the documents.",
  },
  {
    id: 18,
    title: "Metal clip",
    bangla: "মেটাল ক্লিপ",
    synonymous: "Paper clip",
    sentence: "He used a metal clip to hold the papers together.",
  },
  {
    id: 19,
    title: "Calendar",
    bangla: "ক্যালেন্ডার",
    synonymous: "Date planner",
    sentence: "I marked my appointments on the calendar.",
  },
  {
    id: 20,
    title: "Rubber bands",
    bangla: "রাবার ব্যান্ড",
    synonymous: "Elastic bands",
    sentence: "She used rubber bands to bundle the documents.",
  },
  {
    id: 21,
    title: "Correction fluid",
    bangla: "কোরেকশন ফ্লুইড",
    synonymous: "Correction tape",
    sentence: "I used correction fluid to fix the mistake on the paper.",
  },
  {
    id: 22,
    title: "Punch machine",
    bangla: "পাঞ্চ মেশিন",
    synonymous: "Hole punch",
    sentence: "The punch machine was used to make holes in the papers.",
  },
  {
    id: 23,
    title: "Appointment book",
    bangla: "অ্যাপয়েন্টমেন্ট বুক",
    synonymous: "Diary",
    sentence: "She kept all her meetings in the appointment book.",
  },
  {
    id: 24,
    title: "File organizer",
    bangla: "ফাইল অর্গানাইজার",
    synonymous: "Document organizer",
    sentence: "The file organizer helped keep all the paperwork in order.",
  },
  {
    id: 25,
    title: "Bookshelf",
    bangla: "বুকশেলফ",
    synonymous: "Book rack",
    sentence: "The bookshelf was filled with novels and textbooks.",
  },
  {
    id: 26,
    title: "Desk lamp",
    bangla: "ডেস্ক ল্যাম্প",
    synonymous: "Table lamp",
    sentence: "She turned on the desk lamp to read at night.",
  },
  {
    id: 27,
    title: "Luggage trolley",
    bangla: "লােগজ trolley",
    synonymous: "Luggage cart",
    sentence:
      "He used the luggage trolley to transport his bags to the check-in counter.",
  },
  {
    id: 28,
    title: "Air ticket",
    bangla: "এয়ার টিকেট",
    synonymous: "Flight ticket",
    sentence: "She showed her air ticket to the staff at the gate.",
  },
  {
    id: 29,
    title: "Boarding pass",
    bangla: "বোর্ডিং পাস",
    synonymous: "Flight pass",
    sentence:
      "The airline attendant scanned the boarding pass before allowing entry to the plane.",
  },
  {
    id: 30,
    title: "Carry-on luggage",
    bangla: "ক্যারি-অন ল্যাগেজ",
    synonymous: "Hand luggage",
    sentence: "The carry-on luggage was stored in the overhead bin.",
  },
  {
    id: 31,
    title: "Immigration",
    bangla: "ইমিগ্রেশন",
    synonymous: "Border control",
    sentence: "She had to clear immigration before entering the country.",
  },
  {
    id: 32,
    title: "Security check",
    bangla: "সিকিউরিটি চেক",
    synonymous: "Security screening",
    sentence:
      "Passengers need to go through a security check before boarding the flight.",
  },
  {
    id: 33,
    title: "Skycap",
    bangla: "স্কাইক্যাপ",
    synonymous: "Porter",
    sentence:
      "The skycap helped the passenger with their luggage at the airport.",
  },
  {
    id: 34,
    title: "Snack bar",
    bangla: "স্ন্যাক বার",
    synonymous: "Concession stand",
    sentence: "We grabbed some food from the snack bar before our flight.",
  },
  {
    id: 35,
    title: "Waiting area",
    bangla: "ওয়েটিং এরিয়া",
    synonymous: "Passenger lounge",
    sentence:
      "The waiting area was crowded with travelers waiting for their flights.",
  },
  {
    id: 36,
    title: "Airport shop",
    bangla: "এয়ারপোর্ট শপ",
    synonymous: "Duty-free shop",
    sentence: "She bought a souvenir from the airport shop.",
  },
  {
    id: 37,
    title: "Pilot",
    bangla: "পাইলট",
    synonymous: "Airline captain",
    sentence: "The pilot safely landed the aircraft after a smooth flight.",
  },
  {
    id: 38,
    title: "Flight attendant",
    bangla: "ফ্লাইট অ্যাটেনড্যান্ট",
    synonymous: "Air stewardess",
    sentence:
      "The flight attendant provided us with snacks and drinks during the flight.",
  },
  {
    id: 39,
    title: "Overhead locker",
    bangla: "ওভারহেড লকার",
    synonymous: "Overhead compartment",
    sentence: "You can store your carry-on luggage in the overhead locker.",
  },
  {
    id: 40,
    title: "Aisle",
    bangla: "আইল",
    synonymous: "Passageway",
    sentence:
      "Please remain seated while the aisle is being cleared for service.",
  },
  {
    id: 41,
    title: "Life vest",
    bangla: "লাইফ ভেস্ট",
    synonymous: "Life jacket",
    sentence: "Each passenger was instructed on how to wear the life vest.",
  },
  {
    id: 42,
    title: "Armrest",
    bangla: "আর্মরেস্ট",
    synonymous: "Seat arm",
    sentence: "The armrest between the seats was raised for more space.",
  },
  {
    id: 43,
    title: "Tray-table",
    bangla: "ট্রে-টেবিল",
    synonymous: "Fold-down table",
    sentence: "I folded down the tray-table to have lunch on the plane.",
  },
  {
    id: 44,
    title: "Lavatory",
    bangla: "ল্যাভাটরি",
    synonymous: "Toilet",
    sentence: "The lavatory is located at the back of the aircraft.",
  },
  {
    id: 45,
    title: "Reading light",
    bangla: "রিডিং লাইট",
    synonymous: "Personal light",
    sentence:
      "She turned on her reading light to read the book during the flight.",
  },
  {
    id: 46,
    title: "Galley",
    bangla: "গ্যালি",
    synonymous: "Kitchen",
    sentence: "The flight attendants prepared the meals in the galley.",
  },
  {
    id: 47,
    title: "Terminal",
    bangla: "টার্মিনাল",
    synonymous: "Train depot",
    sentence:
      "I waited for my train at the terminal, surrounded by other passengers.",
  },
  {
    id: 48,
    title: "Ticket machine",
    bangla: "পিকট কাটার মেশিন",
    synonymous: "Ticket kiosk",
    sentence: "I purchased my ticket from the ticket machine at the station.",
  },
  {
    id: 49,
    title: "Passenger",
    bangla: "যাত্রী",
    synonymous: "Commuter",
    sentence: "The passengers were waiting in line to board the train.",
  },
  {
    id: 50,
    title: "Wagon",
    bangla: "ওয়াগন",
    synonymous: "Cart",
    sentence:
      "The wagons were loaded with luggage as they passed by the station.",
  },
  {
    id: 51,
    title: "Timetable",
    bangla: "সময়সূচি",
    synonymous: "Train schedules",
    sentence: "The timetable displayed the arrival times for all trains.",
  },
  {
    id: 52,
    title: "Platform",
    bangla: "প্ল্যাটফর্ম",
    synonymous: "Railway platform",
    sentence: "The train was approaching the platform where I was waiting.",
  },
  {
    id: 53,
    title: "Station master",
    bangla: "স্টেশন মাস্টার",
    synonymous: "Station manager",
    sentence:
      "The station master made an announcement that the train was arriving soon.",
  },
  {
    id: 54,
    title: "Passenger section",
    bangla: "যাত্রী সেকশন",
    synonymous: "Waiting room",
    sentence: "I waited in the passenger section for the train to arrive.",
  },
  {
    id: 55,
    title: "Ticket checker",
    bangla: "পিকট চেকার",
    synonymous: "Ticket inspector",
    sentence: "The ticket checker asked for my ticket as I boarded the train.",
  },
  {
    id: 56,
    title: "Porter",
    bangla: "কুলি",
    synonymous: "Carrier",
    sentence: "The porter helped me carry my luggage to the train.",
  },
  {
    id: 57,
    title: "Bus stop",
    bangla: "বাস স্টপ",
    synonymous: "Bus depot",
    sentence: "I waited at the bus stop for my bus to arrive.",
  },
  {
    id: 58,
    title: "Route map",
    bangla: "রুট ম্যাপ",
    synonymous: "Route outline",
    sentence:
      "I looked at the route map to see which buses passed through my area.",
  },
  {
    id: 59,
    title: "Conductor",
    bangla: "কন্ডাক্টর",
    synonymous: "Helper",
    sentence:
      "The conductor helped us with our tickets and gave us directions.",
  },
  {
    id: 60,
    title: "Indicator",
    bangla: "ইন্ডিকেটর",
    synonymous: "Blinker",
    sentence: "The driver used the indicator to signal that he was turning.",
  },
  {
    id: 61,
    title: "Windscreen",
    bangla: "উইন্ডস্ক্রীন",
    synonymous: "Windshield",
    sentence:
      "The windscreen was covered in rain, making it hard to see clearly.",
  },
  {
    id: 62,
    title: "Luggage compartment",
    bangla: "লােগজ কম্পার্টমেন্ট",
    synonymous: "Luggage storage",
    sentence: "I placed my bags in the luggage compartment of the bus.",
  },
  {
    id: 63,
    title: "Wiper",
    bangla: "ওয়াইপার",
    synonymous: "Windscreen wiper",
    sentence: "The wiper cleaned the windshield during the heavy rain.",
  },
  {
    id: 64,
    title: "Steering wheel",
    bangla: "স্টিয়ারিং হুইল",
    synonymous: "Wheel",
    sentence:
      "The driver turned the steering wheel to navigate through the traffic.",
  },
  {
    id: 65,
    title: "Coach",
    bangla: "কোচ",
    synonymous: "Local bus",
    sentence: "I took the coach to the city center.",
  },
  {
    id: 66,
    title: "Public bus",
    bangla: "পাবলিক বাস",
    synonymous: "Bus",
    sentence: "The public bus was crowded, but I managed to find a seat.",
  },

  {
    id: 67,
    title: "Beverage",
    bangla: "পানীয়",
    synonymous: "Drinks",
    sentence: "I ordered a cold beverage to refresh myself.",
  },
  {
    id: 68,
    title: "Chef",
    bangla: "শেফ",
    synonymous: "Cook",
    sentence: "The chef prepared a delicious meal for the guests.",
  },
  {
    id: 69,
    title: "Menu",
    bangla: "মেনু",
    synonymous: "Food list",
    sentence: "I checked the menu to decide what to order.",
  },
  {
    id: 70,
    title: "Dessert",
    bangla: "মিষ্টান্ন",
    synonymous: "Sweet food",
    sentence: "For dessert, we had chocolate cake and ice cream.",
  },
  {
    id: 71,
    title: "Appetizer",
    bangla: "অ্যাপেটাইজার",
    synonymous: "Starter",
    sentence: "We started with a light appetizer before the main course.",
  },
  {
    id: 72,
    title: "Dish",
    bangla: "ডিশ",
    synonymous: "Food",
    sentence: "This dish is my favorite when I dine out.",
  },
  {
    id: 73,
    title: "Ketchup",
    bangla: "কেচাপ",
    synonymous: "Sauce",
    sentence: "I added ketchup to my fries for extra flavor.",
  },
  {
    id: 74,
    title: "Napkin",
    bangla: "ন্যাপকিন",
    synonymous: "Cloth",
    sentence: "I wiped my hands with a napkin after eating.",
  },
  {
    id: 75,
    title: "Waiter",
    bangla: "ওয়েটার",
    synonymous: "Server",
    sentence: "The waiter took our orders and brought the food to our table.",
  },
  {
    id: 76,
    title: "Meal",
    bangla: "মিল",
    synonymous: "Food",
    sentence: "We had a hearty meal to end the day.",
  },
  {
    id: 77,
    title: "Public bus",
    bangla: "পাবলিক বাস",
    synonymous: "Bus",
    sentence: "The public bus was crowded, but I managed to find a seat.",
  },
  {
    id: 78,
    title: "Commentary box",
    bangla: "কেমেন্ট্রি বক্স",
    synonymous: "Evaluation box",
    sentence: "The commentary box provides live updates during the match.",
  },
  {
    id: 79,
    title: "Scoreboard",
    bangla: "স্কোরবোর্ড",
    synonymous: "Display board",
    sentence: "The scoreboard showed the final score of the game.",
  },
  {
    id: 80,
    title: "Referee",
    bangla: "রেফারি",
    synonymous: "Judge",
    sentence: "The referee made a controversial call during the match.",
  },
  {
    id: 81,
    title: "Spectators",
    bangla: "দর্শক",
    synonymous: "Audience",
    sentence: "Spectators cheered loudly for their team during the game.",
  },
  {
    id: 82,
    title: "Flag",
    bangla: "ঝান্ডা",
    synonymous: "National flag",
    sentence: "The national flag was raised in honor of the winning team.",
  },
  {
    id: 83,
    title: "Dressing room",
    bangla: "ড্রেসিং রুম",
    synonymous: "Greenroom",
    sentence: "The players gathered in the dressing room before the match.",
  },
  {
    id: 84,
    title: "Bench",
    bangla: "বেঞ্চ",
    synonymous: "Lawn seat",
    sentence:
      "The coach instructed the players from the bench during the game.",
  },
  {
    id: 85,
    title: "Players",
    bangla: "খেলোয়াড়",
    synonymous: "Athletes",
    sentence: "The players showed great teamwork throughout the match.",
  },
  {
    id: 86,
    title: "Trophy",
    bangla: "ট্রফি",
    synonymous: "Champion's cup",
    sentence: "The team lifted the trophy in celebration after winning.",
  },
  {
    id: 87,
    title: "Whistle",
    bangla: "হুইসল",
    synonymous: "Signal",
    sentence: "The referee blew the whistle to signal the end of the match.",
  },
  {
    id: 88,
    title: "Washbowl",
    bangla: "ওয়াশেবাউল",
    synonymous: "Sink",
    sentence: "I washed my hands in the washbowl after coming home.",
  },
  {
    id: 89,
    title: "Bathroom cabinet",
    bangla: "বাথরুম ক্যাবিনেট",
    synonymous: "Cupboard",
    sentence: "I kept my toiletries in the bathroom cabinet.",
  },
  {
    id: 90,
    title: "Mirror",
    bangla: "মিরর",
    synonymous: "Looking glass",
    sentence: "She looked at her reflection in the bathroom mirror.",
  },
  {
    id: 91,
    title: "Towel",
    bangla: "টাওয়েল",
    synonymous: "Drying cloth",
    sentence: "I used a towel to dry myself after the shower.",
  },
  {
    id: 92,
    title: "Bathtub",
    bangla: "বাথটাব",
    synonymous: "Bathing tub",
    sentence: "He relaxed in the bathtub after a long day.",
  },
  {
    id: 93,
    title: "Comb",
    bangla: "কোম্ব",
    synonymous: "Hair brush",
    sentence: "She combed her hair before heading out.",
  },
  {
    id: 94,
    title: "Toilet paper",
    bangla: "টয়লেট পেপার",
    synonymous: "Toilet tissue roll",
    sentence: "There was no toilet paper in the bathroom.",
  },
  {
    id: 95,
    title: "Scales",
    bangla: "স্কেলস",
    synonymous: "Weighing machine",
    sentence: "I checked my weight on the bathroom scales.",
  },
  {
    id: 96,
    title: "Facewash",
    bangla: "ফেসওয়াশ",
    synonymous: "Cleanser",
    sentence: "She used facewash to clean her skin.",
  },
  {
    id: 97,
    title: "Detergent",
    bangla: "ডিটারজেন্ট",
    synonymous: "Soap",
    sentence: "I used detergent to wash the bathroom floor.",
  },
  {
    id: 98,
    title: "Popsicles",
    bangla: "পপিসকালস",
    synonymous: "Ice-cream",
    sentence: "We enjoyed popsicles by the beach on a hot day.",
  },
  {
    id: 99,
    title: "Flip-flops",
    bangla: "ফ্লিপ-ফ্লপস",
    synonymous: "Sandals",
    sentence: "I wore flip-flops to the beach for comfort.",
  },
  {
    id: 100,
    title: "Swimming trunks",
    bangla: "সুইমিং ট্রাঙ্কস",
    synonymous: "Shorts",
    sentence: "He changed into his swimming trunks before diving in.",
  },
  {
    id: 101,
    title: "Deck-chair",
    bangla: "ডেক-চেয়ার",
    synonymous: "Beach chair",
    sentence: "We relaxed on a deck-chair while watching the sunset.",
  },
  {
    id: 102,
    title: "Sandpit",
    bangla: "স্যান্ডপিট",
    synonymous: "Sand toys",
    sentence: "Children played with sand toys in the sandpit.",
  },
  {
    id: 103,
    title: "Set",
    bangla: "সেট",
    synonymous: "Cool box",
    sentence: "I packed a set of drinks in the cooler for the beach.",
  },
  {
    id: 104,
    title: "Cooler",
    bangla: "কুলার",
    synonymous: "Cool box",
    sentence: "We kept the drinks in the cooler to stay fresh.",
  },
  {
    id: 105,
    title: "Sunscreen",
    bangla: "সানস্ক্রিন",
    synonymous: "Sun cream",
    sentence: "I applied sunscreen to avoid sunburn.",
  },
  {
    id: 106,
    title: "Beach ball",
    bangla: "বিচ বল",
    synonymous: "Volleyball",
    sentence: "We played beach volleyball with a colorful beach ball.",
  },
  {
    id: 107,
    title: "Conch",
    bangla: "কন্চ",
    synonymous: "Shell",
    sentence: "I found a beautiful conch shell on the shore.",
  },
  {
    id: 108,
    title: "Beach vendor",
    bangla: "বিচ ভেন্ডর",
    synonymous: "Hawker",
    sentence: "The beach vendor was selling fresh coconut water.",
  },
  {
    id: 109,
    title: "Shopping mall",
    bangla: "শপিং মল",
    synonymous: "Market",
    sentence:
      "The shopping mall was filled with people buying clothes and accessories.",
  },
  {
    id: 110,
    title: "Apartment building",
    bangla: "অ্যাপার্টমেন্ট বিল্ডিং",
    synonymous: "High-rise building",
    sentence: "She lives in an apartment building on the 10th floor.",
  },
  {
    id: 111,
    title: "Department store",
    bangla: "ডিপার্টমেন্ট স্টোর",
    synonymous: "Store",
    sentence: "We bought all our home appliances from the department store.",
  },
  {
    id: 112,
    title: "Beauty salon",
    bangla: "বিউটি স্যালন",
    synonymous: "Parlour",
    sentence: "She went to the beauty salon to get her hair styled.",
  },
  {
    id: 113,
    title: "Pharmacy",
    bangla: "ফার্মেসি",
    synonymous: "Drugstore",
    sentence: "I went to the pharmacy to buy some medicine for my cold.",
  },
  {
    id: 114,
    title: "Restaurant",
    bangla: "রেস্টুরেন্ট",
    synonymous: "Fast food shop",
    sentence: "We had a wonderful dinner at the restaurant by the lake.",
  },
  {
    id: 115,
    title: "Amusement park",
    bangla: "অ্যামিউজমেন্ট পার্ক",
    synonymous: "Theme park",
    sentence:
      "The amusement park was filled with excited families and children.",
  },
  {
    id: 116,
    title: "Educational institution",
    bangla: "এডুকেশনাল ইনস্টিটিউশন",
    synonymous: "School, College, University",
    sentence:
      "He is studying engineering at an educational institution in the city.",
  },
  {
    id: 117,
    title: "Movie theatre",
    bangla: "মুভি থিয়েটার",
    synonymous: "Multiplex",
    sentence:
      "We watched the latest blockbuster at the movie theatre last night.",
  },
  {
    id: 118,
    title: "Slum",
    bangla: "বস্তি",
    synonymous: "Shanty area",
    sentence:
      "Many people live in a slum area where basic facilities are limited.",
  },
  {
    id: 119,
    title: "Haystack",
    bangla: "হেইস্ট্যাক",
    synonymous: "Hay",
    sentence:
      "The haystack in the field was used to store dry grass for the winter.",
  },
  {
    id: 120,
    title: "Pond",
    bangla: "পন্ড",
    synonymous: "Small lake",
    sentence:
      "We went to the pond to fish and enjoy the peaceful surroundings.",
  },
  {
    id: 121,
    title: "Cornfield",
    bangla: "কর্নফিল্ড",
    synonymous: "Paddy field",
    sentence: "The cornfield stretched across the valley, ready for harvest.",
  },
  {
    id: 122,
    title: "Livestock",
    bangla: "লাইভস্টক",
    synonymous: "Domestic animals",
    sentence:
      "The farmer took care of his livestock, including cows and chickens.",
  },
  {
    id: 123,
    title: "Farmer",
    bangla: "ফার্মার",
    synonymous: "Peasant",
    sentence: "The farmer woke up early to tend to his fields and animals.",
  },
  {
    id: 124,
    title: "Boat",
    bangla: "বোট",
    synonymous: "Canoe",
    sentence: "We rowed the boat across the river, enjoying the calm water.",
  },
  {
    id: 125,
    title: "Fisherman",
    bangla: "ফিশারম্যান",
    synonymous: "Angler",
    sentence:
      "The fisherman cast his line into the water, hoping for a big catch.",
  },
  {
    id: 126,
    title: "Yard",
    bangla: "ইয়ার্ড",
    synonymous: "Courtyard",
    sentence: "The children played in the yard, running around and laughing.",
  },
  {
    id: 127,
    title: "Thatched cottage",
    bangla: "থ্যাচড কটেজ",
    synonymous: "Thatched roof",
    sentence: "The cottage had a charming thatched roof and a small garden.",
  },
  {
    id: 128,
    title: "Clinic",
    bangla: "ক্লিনিক",
    synonymous: "Medical centre",
    sentence:
      "She went to the clinic for a check-up and some advice on her health.",
  },
  {
    id: 129,
    title: "Tablet",
    bangla: "ট্যাবলেট",
    synonymous: "Pill",
    sentence: "He took a tablet for his headache and felt better soon.",
  },
  {
    id: 130,
    title: "Injection",
    bangla: "ইনজেকশন",
    synonymous: "Shot",
    sentence: "The doctor gave me an injection to prevent the infection.",
  },
  {
    id: 131,
    title: "Cough Syrup",
    bangla: "কাফ সিরাপ",
    synonymous: "Cough medicine",
    sentence: "She drank some cough syrup to soothe her throat.",
  },
  {
    id: 132,
    title: "Ointment",
    bangla: "অয়েন্টমেন্ট",
    synonymous: "Cream",
    sentence: "The doctor recommended applying ointment to the wound.",
  },
  {
    id: 133,
    title: "Drops",
    bangla: "ড্রপস",
    synonymous: "Nasal drops",
    sentence: "I put some drops in my eyes to relieve the irritation.",
  },
  {
    id: 134,
    title: "Wet wipes",
    bangla: "ওয়েট ওয়াইপস",
    synonymous: "Wipes",
    sentence: "She used wet wipes to clean her hands after the meal.",
  },
  {
    id: 135,
    title: "Deodorant",
    bangla: "ডিওডোরেন্ট",
    synonymous: "Antiperspirant",
    sentence: "I applied deodorant to stay fresh throughout the day.",
  },
  {
    id: 136,
    title: "Painkillers",
    bangla: "পেইনকিলার্স",
    synonymous: "Pain relievers",
    sentence: "He took painkillers to ease the discomfort after the injury.",
  },
  {
    id: 137,
    title: "Vitamins",
    bangla: "ভিটামিনস",
    synonymous: "Supplements",
    sentence: "She takes vitamins every morning to maintain her health.",
  },
  {
    id: 138,
    title: "Pharmacist",
    bangla: "ফার্মাসিস্ট",
    synonymous: "Chemist",
    sentence: "The pharmacist advised me on which medication to take.",
  },
  {
    id: 139,
    title: "Facial",
    bangla: "ফেসিয়াল",
    synonymous: "Face massage",
    sentence: "She went to the spa for a relaxing facial treatment.",
  },
  {
    id: 140,
    title: "Beautician",
    bangla: "বিউটিশিয়ান",
    synonymous: "Aesthetician",
    sentence: "The beautician gave her a makeover for the party.",
  },
  {
    id: 141,
    title: "Wig",
    bangla: "উইগ",
    synonymous: "Hair extension",
    sentence: "She wore a wig to change her hairstyle for the event.",
  },
  {
    id: 142,
    title: "Scissors",
    bangla: "কাঁচি",
    synonymous: "Trimmer",
    sentence: "The hairdresser used scissors to cut my hair.",
  },
  {
    id: 143,
    title: "Hair gel",
    bangla: "হেয়ার জেল",
    synonymous: "Styling gel",
    sentence: "He applied hair gel to style his hair for the party.",
  },
  {
    id: 144,
    title: "Face pack",
    bangla: "ফেস প্যাক",
    synonymous: "Face mask",
    sentence: "I applied a face pack to rejuvenate my skin.",
  },
  {
    id: 145,
    title: "Hair clip",
    bangla: "হেয়ার ক্লিপ",
    synonymous: "Clippers",
    sentence: "She used a hair clip to secure her bangs.",
  },
  {
    id: 146,
    title: "Hair Straightener",
    bangla: "হেয়ার স্ট্রেইটনার",
    synonymous: "Straightener",
    sentence: "She used a hair straightener to smooth her curly hair.",
  },
  {
    id: 147,
    title: "Hairdryer",
    bangla: "হেয়ার ড্রায়ার",
    synonymous: "Blow dryer",
    sentence: "He used a hairdryer to dry his hair quickly after the shower.",
  },
  {
    id: 148,
    title: "Moisturizer",
    bangla: "ময়েশ্চারাইজার",
    synonymous: "Lotion",
    sentence: "She applied moisturizer to keep her skin soft and hydrated.",
  },
  {
    id: 149,
    title: "Blanket",
    bangla: "কম্বল",
    synonymous: "Sheet",
    sentence: "I wrapped myself in a warm blanket during the winter night.",
  },
  {
    id: 150,
    title: "Campfire",
    bangla: "ক্যাম্পফায়ার",
    synonymous: "Bonfire",
    sentence: "We gathered around the campfire to roast marshmallows.",
  },
  {
    id: 151,
    title: "Sleeping bag",
    bangla: "স্লিপিং ব্যাগ",
    synonymous: "Bedroll",
    sentence: "He slept inside his sleeping bag under the stars.",
  },
  {
    id: 152,
    title: "Cutlery",
    bangla: "কাটলারি",
    synonymous: "Knife and fork",
    sentence: "The restaurant set the table with cutlery for each guest.",
  },
  {
    id: 153,
    title: "Garden",
    bangla: "বাগান",
    synonymous: "Lawn",
    sentence: "She spends a lot of time in the garden planting flowers.",
  },
  {
    id: 154,
    title: "Lake",
    bangla: "হ্রদ",
    synonymous: "Lagoon",
    sentence: "We enjoyed a peaceful afternoon by the lake.",
  },
  {
    id: 155,
    title: "Barbecue",
    bangla: "বারবিকিউ",
    synonymous: "Grill",
    sentence: "We had a barbecue in the backyard with friends.",
  },
  {
    id: 156,
    title: "Lemonade",
    bangla: "লেমনেড",
    synonymous: "Lemon juice",
    sentence: "She made fresh lemonade with lemons from the garden.",
  },
  {
    id: 157,
    title: "Flashlight",
    bangla: "ফ্ল্যাশলাইট",
    synonymous: "Torchlight",
    sentence: "We used a flashlight to find our way through the dark forest.",
  },
  {
    id: 158,
    title: "Lunch box",
    bangla: "লাঞ্চ বক্স",
    synonymous: "Luncheon",
    sentence: "She packed her sandwich in a lunch box for school.",
  },
  {
    id: 159,
    title: "Credit card",
    bangla: "ক্রেডিট কার্ড",
    synonymous: "Bank card",
    sentence: "I used my credit card to pay for the groceries.",
  },
  {
    id: 160,
    title: "Cheque book",
    bangla: "চেকবুক",
    synonymous: "Cheque",
    sentence: "She wrote a cheque from her cheque book to pay the bills.",
  },
  {
    id: 161,
    title: "Deposit slip",
    bangla: "ডিপোজিট স্লিপ",
    synonymous: "Bank slip",
    sentence:
      "I filled out the deposit slip before depositing the money into my account.",
  },
  {
    id: 162,
    title: "Bank officer",
    bangla: "ব্যাংক কর্মকর্তা",
    synonymous: "Officer",
    sentence: "The bank officer helped me with my loan application.",
  },
  {
    id: 163,
    title: "Safe-deposit vault",
    bangla: "সেফ-ডিপোজিট ভল্ট",
    synonymous: "Bank vault",
    sentence: "The bank keeps valuable items in the safe-deposit vault.",
  },
  {
    id: 164,
    title: "Money order",
    bangla: "মানি অর্ডার",
    synonymous: "Postal order",
    sentence: "He sent the money using a money order through the post office.",
  },
  {
    id: 165,
    title: "ATM card",
    bangla: "এটিএম কার্ড",
    synonymous: "Debit card",
    sentence: "You can withdraw money using your ATM card at any ATM.",
  },
  {
    id: 166,
    title: "Monthly statement",
    bangla: "মাসিক বিবরণী",
    synonymous: "Bank statement",
    sentence: "I reviewed my monthly statement to track my expenses.",
  },
  {
    id: 167,
    title: "Loan application",
    bangla: "ঋণ আবেদন",
    synonymous: "Credit request",
    sentence: "She submitted her loan application to the bank.",
  },
  {
    id: 168,
    title: "Bank teller",
    bangla: "ব্যাংক টেলার",
    synonymous: "Cashier",
    sentence: "The bank teller assisted me with my transaction.",
  },
  {
    id: 169,
    title: "Sauna",
    bangla: "সৌনা",
    synonymous: "Steam bath",
    sentence: "I relaxed in the sauna after a long workout.",
  },
  {
    id: 170,
    title: "Lobby",
    bangla: "লবি",
    synonymous: "Lounge",
    sentence: "The lobby was beautifully decorated for the holiday season.",
  },
  {
    id: 171,
    title: "Bellboy",
    bangla: "বেলবয়",
    synonymous: "Bellman",
    sentence: "The bellboy helped carry our luggage to the room.",
  },
  {
    id: 172,
    title: "Key card",
    bangla: "কী কার্ড",
    synonymous: "Room card",
    sentence: "I used the key card to unlock the hotel room door.",
  },
  {
    id: 173,
    title: "Gymnasium",
    bangla: "জিমনেশিয়াম",
    synonymous: "Gym",
    sentence: "I work out at the gymnasium every morning.",
  },
  {
    id: 174,
    title: "Front desk",
    bangla: "ফ্রন্ট ডেস্ক",
    synonymous: "Reception desk",
    sentence: "I checked in at the front desk when I arrived at the hotel.",
  },
  {
    id: 175,
    title: "Swimming pool",
    bangla: "সুইমিং পুল",
    synonymous: "Pool",
    sentence: "We spent the afternoon relaxing by the swimming pool.",
  },
  {
    id: 176,
    title: "Brochure",
    bangla: "ব্রোশিওর",
    synonymous: "Booklet",
    sentence:
      "The brochure provided detailed information about the hotel's amenities.",
  },
  {
    id: 177,
    title: "Housekeeping",
    bangla: "হাউসকিপিং",
    synonymous: "Room service",
    sentence: "The housekeeping staff cleaned our room every day.",
  },
  {
    id: 178,
    title: "Valet",
    bangla: "ভ্যালেট",
    synonymous: "Attendant",
    sentence: "The valet parked our car when we arrived at the hotel.",
  },
  {
    id: 179,
    title: "Forehead",
    bangla: "মাথার উপরের অংশ",
    synonymous: "Forehead",
    sentence: "She wiped the sweat off her forehead.",
  },
  {
    id: 180,
    title: "Eyebrow",
    bangla: "ভ্রু",
    synonymous: "Eyebrow",
    sentence: "He raised his eyebrow in surprise.",
  },
  {
    id: 181,
    title: "Elbow",
    bangla: "কনুই",
    synonymous: "Elbow",
    sentence: "She bumped her elbow against the wall.",
  },
  {
    id: 182,
    title: "Cheek",
    bangla: "গাল",
    synonymous: "Cheek",
    sentence: "She kissed him on the cheek before leaving.",
  },
  {
    id: 183,
    title: "Chin",
    bangla: "ঠোঁটের নিচের অংশ",
    synonymous: "Chin",
    sentence: "He stroked his chin while thinking.",
  },
  {
    id: 184,
    title: "Wrist",
    bangla: "হাতের কবজি",
    synonymous: "Wrist",
    sentence: "She wore a bracelet on her wrist.",
  },
  {
    id: 185,
    title: "Palm",
    bangla: "হাতের তালু",
    synonymous: "Palm",
    sentence: "She held the flower gently in the palm of her hand.",
  },
  {
    id: 186,
    title: "Lips",
    bangla: "হাঁট",
    synonymous: "Lips",
    sentence: "She smiled, revealing her soft lips.",
  },
  {
    id: 187,
    title: "Thigh",
    bangla: "যাত্রার অংশ",
    synonymous: "Thigh",
    sentence: "He had a tattoo on his thigh.",
  },
  {
    id: 188,
    title: "Feet",
    bangla: "পা",
    synonymous: "Feet",
    sentence: "She stood on her feet for hours while shopping.",
  },
  {
    id: 189,
    title: "Cardamom",
    bangla: "এলাচ",
    synonymous: "Cardamom",
    sentence: "She added cardamom to the tea for extra flavor.",
  },
  {
    id: 190,
    title: "Spring onion",
    bangla: "পেঁয়াজের শীষ",
    synonymous: "Scallion",
    sentence: "He garnished the soup with some chopped spring onions.",
  },
  {
    id: 191,
    title: "Black pepper",
    bangla: "কালো মরিচ",
    synonymous: "Pepper",
    sentence: "She sprinkled black pepper on her salad for added spice.",
  },
  {
    id: 192,
    title: "Bay leaf",
    bangla: "তেজপাতা",
    synonymous: "Bay leaf",
    sentence: "The recipe called for a couple of bay leaves to add fragrance.",
  },
  {
    id: 193,
    title: "Paprika",
    bangla: "প্যাপ্রিকা",
    synonymous: "Paprika",
    sentence: "The chicken was seasoned with paprika and garlic.",
  },
  {
    id: 194,
    title: "Cumin seed",
    bangla: "জিরে",
    synonymous: "Cumin",
    sentence: "Cumin seeds are often used in Indian cuisine.",
  },
  {
    id: 195,
    title: "Coriander leaves",
    bangla: "ধনে পাতা",
    synonymous: "Coriander",
    sentence: "She garnished the curry with fresh coriander leaves.",
  },
  {
    id: 196,
    title: "Clove",
    bangla: "লবঙ্গ",
    synonymous: "Clove",
    sentence: "The clove added a strong, aromatic flavor to the dish.",
  },
  {
    id: 197,
    title: "Cinnamon",
    bangla: "দারচিনি",
    synonymous: "Cinnamon",
    sentence: "She added a stick of cinnamon to the tea for a warm aroma.",
  },
  {
    id: 198,
    title: "Raisin",
    bangla: "খেজুর",
    synonymous: "Raisin",
    sentence: "She added raisins to the oatmeal for sweetness.",
  },
  {
    id: 199,
    title: "Pomegranate",
    bangla: "ডালিম",
    synonymous: "Pomegranate",
    sentence: "She ate a fresh pomegranate for dessert.",
  },
  {
    id: 200,
    title: "Pear",
    bangla: "নাশপাতি",
    synonymous: "Pear",
    sentence: "He sliced a pear and added it to the salad.",
  },
  {
    id: 201,
    title: "Plum",
    bangla: "আলুবোখারা",
    synonymous: "Plum",
    sentence: "The plums were ripe and sweet.",
  },
  {
    id: 202,
    title: "Sapodilla",
    bangla: "চিকা",
    synonymous: "Sapodilla",
    sentence: "She enjoyed a ripe sapodilla after lunch.",
  },
  {
    id: 203,
    title: "Date",
    bangla: "খেজুর",
    synonymous: "Date",
    sentence: "Dates are a popular fruit during Ramadan.",
  },
  {
    id: 204,
    title: "Custard apple",
    bangla: "সিতাফল",
    synonymous: "Custard apple",
    sentence: "Custard apple is delicious and full of vitamins.",
  },
  {
    id: 205,
    title: "Wood apple",
    bangla: "বেল",
    synonymous: "Wood apple",
    sentence: "He made a refreshing drink with wood apple.",
  },
  {
    id: 206,
    title: "Star fruit",
    bangla: "কামরাঙ্গা",
    synonymous: "Star fruit",
    sentence: "The star fruit's shape is unique and tangy in flavor.",
  },
  {
    id: 207,
    title: "Palm-cabbage",
    bangla: "পাম-কেরিজ",
    synonymous: "Palm cabbage",
    sentence: "Palm-cabbage is a delicacy in many tropical regions.",
  },
  {
    id: 199,
    title: "Pomegranate",
    bangla: "ডালিম",
    synonymous: "Pomegranate",
    sentence: "She ate a fresh pomegranate for dessert.",
  },
  {
    id: 200,
    title: "Pear",
    bangla: "নাশপাতি",
    synonymous: "Pear",
    sentence: "He sliced a pear and added it to the salad.",
  },
  {
    id: 201,
    title: "Plum",
    bangla: "আলুবোখারা",
    synonymous: "Plum",
    sentence: "The plums were ripe and sweet.",
  },
  {
    id: 202,
    title: "Sapodilla",
    bangla: "চিকা",
    synonymous: "Sapodilla",
    sentence: "She enjoyed a ripe sapodilla after lunch.",
  },
  {
    id: 203,
    title: "Date",
    bangla: "খেজুর",
    synonymous: "Date",
    sentence: "Dates are a popular fruit during Ramadan.",
  },
  {
    id: 204,
    title: "Custard apple",
    bangla: "সিতাফল",
    synonymous: "Custard apple",
    sentence: "Custard apple is delicious and full of vitamins.",
  },
  {
    id: 205,
    title: "Wood apple",
    bangla: "বেল",
    synonymous: "Wood apple",
    sentence: "He made a refreshing drink with wood apple.",
  },
  {
    id: 206,
    title: "Star fruit",
    bangla: "কামরাঙ্গা",
    synonymous: "Star fruit",
    sentence: "The star fruit's shape is unique and tangy in flavor.",
  },
  {
    id: 207,
    title: "Palm-cabbage",
    bangla: "পাম-কেরিজ",
    synonymous: "Palm cabbage",
    sentence: "Palm-cabbage is a delicacy in many tropical regions.",
  },
  {
    serialID: 1,
    id: 208,
    title: "Pomegranate",
    bangla: "ডালিম",
    synonymous: "Pomegranate",
    sentence: "She ate a fresh pomegranate for dessert.",
  },
  {
    serialID: 2,
    id: 209,
    title: "Pear",
    bangla: "নাশপাতি",
    synonymous: "Pear",
    sentence: "He sliced a pear and added it to the salad.",
  },
  {
    serialID: 3,
    id: 210,
    title: "Plum",
    bangla: "আলুবোখারা",
    synonymous: "Plum",
    sentence: "The plums were ripe and sweet.",
  },
  {
    serialID: 4,
    id: 211,
    title: "Sapodilla",
    bangla: "চিকা",
    synonymous: "Sapodilla",
    sentence: "She enjoyed a ripe sapodilla after lunch.",
  },
  {
    serialID: 5,
    id: 212,
    title: "Date",
    bangla: "খেজুর",
    synonymous: "Date",
    sentence: "Dates are a popular fruit during Ramadan.",
  },
  {
    serialID: 6,
    id: 213,
    title: "Custard apple",
    bangla: "সিতাফল",
    synonymous: "Custard apple",
    sentence: "Custard apple is delicious and full of vitamins.",
  },
  {
    serialID: 7,
    id: 214,
    title: "Wood apple",
    bangla: "বেল",
    synonymous: "Wood apple",
    sentence: "He made a refreshing drink with wood apple.",
  },
  {
    serialID: 8,
    id: 215,
    title: "Star fruit",
    bangla: "কামরাঙ্গা",
    synonymous: "Star fruit",
    sentence: "The star fruit's shape is unique and tangy in flavor.",
  },
  {
    serialID: 9,
    id: 216,
    title: "Palm-cabbage",
    bangla: "পাম-কেরিজ",
    synonymous: "Palm cabbage",
    sentence: "Palm-cabbage is a delicacy in many tropical regions.",
  },
  {
    serialID: 10,
    id: 217,
    title: "Induction Cooker",
    bangla: "ইনডাকশন কুকার",
    synonymous: "Induction stove",
    sentence:
      "The induction cooker is energy-efficient and heats food quickly.",
  },
  {
    serialID: 11,
    id: 218,
    title: "Oven",
    bangla: "ওভেন",
    synonymous: "Baking oven",
    sentence: "She baked a delicious cake in the oven.",
  },
  {
    serialID: 12,
    id: 219,
    title: "Hair Dryer",
    bangla: "হেয়ার ড্রায়ার",
    synonymous: "Blow dryer",
    sentence: "He used the hair dryer to dry his hair quickly.",
  },
  {
    serialID: 13,
    id: 220,
    title: "Graphic Tablet",
    bangla: "গ্রাফিক ট্যাবলেট",
    synonymous: "Drawing tablet",
    sentence: "The graphic tablet allows for detailed digital artwork.",
  },
  {
    serialID: 14,
    id: 221,
    title: "Washing Machine",
    bangla: "ওয়াশিং মেশিন",
    synonymous: "Laundry machine",
    sentence: "She loaded the laundry machine with clothes for washing.",
  },
  {
    serialID: 15,
    id: 222,
    title: "Earphone",
    bangla: "ইয়ারফোন",
    synonymous: "Headphones",
    sentence: "He listened to music through his earphones while jogging.",
  },
  {
    serialID: 16,
    id: 223,
    title: "Refrigerator",
    bangla: "ফ্রিজ",
    synonymous: "Fridge",
    sentence: "The refrigerator keeps food fresh for a long time.",
  },
  {
    serialID: 17,
    id: 224,
    title: "Electric Kettle",
    bangla: "ইলেকট্রিক কেটল",
    synonymous: "Electric kettle",
    sentence: "She boiled water for tea in the electric kettle.",
  },
  {
    serialID: 18,
    id: 225,
    title: "Blender",
    bangla: "ব্লেন্ডার",
    synonymous: "Juicer",
    sentence:
      "He blended the ingredients into a smooth juice using the blender.",
  },
  {
    serialID: 19,
    id: 226,
    title: "Induction Hob",
    bangla: "ইনডাকশন হব",
    synonymous: "Induction cooktop",
    sentence: "The induction hob provides fast and precise heating.",
  },
  {
    serialID: 20,
    id: 227,
    title: "Microwave",
    bangla: "মাইক্রোওয়েভ",
    synonymous: "Microwave oven",
    sentence: "She reheated the leftovers in the microwave.",
  },
  {
    serialID: 21,
    id: 228,
    title: "Blow Dryer",
    bangla: "ব্লো ড্রায়ার",
    synonymous: "Hair dryer",
    sentence: "He dried his hair with the blow dryer before heading out.",
  },
  {
    serialID: 22,
    id: 229,
    title: "Drawing Tablet",
    bangla: "ড্রইং ট্যাবলেট",
    synonymous: "Graphic tablet",
    sentence: "The artist used a drawing tablet to sketch digitally.",
  },
  {
    serialID: 23,
    id: 230,
    title: "Laundry Machine",
    bangla: "লন্ড্রি মেশিন",
    synonymous: "Washing machine",
    sentence: "The laundry machine cleaned the clothes with ease.",
  },
  {
    serialID: 24,
    id: 231,
    title: "Headphone",
    bangla: "হেডফোন",
    synonymous: "Earphones",
    sentence: "He wore headphones to listen to his favorite playlist.",
  },
  {
    serialID: 25,
    id: 232,
    title: "Fridge",
    bangla: "ফ্রিজ",
    synonymous: "Refrigerator",
    sentence: "The fridge keeps fruits and vegetables fresh for days.",
  },
  {
    serialID: 26,
    id: 233,
    title: "Automatic Kettle",
    bangla: "অটোমেটিক কেটল",
    synonymous: "Electric kettle",
    sentence: "The automatic kettle shuts off once the water boils.",
  },
  {
    serialID: 27,
    id: 234,
    title: "Mixer",
    bangla: "মিক্সার",
    synonymous: "Blender",
    sentence: "She used a mixer to blend the ingredients for the cake.",
  },
  {
    id: 208,
    title: "Picnic area",
    bangla: "পিকনিক এলাকা",
    synonymous: "Picnic spot",
    sentence: "Families enjoy gathering in the picnic area on weekends.",
  },
  {
    id: 209,
    title: "Greenery",
    bangla: "সবুজ এলাকা",
    synonymous: "Lush vegetation",
    sentence:
      "The park is filled with lush greenery, providing a refreshing atmosphere.",
  },
  {
    id: 210,
    title: "Merry-go-round",
    bangla: "মেরি-গো-রাউন্ড",
    synonymous: "Carousel",
    sentence: "Children were excited to ride the merry-go-round at the fair.",
  },
  {
    id: 211,
    title: "Food cart",
    bangla: "খাবারের গাড়ি",
    synonymous: "Food stall",
    sentence:
      "The food cart served delicious hot dogs and snacks at the event.",
  },
  {
    id: 212,
    title: "Jogging path",
    bangla: "দৌড়ানোর পথ",
    synonymous: "Running track",
    sentence: "The jogging path is ideal for a morning run or walk.",
  },
  {
    id: 213,
    title: "Sculpture",
    bangla: "ভাস্কর্য",
    synonymous: "Statue",
    sentence: "The sculpture in the park was a beautiful work of art.",
  },
  {
    id: 214,
    title: "Bench",
    bangla: "বেঞ্চ",
    synonymous: "Seating",
    sentence: "The bench under the tree offered a perfect spot to relax.",
  },
  {
    id: 215,
    title: "Seesaw",
    bangla: "সীসও",
    synonymous: "Teeter-totter",
    sentence: "The kids had fun playing on the seesaw at the playground.",
  },
  {
    id: 216,
    title: "Ferris wheel",
    bangla: "ফেরিস হুইল",
    synonymous: "Big wheel",
    sentence: "The Ferris wheel offered a spectacular view of the city.",
  },
  {
    id: 217,
    title: "Fountain",
    bangla: "ঝর্ণা",
    synonymous: "Water feature",
    sentence: "The fountain in the plaza provided a tranquil atmosphere.",
  },
  {
    id: 218,
    title: "Picnic spot",
    bangla: "পিকনিক স্পট",
    synonymous: "Picnic area",
    sentence: "The picnic spot by the lake is popular during summer months.",
  },
  {
    id: 219,
    title: "Trees",
    bangla: "গাছ",
    synonymous: "Shrubs",
    sentence:
      "The trees along the road provided shade during the hot afternoon.",
  },
  {
    id: 220,
    title: "Roundabout",
    bangla: "রাউন্ডঅ্যাবাউন্ড",
    synonymous: "Traffic circle",
    sentence: "The roundabout at the city center helps to manage traffic flow.",
  },
  {
    id: 221,
    title: "Food stall",
    bangla: "খাবারের স্টল",
    synonymous: "Food cart",
    sentence:
      "The food stall sold fresh fruits and juices during the festival.",
  },
  {
    id: 222,
    title: "Running track",
    bangla: "দৌড়ানোর ট্র্যাক",
    synonymous: "Jogging path",
    sentence:
      "The running track is lined with trees, making it a scenic place to exercise.",
  },
  {
    id: 223,
    title: "Statue",
    bangla: "ভাস্কর্য",
    synonymous: "Sculpture",
    sentence: "The statue of the founder stood proudly in the town square.",
  },
  {
    id: 224,
    title: "Seat",
    bangla: "সীট",
    synonymous: "Chair",
    sentence: "There was a vacant seat next to the window on the bus.",
  },
  {
    id: 225,
    title: "Teeter-totter",
    bangla: "টিটার-টটার",
    synonymous: "Seesaw",
    sentence:
      "The teeter-totter at the playground was perfect for two children to play together.",
  },
  {
    id: 226,
    title: "Big wheel",
    bangla: "বিগ হুইল",
    synonymous: "Ferris wheel",
    sentence: "Riding the big wheel was the highlight of the carnival.",
  },
  {
    id: 227,
    title: "Throng of people",
    bangla: "ভিড়",
    synonymous: "Crowd",
    sentence:
      "A throng of people gathered outside the concert hall waiting for the show to begin.",
  },
  {
    id: 228,
    title: "Bookstall",
    bangla: "বইয়ের স্টল",
    synonymous: "Bookstore",
    sentence: "I bought a novel from the bookstall at the local market.",
  },
  {
    id: 229,
    title: "Journalist",
    bangla: "সাংবাদিক",
    synonymous: "Reporter",
    sentence: "The journalist asked for an interview after the event.",
  },
  {
    id: 230,
    title: "Stage",
    bangla: "মঞ্চ",
    synonymous: "Podium",
    sentence: "The actor stood on the stage and delivered a powerful speech.",
  },
  {
    id: 231,
    title: "Children",
    bangla: "শিশুরা",
    synonymous: "Youngsters",
    sentence: "The children played joyfully in the park all afternoon.",
  },
  {
    id: 232,
    title: "Bookseller",
    bangla: "বই বিক্রেতা",
    synonymous: "Book salesman",
    sentence: "The bookseller offered a discount on all fiction books.",
  },
  {
    id: 233,
    title: "Food shop",
    bangla: "খাবারের দোকান",
    synonymous: "Snacks bar",
    sentence: "The food shop in the mall serves quick snacks and beverages.",
  },
  {
    id: 234,
    title: "Book launching ceremony",
    bangla: "বই উন্মোচন অনুষ্ঠান",
    synonymous: "Promotional programme",
    sentence:
      "The book launching ceremony was held at the city's central library.",
  },
  {
    id: 235,
    title: "Queue",
    bangla: "লাইনে দাঁড়ানো",
    synonymous: "Line",
    sentence: "People stood in a queue to buy tickets for the concert.",
  },
  {
    id: 236,
    title: "Flower crown",
    bangla: "ফুলের মুকুট",
    synonymous: "Flower headband",
    sentence: "She wore a beautiful flower crown during the wedding ceremony.",
  },
  {
    id: 237,
    title: "Trainer",
    bangla: "প্রশিক্ষক",
    synonymous: "Instructor",
    sentence:
      "The trainer guided me through a series of exercises to improve my stamina.",
  },
  {
    id: 238,
    title: "Press-ups",
    bangla: "হাতে ভর দিয়ে শরীর ওঠানো",
    synonymous: "Push-ups",
    sentence: "He completed 20 press-ups before taking a break.",
  },
  {
    id: 239,
    title: "Fitness cycle",
    bangla: "ফিটনেস সাইকেল",
    synonymous: "Exercise cycle",
    sentence: "I spent 30 minutes on the fitness cycle at the gym.",
  },
  {
    id: 240,
    title: "Exercise ball",
    bangla: "ব্যায়াম বল",
    synonymous: "Stability ball",
    sentence: "The exercise ball is great for improving core strength.",
  },
  {
    id: 241,
    title: "Crunches",
    bangla: "পেটের ব্যায়াম",
    synonymous: "Sit-ups",
    sentence: "She did 50 crunches as part of her abdominal workout.",
  },
  {
    id: 242,
    title: "Athletic shoes",
    bangla: "খেলাধুলার জুতা",
    synonymous: "Sports shoes",
    sentence:
      "It's important to wear athletic shoes when running to avoid injury.",
  },
  {
    id: 243,
    title: "Jump rope",
    bangla: "জাম্প রোপ",
    synonymous: "Skipping rope",
    sentence: "Jumping rope is an excellent cardiovascular workout.",
  },
  {
    id: 244,
    title: "Gym bag",
    bangla: "জিম ব্যাগ",
    synonymous: "Duffel bag",
    sentence:
      "I packed my gym bag with clothes and shoes for my workout session.",
  },
  {
    id: 245,
    title: "Treadmill",
    bangla: "ট্রেডমিল",
    synonymous: "Running machine",
    sentence: "I ran 5 kilometers on the treadmill at the gym.",
  },
  {
    id: 246,
    title: "Weight lifting",
    bangla: "ওজন তুলনা",
    synonymous: "Strength training",
    sentence: "He focused on weight lifting to build muscle mass.",
  },
  {
    id: 247,
    title: "Shopkeeper",
    bangla: "দোকানদার",
    synonymous: "Storekeeper",
    sentence: "The shopkeeper greeted the customers as they entered the store.",
  },
  {
    id: 248,
    title: "Signboard",
    bangla: "সাইনবোর্ড",
    synonymous: "Billboard",
    sentence:
      "The shop's signboard was brightly lit and visible from a distance.",
  },
  {
    id: 249,
    title: "Canned food",
    bangla: "ক্যানড ফুড",
    synonymous: "Preserved food",
    sentence:
      "Canned food is often used as a backup when fresh food is unavailable.",
  },
  {
    id: 250,
    title: "Bread",
    bangla: "রুটি",
    synonymous: "Loaf",
    sentence: "I bought a loaf of bread from the bakery for breakfast.",
  },
  {
    id: 251,
    title: "Pickle",
    bangla: "আচার",
    synonymous: "Relish",
    sentence: "She added pickle to her sandwich for extra flavor.",
  },
  {
    id: 252,
    title: "Flour",
    bangla: "আটা",
    synonymous: "All purpose flour",
    sentence: "Flour is the main ingredient in most baking recipes.",
  },
  {
    id: 253,
    title: "Stationery",
    bangla: "লিখন সামগ্রী",
    synonymous: "Writing supplies",
    sentence: "She bought a notebook and some pens from the stationery shop.",
  },
  {
    id: 254,
    title: "Biscuit",
    bangla: "বিস্কুট",
    synonymous: "Cookies",
    sentence: "I enjoy having a biscuit with my afternoon tea.",
  },
  {
    id: 255,
    title: "Cold drinks",
    bangla: "ঠান্ডা পানীয়",
    synonymous: "Cold beverages",
    sentence: "On a hot day, cold drinks are the best way to stay refreshed.",
  },
  {
    id: 256,
    title: "Mustard",
    bangla: "সরিষা",
    synonymous: "Mustard seeds",
    sentence: "She added mustard to the salad dressing for a tangy flavor.",
  },

  {
    id: 257,
    title: "Dairy products",
    bangla: "ডেইরি পণ্য",
    synonymous: "Milk products",
    sentence:
      "Dairy products like milk, cheese, and butter are essential in many households.",
  },
  {
    id: 258,
    title: "Jam",
    bangla: "জ্যাম",
    synonymous: "Marmalade",
    sentence: "I like to spread jam on my toast in the morning.",
  },
  {
    id: 259,
    title: "Sausage",
    bangla: "সসেজ",
    synonymous: "Meat",
    sentence: "Sausages are commonly eaten for breakfast in many cultures.",
  },
  {
    id: 260,
    title: "Frozen food",
    bangla: "জমানো খাবার",
    synonymous: "Canned food",
    sentence:
      "Frozen food is convenient for quick meals when you're short on time.",
  },
  {
    id: 261,
    title: "Shopping cart",
    bangla: "শপিং কার্ট",
    synonymous: "Trolley",
    sentence:
      "I filled my shopping cart with groceries and headed to the checkout.",
  },
  {
    id: 262,
    title: "Cornflakes",
    bangla: "কর্নফ্লেক্স",
    synonymous: "Cereal",
    sentence: "I enjoy cornflakes with milk for breakfast every day.",
  },
  {
    id: 263,
    title: "Cash register",
    bangla: "ক্যাশ রেজিস্টার",
    synonymous: "Till, money box",
    sentence: "The cashier rang up the total on the cash register.",
  },
  {
    id: 264,
    title: "Baby food",
    bangla: "শিশু খাবার",
    synonymous: "Kids' meals",
    sentence: "The store has a section dedicated to baby food and kids' meals.",
  },
  {
    id: 265,
    title: "Utensils",
    bangla: "বিন্যাস সামগ্রী",
    synonymous: "Appliances",
    sentence:
      "The kitchen was filled with various utensils, ready for cooking.",
  },
  {
    id: 266,
    title: "Footwear",
    bangla: "জুতা",
    synonymous: "Shoes",
    sentence: "I bought a new pair of footwear for the upcoming winter season.",
  },
  {
    id: 267,
    title: "Auditorium",
    bangla: "অডিটোরিয়াম",
    synonymous: "Hall",
    sentence: "The auditorium was filled with excited moviegoers.",
  },
  {
    id: 268,
    title: "Big screen",
    bangla: "বড় পর্দা",
    synonymous: "Silver screen",
    sentence: "The movie was best experienced on the big screen.",
  },
  {
    id: 269,
    title: "Audience",
    bangla: "দর্শক",
    synonymous: "Viewer",
    sentence: "The audience cheered as the movie started.",
  },
  {
    id: 270,
    title: "Popcorn",
    bangla: "পপকর্ণ",
    synonymous: "Corn kernels",
    sentence: "I always enjoy a bucket of popcorn during the movie.",
  },
  {
    id: 271,
    title: "3D glasses",
    bangla: "৩ডি চশমা",
    synonymous: "Movie glasses",
    sentence:
      "Don’t forget to wear your 3D glasses for the immersive experience.",
  },
  {
    id: 272,
    title: "Movie poster",
    bangla: "মুভি পোস্টার",
    synonymous: "Film poster",
    sentence:
      "The movie poster had colorful artwork showcasing the main characters.",
  },
  {
    id: 273,
    title: "Snacks counter",
    bangla: "স্ন্যাকস কাউন্টার",
    synonymous: "Food stand",
    sentence: "The snacks counter had a variety of treats for moviegoers.",
  },
  {
    id: 274,
    title: "Ticket counter",
    bangla: "টিকেট কাউন্টার",
    synonymous: "Ticket booth",
    sentence: "I stood in line at the ticket counter to get my movie tickets.",
  },
  {
    id: 275,
    title: "Soft drinks",
    bangla: "সফট ড্রিঙ্ক",
    synonymous: "Drinks",
    sentence:
      "I grabbed a soft drink from the concession stand before heading into the theater.",
  },
  {
    id: 276,
    title: "Curtain",
    bangla: "কার্টেন",
    synonymous: "Drape",
    sentence: "The curtain slowly rose to reveal the start of the movie.",
  },
  {
    id: 277,
    title: "Librarian",
    bangla: "লাইব্রেরিয়ান",
    synonymous: "Library keeper",
    sentence: "The librarian helped me find the book I was looking for.",
  },
  {
    id: 278,
    title: "Periodicals",
    bangla: "পিরিওডিক্যালস",
    synonymous: "Magazines",
    sentence:
      "The library has a section dedicated to periodicals and magazines.",
  },
  {
    id: 279,
    title: "Library card",
    bangla: "লাইব্রেরী কার্ড",
    synonymous: "ID card",
    sentence: "You need a library card to borrow books from the library.",
  },
  {
    id: 280,
    title: "Circulation desk",
    bangla: "সার্কুলেশন ডেস্ক",
    synonymous: "Ch",
    sentence: "I went to the circulation desk to return my books.",
  },
  {
    id: 281,
    title: "Atlas",
    bangla: "অ্যাটলাস",
    synonymous: "Ch",
    sentence: "The atlas provided detailed maps of countries around the world.",
  },
  {
    id: 282,
    title: "Due date",
    bangla: "ডিউ ডেট",
    synonymous: "Ch",
    sentence: "The due date for returning the book is next Friday.",
  },
  {
    id: 283,
    title: "Children's section",
    bangla: "শিশুদের সেকশন",
    synonymous: "Ch",
    sentence: "The children's section is full of colorful picture books.",
  },
  {
    id: 284,
    title: "Barcode",
    bangla: "বারকোড",
    synonymous: "Ch",
    sentence: "Each book in the library has a barcode for tracking.",
  },
  {
    id: 285,
    title: "Fiction section",
    bangla: "ফিকশন সেকশন",
    synonymous: "Ch",
    sentence: "I prefer to browse the fiction section for my next read.",
  },
  {
    id: 286,
    title: "Photocopy machine",
    bangla: "ফোটোকপি মেশিন",
    synonymous: "Ch",
    sentence: "I used the photocopy machine to make a copy of my library card.",
  },

  {
    id: 287,
    title: "Bride",
    bangla: "ব্রাইড",
    synonymous: "Newly-wed woman",
    sentence: "The bride looked stunning in her wedding dress.",
  },
  {
    id: 288,
    title: "Groom",
    bangla: "গরুম",
    synonymous: "Bridegroom",
    sentence: "The groom waited eagerly at the altar for his bride.",
  },
  {
    id: 289,
    title: "Wedding photographer",
    bangla: "বিয়ের ফটোগ্রাফার",
    synonymous: "Photographer",
    sentence:
      "The wedding photographer captured every beautiful moment of the ceremony.",
  },
  {
    id: 290,
    title: "Stage",
    bangla: "মঞ্চ",
    synonymous: "Platform",
    sentence:
      "The wedding ceremony took place on a beautifully decorated stage.",
  },
  {
    id: 291,
    title: "Floral decoration",
    bangla: "ফুলের সাজসজ্জা",
    synonymous: "Floral arrangement",
    sentence: "The floral decoration in the wedding hall was exquisite.",
  },
  {
    id: 292,
    title: "Guests",
    bangla: "অতিথি",
    synonymous: "Visitors",
    sentence:
      "The guests were greeted warmly as they arrived at the wedding venue.",
  },
  {
    id: 293,
    title: "Video camera",
    bangla: "ভিডিও ক্যামেরা",
    synonymous: "Camcorder",
    sentence:
      "The video camera recorded the entire wedding ceremony for the couple.",
  },
  {
    id: 294,
    title: "Dining table",
    bangla: "ডাইনিং টেবিল",
    synonymous: "Dining area",
    sentence: "The dining table was set beautifully for the wedding reception.",
  },
  {
    id: 295,
    title: "Waiter",
    bangla: "ওয়েটার",
    synonymous: "Server",
    sentence:
      "The waiter served the guests their delicious meals during the reception.",
  },
  {
    id: 296,
    title: "Chandelier",
    bangla: "শ্যান্ডেলিয়ার",
    synonymous: "Candelabra",
    sentence:
      "The chandelier hanging from the ceiling added a touch of elegance to the wedding hall.",
  },
  {
    id: 297,
    title: "Fried hilsha fish",
    bangla: "ভাজা ইলিশ মাছ",
    synonymous: "Hilsha fish",
    sentence: "Fried hilsha fish is a delicacy in Bengali cuisine.",
  },
  {
    id: 298,
    title: "Fermented rice",
    bangla: "ভাতের আচার",
    synonymous: "Soaked rice",
    sentence:
      "Fermented rice is often served with hilsha fish in a traditional Bengali meal.",
  },
  {
    id: 299,
    title: "Procession",
    bangla: "মিছিল",
    synonymous: "Mass procession",
    sentence:
      "The procession of the bride and groom was accompanied by traditional music.",
  },
  {
    id: 300,
    title: "Mashed vegetables",
    bangla: "ম্যাশড সবজি",
    synonymous: "Vegetable paste",
    sentence:
      "Mashed vegetables are a healthy and popular dish in traditional meals.",
  },
  {
    id: 301,
    title: "Vibrant mask",
    bangla: "জ্বলজ্বলে মুখোশ",
    synonymous: "Colorful mask",
    sentence:
      "The vibrant mask worn by the dancers was a highlight of the festival.",
  },
  {
    id: 302,
    title: "Red and white dresses",
    bangla: "লাল এবং সাদা পোশাক",
    synonymous: "Red and white outfits",
    sentence: "Many people wore red and white dresses during the celebration.",
  },
  {
    id: 303,
    title: "Carnival",
    bangla: "কার্নিভাল",
    synonymous: "Festivity",
    sentence:
      "The carnival was filled with music, dancing, and vibrant costumes.",
  },
  {
    id: 304,
    title: "Country snacks",
    bangla: "গ্রামীণ খাবার",
    synonymous: "Traditional snacks",
    sentence:
      "Country snacks like pitha and sweets were served during the festival.",
  },
  {
    id: 305,
    title: "Earthen pot",
    bangla: "মাটির পট",
    synonymous: "Pottery",
    sentence:
      "The food was served in traditional earthen pots during the celebration.",
  },
  {
    id: 306,
    title: "Puppet show",
    bangla: "পুতুল প্রদর্শনী",
    synonymous: "Puppetry",
    sentence:
      "The puppet show was an enjoyable activity for children at the festival.",
  },
  {
    id: 307,
    title: "Enormous field",
    bangla: "এনরমাস মাঠ",
    synonymous: "Spacious area",
    sentence:
      "The festival was held in an enormous field with plenty of space for everyone.",
  },
  {
    id: 308,
    title: "Security guard",
    bangla: "সিকিউরিটি গার্ড",
    synonymous: "Watchman",
    sentence:
      "A security guard stood at the entrance to ensure the safety of the event.",
  },
  {
    id: 309,
    title: "Pavilion",
    bangla: "প্যাভিলিয়ন",
    synonymous: "Tent",
    sentence: "The exhibition was held in a large pavilion with many stalls.",
  },
  {
    id: 310,
    title: "Sale",
    bangla: "বিক্রয়",
    synonymous: "Discount",
    sentence: "There was a big sale on all items, with discounts up to 50%.",
  },
  {
    id: 311,
    title: "Foreign products",
    bangla: "বিদেশী পণ্য",
    synonymous: "International goods",
    sentence: "The market had a wide range of foreign products on display.",
  },
  {
    id: 312,
    title: "Car Park",
    bangla: "কার পার্ক",
    synonymous: "Parking lot",
    sentence:
      "The car park was full, and people had to park their vehicles on the roadside.",
  },
  {
    id: 313,
    title: "Crockery shops",
    bangla: "টিপি দোকান",
    synonymous: "Crockery store",
    sentence:
      "There are several crockery shops selling beautiful plates and bowls.",
  },
  {
    id: 314,
    title: "Cottage industry",
    bangla: "গ্রামীণ শিল্প",
    synonymous: "Handicraft",
    sentence:
      "The village is known for its cottage industry, producing handmade crafts.",
  },
  {
    id: 315,
    title: "Electronic device shops",
    bangla: "ইলেকট্রনিক ডিভাইস শপ",
    synonymous: "Gadget shops",
    sentence:
      "There are many electronic device shops in the mall offering the latest gadgets.",
  },
  {
    id: 316,
    title: "Furniture shops",
    bangla: "ফার্নিচার শপস",
    synonymous: "Furniture store",
    sentence:
      "I visited a few furniture shops to buy a new sofa for the living room.",
  },
  {
    id: 317,
    title: "Blazing sunlight",
    bangla: "প্রচন্ড রোদ",
    synonymous: "Scorching heat",
    sentence:
      "The blazing sunlight made it difficult to walk outside during the afternoon.",
  },
  {
    id: 318,
    title: "Shorts",
    bangla: "শর্টস",
    synonymous: "Short trousers",
    sentence: "He wore shorts to stay cool in the hot weather.",
  },
  {
    id: 319,
    title: "Sunshade",
    bangla: "সানশেড",
    synonymous: "Canopy",
    sentence: "The sunshade provided some relief from the scorching heat.",
  },
  {
    id: 320,
    title: "Popsicle",
    bangla: "পপিসিকল",
    synonymous: "Ice-cream",
    sentence: "I love having a popsicle to cool down on a hot day.",
  },
  {
    id: 321,
    title: "Cotton wear",
    bangla: "কটন ওয়্যার",
    synonymous: "Cotton garments",
    sentence: "Cotton wear is the most comfortable choice for summer clothing.",
  },
  {
    id: 322,
    title: "Sweat",
    bangla: "ঘাম",
    synonymous: "Perspiration",
    sentence: "The intense heat caused him to sweat heavily.",
  },
  {
    id: 323,
    title: "Umbrella",
    bangla: "ছাতা",
    synonymous: "Shade",
    sentence: "He used an umbrella for shade to protect himself from the sun.",
  },
  {
    id: 324,
    title: "Sunglasses",
    bangla: "সানগ্লাস",
    synonymous: "Eyeglasses",
    sentence:
      "Sunglasses are essential for protecting your eyes from harmful UV rays.",
  },
  {
    id: 325,
    title: "Sun hat",
    bangla: "সান হ্যাট",
    synonymous: "Hat",
    sentence:
      "She wore a wide-brimmed sun hat to shield her face from the sun.",
  },
  {
    id: 326,
    title: "Hand fan",
    bangla: "হ্যান্ড ফ্যান",
    synonymous: "Fan",
    sentence: "The hand fan helped cool me down on a hot summer afternoon.",
  },
  {
    id: 327,
    title: "Rain boots",
    bangla: "রেইন বুটস",
    synonymous: "Rubber boots",
    sentence:
      "I wore my rain boots to avoid getting my feet wet in the downpour.",
  },
  {
    id: 328,
    title: "Drizzle",
    bangla: "মেঘা",
    synonymous: "Sprinkle",
    sentence: "The drizzle made it just wet enough to need an umbrella.",
  },
  {
    id: 329,
    title: "Downpour",
    bangla: "ভারী বৃষ্টি",
    synonymous: "Torrential rain",
    sentence: "We had to seek shelter because of the heavy downpour.",
  },
  {
    id: 330,
    title: "Raincoat",
    bangla: "রেইনকোট",
    synonymous: "Water-repellent coat",
    sentence: "He wore his raincoat to stay dry during the sudden downpour.",
  },
  {
    id: 331,
    title: "Drenched",
    bangla: "ভিজে যাওয়া",
    synonymous: "Soaked",
    sentence: "I got drenched after forgetting to bring an umbrella.",
  },
  {
    id: 332,
    title: "Puddle",
    bangla: "পানির জমাট",
    synonymous: "Swamp",
    sentence: "There was a big puddle on the road after the rainstorm.",
  },
  {
    id: 333,
    title: "Slippery road",
    bangla: "পিচ্ছিল রাস্তা",
    synonymous: "Wet road",
    sentence:
      "The road became slippery after the rain, so we had to drive carefully.",
  },
  {
    id: 334,
    title: "Foggy",
    bangla: "কুয়াশাচ্ছন্ন",
    synonymous: "Gloomy, hazy",
    sentence: "The foggy weather made it difficult to see while driving.",
  },
  {
    id: 335,
    title: "Overcast sky",
    bangla: "মেঘলা আকাশ",
    synonymous: "Overclouded sky",
    sentence: "The overcast sky suggested that rain was coming soon.",
  },
  {
    id: 336,
    title: "Lightning",
    bangla: "বজ্রপাত",
    synonymous: "Thunder",
    sentence:
      "We saw a flash of lightning just before the thunderstorm started.",
  },
  {
    id: 337,
    title: "Overcoat",
    bangla: "ওভারকোট",
    synonymous: "Parka",
    sentence: "She wore an overcoat to protect herself from the cold winds.",
  },
  {
    id: 338,
    title: "Mittens",
    bangla: "মিটেন্স",
    synonymous: "Hand gloves",
    sentence: "I wore mittens to keep my hands warm during the snowstorm.",
  },
  {
    id: 339,
    title: "Fireplace",
    bangla: "ফায়ারপ্লেস",
    synonymous: "Hearth",
    sentence:
      "We gathered around the fireplace to stay warm during the winter evening.",
  },
  {
    id: 340,
    title: "Quilt",
    bangla: "কুইল্ট",
    synonymous: "Duvet",
    sentence: "The quilt kept me cozy and warm throughout the night.",
  },
  {
    id: 341,
    title: "Shawl",
    bangla: "শাল",
    synonymous: "Cape",
    sentence: "She wrapped herself in a shawl to ward off the chill.",
  },
  {
    id: 342,
    title: "Snowflake",
    bangla: "তুষারের পাতা",
    synonymous: "Snowfall",
    sentence:
      "Each snowflake is unique and adds to the beauty of the winter scene.",
  },
  {
    id: 343,
    title: "Earmuffs",
    bangla: "ইয়ারমাফস",
    synonymous: "Ear warmers",
    sentence: "I wore earmuffs to keep my ears warm while walking in the snow.",
  },
  {
    id: 344,
    title: "Radiator",
    bangla: "রেডিয়েটর",
    synonymous: "Heater",
    sentence: "The radiator kept the room warm during the cold winter nights.",
  },
  {
    id: 345,
    title: "Neck warmer",
    bangla: "নেক ওয়ারমার",
    synonymous: "Scarf",
    sentence: "I wore a neck warmer to protect my neck from the freezing wind.",
  },
  {
    id: 346,
    title: "Mist",
    bangla: "কুয়াশা",
    synonymous: "Fog",
    sentence: "The mist in the morning made it difficult to see far ahead.",
  },
  {
    id: 347,
    title: "High time",
    bangla: "হাই টাইম",
    synonymous: "About time",
    sentence: "It's high time we took a break and rested for a while.",
  },
  {
    id: 348,
    title: "Time flies",
    bangla: "টাইম ফ্লাইস",
    synonymous: "Time goes by",
    sentence: "It feels like time flies when you're having fun.",
  },
  {
    id: 349,
    title: "Kill time",
    bangla: "কিল টাইম",
    synonymous: "Passing the time",
    sentence: "I read a book to kill time while waiting for the train.",
  },
  {
    id: 350,
    title: "Run out of time",
    bangla: "রান আউট অফ টাইম",
    synonymous: "Clock is ticking",
    sentence: "We ran out of time before we could finish the project.",
  },
  {
    id: 351,
    title: "Time out",
    bangla: "টাইম আউট",
    synonymous: "Time off",
    sentence: "The coach called a time out to strategize during the game.",
  },
  {
    id: 352,
    title: "Matter of time",
    bangla: "ম্যাটার অফ টাইম",
    synonymous: "Forthcoming",
    sentence: "It's only a matter of time before we hear the results.",
  },
  {
    id: 353,
    title: "Ahead of time",
    bangla: "অ্যাহেড অফ টাইম",
    synonymous: "Beforehand",
    sentence: "We arrived ahead of time to get the best seats.",
  },
  {
    id: 354,
    title: "Race against time",
    bangla: "রেস অ্যাগেইনস্ট টাইম",
    synonymous: "Race against the clock",
    sentence:
      "We were in a race against time to finish the project before the deadline.",
  },
  {
    id: 355,
    title: "Nick of time",
    bangla: "নিক অফ টাইম",
    synonymous: "At the eleventh hour",
    sentence:
      "We completed the task in the nick of time, just before the deadline.",
  },
  {
    id: 356,
    title: "All in good time",
    bangla: "অল ইন গুড টাইম",
    synonymous: "All in due time",
    sentence: "You'll get the answer, but all in good time.",
  },
  {
    id: 357,
    title: "Bird watching",
    bangla: "বাডর্ ওয়ািচিং",
    synonymous: "Watching birds",
    sentence:
      "Bird watching is a relaxing hobby that connects you with nature.",
  },
  {
    id: 358,
    title: "Painting",
    bangla: "এঁকিং",
    synonymous: "Art",
    sentence: "Painting is a great way to express creativity and emotions.",
  },
  {
    id: 359,
    title: "Travelling",
    bangla: "ভ্রমণ",
    synonymous: "Tourism",
    sentence: "Travelling allows you to explore new places and cultures.",
  },
  {
    id: 360,
    title: "Exercising",
    bangla: "ব্যায়াম",
    synonymous: "Physical activity",
    sentence: "Exercising regularly is important for maintaining good health.",
  },
  {
    id: 361,
    title: "Art and Crafts",
    bangla: "শিল্প ও কারুশিল্প",
    synonymous: "Crafting",
    sentence: "Art and crafts activities can be therapeutic and fun.",
  },
  {
    id: 362,
    title: "Baking",
    bangla: "বেকিং",
    synonymous: "Cooking desserts",
    sentence:
      "Baking cookies is one of my favorite hobbies during the holidays.",
  },
  {
    id: 363,
    title: "Gardening",
    bangla: "বাগান করা",
    synonymous: "Horticulture",
    sentence:
      "Gardening is a rewarding hobby that lets you grow your own plants.",
  },
  {
    id: 364,
    title: "Video games",
    bangla: "ভিডিও গেমস",
    synonymous: "Gaming",
    sentence: "Video games provide a fun way to unwind after a long day.",
  },
  {
    id: 365,
    title: "Hiking",
    bangla: "হাইকিং",
    synonymous: "Trekking",
    sentence:
      "Hiking through the mountains is a great way to connect with nature.",
  },
  {
    id: 366,
    title: "Learning a musical instrument",
    bangla: "সঙ্গীত যন্ত্র শিখা",
    synonymous: "Music training",
    sentence:
      "Learning a musical instrument can enhance your cognitive abilities and creativity.",
  },
  {
    id: 367,
    title: "Earphones",
    bangla: "এয়ারফোনস",
    synonymous: "Headset",
    sentence: "I always use earphones while commuting to listen to music.",
  },
  {
    id: 368,
    title: "Loudspeaker",
    bangla: "লাউডস্পিকার",
    synonymous: "Speaker",
    sentence:
      "The loudspeaker was so powerful that it could be heard from a distance.",
  },
  {
    id: 369,
    title: "Cellphone",
    bangla: "সেলফোন",
    synonymous: "Handphone",
    sentence: "She always checks her cellphone for messages and updates.",
  },
  {
    id: 370,
    title: "Power bank",
    bangla: "পাওয়ার ব্যাংক",
    synonymous: "Portable charger",
    sentence:
      "I carry a power bank with me to keep my phone charged while traveling.",
  },
  {
    id: 371,
    title: "Adaptor",
    bangla: "অ্যাডাপ্টার",
    synonymous: "Travel adaptor",
    sentence:
      "You will need an adaptor to plug your devices into foreign sockets.",
  },
  {
    id: 372,
    title: "Multiplug",
    bangla: "মাল্টিপ্লাগ",
    synonymous: "Power Strip",
    sentence: "I use a multiplug to connect multiple devices at once.",
  },
  {
    id: 373,
    title: "Router",
    bangla: "রাউটার",
    synonymous: "Cellular hotspot",
    sentence:
      "The router is set up to provide Wi-Fi access throughout the house.",
  },
  {
    id: 374,
    title: "Desktop",
    bangla: "ডেস্কটপ",
    synonymous: "Personal Computer (PC)",
    sentence:
      "He prefers working on a desktop for its larger screen and better performance.",
  },
  {
    id: 375,
    title: "Smartwatch",
    bangla: "স্মার্টওয়াচ",
    synonymous: "Electronic watch",
    sentence:
      "The smartwatch tracks my fitness and notifications all day long.",
  },
  {
    id: 376,
    title: "Tablet",
    bangla: "ট্যাবলেট",
    synonymous: "Tab",
    sentence: "I use my tablet to read books and watch videos while traveling.",
  },
  {
    id: 377,
    title: "Chowmein",
    bangla: "চাওইমেন",
    synonymous: "Noodles",
    sentence:
      "Chowmein is a popular dish in many Asian countries, often served with vegetables and meat.",
  },
  {
    id: 378,
    title: "Scrambled eggs",
    bangla: "স্ক্র্যাম্বড এগস",
    synonymous: "Omelette",
    sentence:
      "Scrambled eggs are a quick and easy breakfast option, often served with toast.",
  },
  {
    id: 379,
    title: "Fried rice",
    bangla: "ফ্রাইড রাইস",
    synonymous: "Crispy rice",
    sentence:
      "Fried rice is a popular dish in many Asian countries, made with leftover rice and vegetables.",
  },
  {
    id: 380,
    title: "Beef curry",
    bangla: "বিফ কারি",
    synonymous: "Beef steak",
    sentence:
      "Beef curry is a rich and flavorful dish, often served with rice or bread.",
  },
  {
    id: 381,
    title: "Lentil",
    bangla: "লেন্টিল",
    synonymous: "Lentil soup",
    sentence:
      "Lentil soup is a nutritious and filling meal, commonly eaten with rice.",
  },
  {
    id: 382,
    title: "Fish fry",
    bangla: "ফিশ ফ্রাই",
    synonymous: "Fried fish",
    sentence:
      "Fish fry is a simple yet tasty dish, often served with a side of vegetables or rice.",
  },
  {
    id: 383,
    title: "Vegetable curry",
    bangla: "সবজি কারি",
    synonymous: "Mixed vegetable",
    sentence:
      "Vegetable curry is a healthy and flavorful dish, often made with a variety of seasonal vegetables.",
  },
  {
    id: 384,
    title: "Bread",
    bangla: "রুটি",
    synonymous: "White bread",
    sentence:
      "Bread is a staple food in many cultures, typically served with curries or soups.",
  },
  {
    id: 385,
    title: "French toast",
    bangla: "ফ্রেঞ্চ টোস্ট",
    synonymous: "Spanish toast",
    sentence:
      "French toast is a popular breakfast dish, made by dipping bread in an egg mixture and frying it.",
  },
  {
    id: 386,
    title: "Grilled chicken",
    bangla: "গ্রিলড চিকেন",
    synonymous: "Barbeque",
    sentence:
      "Grilled chicken is a tasty and healthy option, often served with a side of salad or vegetables.",
  },
  {
    id: 387,
    title: "Tweezers",
    bangla: "টুইজার্স",
    synonymous: "Pincer",
    sentence: "I used tweezers to remove the splinter from my finger.",
  },
  {
    id: 388,
    title: "Backpack",
    bangla: "ব্যাকপ্যাক",
    synonymous: "Shoulder bag",
    sentence: "I packed my clothes into the backpack for the trip.",
  },
  {
    id: 389,
    title: "Hair brush",
    bangla: "হেয়ার ব্রাশ",
    synonymous: "Comb",
    sentence: "She brushed her hair with a hair brush before the meeting.",
  },
  {
    id: 390,
    title: "Lip balm",
    bangla: "লিপ বাম",
    synonymous: "Lip moisturizer",
    sentence: "I apply lip balm every night to keep my lips soft.",
  },
  {
    id: 391,
    title: "Dental floss",
    bangla: "ডেন্টাল ফ্লস",
    synonymous: "Floss",
    sentence:
      "I always use dental floss to clean between my teeth after meals.",
  },
  {
    id: 392,
    title: "Bobby pins",
    bangla: "ববি পিনস",
    synonymous: "Hair clip",
    sentence: "She used bobby pins to secure her hair in place.",
  },
  {
    id: 393,
    title: "Nail clipper",
    bangla: "নেইল ক্লিপার",
    synonymous: "Nail cutter",
    sentence: "I need to use the nail clipper to trim my nails.",
  },
  {
    id: 394,
    title: "Wash cloth",
    bangla: "ওয়াশ ক্লথ",
    synonymous: "Small towel",
    sentence: "I wiped my face with a wash cloth after my shower.",
  },
  {
    id: 395,
    title: "Wet wipes",
    bangla: "ওয়েট ওয়াইপস",
    synonymous: "Wet towels",
    sentence: "I carry wet wipes in my bag to clean my hands when needed.",
  },
  {
    id: 396,
    title: "Mouthwash",
    bangla: "মাউথওয়াশ",
    synonymous: "Mouth rinse",
    sentence: "I use mouthwash every morning to freshen my breath.",
  },
  {
    id: 397,
    title: "Saree",
    bangla: "সারি",
    synonymous: "Traditional Bengali attire",
    sentence: "She wore a beautiful saree at the wedding.",
  },
  {
    id: 398,
    title: "Polo shirt",
    bangla: "পোলো শার্ট",
    synonymous: "Golf shirt",
    sentence: "He likes wearing polo shirts during the summer.",
  },
  {
    id: 399,
    title: "Vest",
    bangla: "ভেস্ট",
    synonymous: "Waistcoat",
    sentence: "He wore a vest under his suit jacket.",
  },
  {
    id: 400,
    title: "Hoody",
    bangla: "হুডি",
    synonymous: "Hooded sweatshirt",
    sentence: "I always wear a hoody when it's cold outside.",
  },
  {
    id: 401,
    title: "T-shirt",
    bangla: "টি-শার্ট",
    synonymous: "Button-down shirt",
    sentence: "I prefer wearing T-shirts on casual days.",
  },
  {
    id: 402,
    title: "Stockings",
    bangla: "স্টকিংস",
    synonymous: "Hosiery",
    sentence: "She wore stockings with her dress for the party.",
  },
  {
    id: 403,
    title: "Leggings",
    bangla: "লেগিংস",
    synonymous: "Tights",
    sentence: "She prefers wearing leggings for yoga classes.",
  },
  {
    id: 404,
    title: "Baggy pants",
    bangla: "ব্যাগি প্যান্টস",
    synonymous: "Wide pants",
    sentence: "He likes to wear baggy pants for a relaxed look.",
  },
  {
    id: 405,
    title: "Gown",
    bangla: "গাউন",
    synonymous: "Long frock",
    sentence: "She looked stunning in her evening gown.",
  },
];
export default vocabData;
