// data.js
const data = [
    // {
    //   "userId": 1,
    //   "id": 1,
    //   "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    //   "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
    // },
    
      { "id": 1, "title": "Monday", "bangla": "সোমবার" },
      { "id": 2, "title": "Tuesday", "bangla": "মঙ্গলবার" },
      { "id": 3, "title": "Wednesday", "bangla": "বুধবার" },
      { "id": 4, "title": "Thursday", "bangla": "বৃহস্পতিবার" },
      { "id": 5, "title": "Friday", "bangla": "শুক্রবার" },
      { "id": 6, "title": "Saturday", "bangla": "শনিবার" },
      { "id": 7, "title": "Sunday", "bangla": "রবিবার" },
      { "id": 8, "title": "Weekdays", "bangla": "সপ্তাহের দিন" },
      { "id": 9, "title": "Weekend", "bangla": "সপ্তাহান্ত" },
      { "id": 10, "title": "January", "bangla": "জানুয়ারি" },
      { "id": 11, "title": "February", "bangla": "ফেব্রুয়ারি" },
      { "id": 12, "title": "March", "bangla": "মার্চ" },
      { "id": 13, "title": "April", "bangla": "এপ্রিল" },
      { "id": 14, "title": "May", "bangla": "মে" },
      { "id": 15, "title": "June", "bangla": "জুন" },
      { "id": 16, "title": "July", "bangla": "জুলাই" },
      { "id": 17, "title": "August", "bangla": "আগস্ট" },
      { "id": 18, "title": "September", "bangla": "সেপ্টেম্বর" },
      { "id": 19, "title": "October", "bangla": "অক্টোবর" },
      { "id": 20, "title": "November", "bangla": "নভেম্বর" },
      { "id": 21, "title": "December", "bangla": "ডিসেম্বর" },
      { "id": 22, "title": "Gardening", "bangla": "বাগান করা" },
      { "id": 23, "title": "Stamp Collection", "bangla": "টিকেট সংগ্রহ" },
      { "id": 24, "title": "Orienteering", "bangla": "অরিয়েন্টিয়ারিং" },
      { "id": 25, "title": "Caving", "bangla": "গুহায় প্রবেশ" },
      { "id": 26, "title": "Spelunking", "bangla": "গুহা অনুসন্ধান" },
      { "id": 27, "title": "Scuba Diving", "bangla": "স্কুবা ডাইভিং" },
      { "id": 28, "title": "Snorkelling", "bangla": "স্নরকেলিং" },
      { "id": 29, "title": "Skateboarding", "bangla": "স্কেটবোর্ডিং" },
      { "id": 30, "title": "Bowls", "bangla": "বল" },
      { "id": 31, "title": "Archery", "bangla": "ধনুকবিদ্যা" },
      { "id": 32, "title": "Ice Skating", "bangla": "আইস স্কেটিং" },
      { "id": 33, "title": "Dart", "bangla": "ডার্ট" },
      { "id": 34, "title": "Golf", "bangla": "গলফ" },
      { "id": 35, "title": "Billiards", "bangla": "বিলিয়ার্ডস" },
      { "id": 36, "title": "Photography", "bangla": "ফটোগ্রাফি" },
      { "id": 37, "title": "Painting", "bangla": "চিত্রকলা" },
      { "id": 38, "title": "Embroidery", "bangla": "কাঠ বুনন" },
      { "id": 39, "title": "Climbing", "bangla": "পর্বতারোহণ" },
      { "id": 40, "title": "Chess", "bangla": "চেস" },
      { "id": 41, "title": "Parachute", "bangla": "প্যারাশুট" },
      { "id": 42, "title": "Pottery", "bangla": "মাটির তৈজসপত্র" },
      { "id": 43, "title": "Woodcarving", "bangla": "কাঠ খোদাই" },
      { "id": 44, "title": "Science", "bangla": "বিজ্ঞান" },
      { "id": 45, "title": "Politics", "bangla": "রাজনীতি" },
      { "id": 46, "title": "Architecture", "bangla": "স্থাপত্য" },
      { "id": 47, "title": "Law", "bangla": "আইন" },
      { "id": 48, "title": "Geography", "bangla": "ভূগোল" },
      { "id": 49, "title": "History", "bangla": "ইতিহাস" },
      { "id": 50, "title": "Biology", "bangla": "জীববিজ্ঞান" },
      { "id": 51, "title": "Archaeology", "bangla": "আর্কিওলজি" },
      { "id": 52, "title": "Literature", "bangla": "সাহিত্য" },
      { "id": 53, "title": "Statistics", "bangla": "গণিত শাস্ত্র" },
      { "id": 54, "title": "Mathematics", "bangla": "গণিত" },
      { "id": 55, "title": "Performing Arts", "bangla": "প্রদর্শনী শিল্পকলা" },
      { "id": 56, "title": "Visual Arts", "bangla": "দৃশ্য শিল্পকলা" },
      { "id": 57, "title": "Logic", "bangla": "যুক্তি" },
      { "id": 58, "title": "Physics", "bangla": "ভৌত বিজ্ঞান" },
      { "id": 59, "title": "Psychology", "bangla": "মানসিক বিজ্ঞান" },
      { "id": 60, "title": "Anthropology", "bangla": "মানববিদ্যা" },
      { "id": 61, "title": "Economics", "bangla": "অর্থনীতি" },
      { "id": 62, "title": "Philosophy", "bangla": "দর্শনশাস্ত্র" },
      { "id": 63, "title": "Chemistry", "bangla": "রসায়ন" },
      { "id": 64, "title": "Humanities", "bangla": "মানবিক বিজ্ঞান" },
      { "id": 65, "title": "Business Management", "bangla": "ব্যবসা ব্যবস্থাপনা" },
      { "id": 66, "title": "Agriculture", "bangla": "কৃষি"
      },
      { "id": 67, "title": "Printer", "bangla": "প্রিন্টার" },
  { "id": 68, "title": "Assessment", "bangla": "মূল্যায়ন" },
  { "id": 69, "title": "Library", "bangla": "লাইব্রেরি" },
  { "id": 70, "title": "Department", "bangla": "বিভাগ" },
  { "id": 71, "title": "Computer Centre", "bangla": "কম্পিউটার সেন্টার" },
  { "id": 72, "title": "Classroom", "bangla": "ক্লাসরুম" },
  { "id": 73, "title": "Attendance", "bangla": "উপস্থিতি" },
  { "id": 74, "title": "Deadline", "bangla": "সময়সীমা" },
  { "id": 75, "title": "Give A Talk", "bangla": "একটি আলোচনা দিন" },
  { "id": 76, "title": "Speech", "bangla": "ভাষণ" },
  { "id": 77, "title": "Lecture", "bangla": "বক্তৃতা" },
  { "id": 78, "title": "Tutor", "bangla": "টিউটর" },
  { "id": 79, "title": "Main Hall", "bangla": "প্রধান হল" },
  { "id": 80, "title": "Computer Laboratory", "bangla": "কম্পিউটার ল্যাবরেটরি" },
  { "id": 81, "title": "Certificate", "bangla": "সার্টিফিকেট" },
  { "id": 82, "title": "Diploma", "bangla": "ডিপ্লোমা" },
  { "id": 83, "title": "Placement Test", "bangla": "প্লেসমেন্ট টেস্ট" },
  { "id": 84, "title": "Facilities", "bangla": "সুবিধা" },
  { "id": 85, "title": "College", "bangla": "কলেজ" },
  { "id": 86, "title": "Dining Room", "bangla": "ডাইনিং রুম" },
  { "id": 87, "title": "Specialist", "bangla": "বিশেষজ্ঞ" },
  { "id": 88, "title": "Knowledge", "bangla": "জ্ঞান" },
  { "id": 89, "title": "International", "bangla": "আন্তর্জাতিক" },
  { "id": 90, "title": "Accommodation", "bangla": "আবাসন" },
  { "id": 91, "title": "Overseas Students", "bangla": "অবশ্যই ছাত্র" },
  { "id": 92, "title": "Full-Time", "bangla": "পূর্ণ সময়" },
  { "id": 93, "title": "Homestay", "bangla": "হোমস্টে" },
  { "id": 94, "title": "Primary", "bangla": "প্রাথমিক" },
  { "id": 95, "title": "Secondary", "bangla": "মাধ্যমিক" },
  { "id": 96, "title": "Intermediate", "bangla": "মাঝারি" },
  { "id": 97, "title": "Media Room", "bangla": "মিডিয়া রুম" },
  { "id": 98, "title": "Commencement", "bangla": "আরম্ভ" },
  { "id": 99, "title": "Dissertation", "bangla": "থিসিস" },
  { "id": 100, "title": "Leaflet", "bangla": "পতাকা" },
  { "id": 101, "title": "School Reunion", "bangla": "স্কুল পুনর্মিলনী" },
  { "id": 102, "title": "Feedback", "bangla": "প্রতিক্রিয়া" },
  { "id": 103, "title": "Tasks", "bangla": "কাজ" },
  { "id": 104, "title": "Outcomes", "bangla": "ফলাফল" },
  { "id": 105, "title": "Advanced", "bangla": "অগ্রসর" },
  { "id": 106, "title": "Introductory", "bangla": "ভূমিকা" },
  { "id": 107, "title": "Extra Background", "bangla": "অতিরিক্ত ব্যাকগ্রাউন্ড" },
  { "id": 108, "title": "Resources Room", "bangla": "সম্পদ কক্ষ" },
  { "id": 109, "title": "Staff", "bangla": "স্টাফ" },
  { "id": 110, "title": "Higher Education", "bangla": "উচ্চ শিক্ষা" },
  { "id": 111, "title": "Guidelines", "bangla": "নির্দেশিকা" },
  { "id": 112, "title": "Post-Secondary", "bangla": "মাধ্যমিক পরবর্তী" },
  { "id": 113, "title": "Faculty", "bangla": "ফ্যাকাল্টি" },
  { "id": 114, "title": "Pupils", "bangla": "শিক্ষার্থী" },
  { "id": 115, "title": "Pencil", "bangla": "পেন্সিল" },
  { "id": 116, "title": "Supervisor", "bangla": "পর্যবেক্ষক" },
  { "id": 117, "title": "Bachelor’s Degree", "bangla": "ব্যাচেলর ডিগ্রী" },
  { "id": 118, "title": "Compound", "bangla": "সংকর" },
  { "id": 119, "title": "Foreign Students", "bangla": "বিদেশী ছাত্র" },
  { "id": 120, "title": "Schedule", "bangla": "সময়সূচী" },
  { "id": 121, "title": "Vocabulary", "bangla": "শব্দভান্ডার" },
  { "id": 122, "title": "Student Support Services", "bangla": "ছাত্র সহায়ক সেবা" },
  { "id": 123, "title": "Student Retention", "bangla": "ছাত্র ধারন" },
  { "id": 124, "title": "Publication", "bangla": "প্রকাশনা" },
  { "id": 125, "title": "Registrar’s Office", "bangla": "রেজিস্ট্রারের অফিস" },
  { "id": 126, "title": "Stationery", "bangla": "কাগজপত্র" },
  { "id": 127, "title": "Designer", "bangla": "ডিজাইনার" },
  { "id": 128, "title": "Occupation", "bangla": "পেশা" },
  { "id": 129, "title": "Profession", "bangla": "পেশাগত" },
  { "id": 130, "title": "Decorator", "bangla": "সাজসজ্জাকারী" },
  { "id": 131, "title": "Architect", "bangla": "স্থপতি" },
  { "id": 132, "title": "Engineer", "bangla": "এঞ্জিনিয়ার" },
  { "id": 133, "title": "Waiter", "bangla": "ওয়েটার" },
  { "id": 134, "title": "Teacher", "bangla": "শিক্ষক" },
  { "id": 135, "title": "Vacancy", "bangla": "খালি পদ" },
  { "id": 136, "title": "Professor", "bangla": "প্রফেসর" },
  { "id": 137, "title": "Specialist", "bangla": "বিশেষজ্ঞ" },
  { "id": 138, "title": "Manager", "bangla": "ম্যানেজার" },
  { "id": 139, "title": "Waitress", "bangla": "ওয়েট্রেস" },
  { "id": 140, "title": "Psychologist", "bangla": "মনোবিজ্ঞানী" },
  { "id": 141, "title": "Volunteer", "bangla": "স্বেচ্ছাসেবক" },
  { "id": 142, "title": "Craftsman", "bangla": "শিল্পী" },
  { "id": 143, "title": "Work Experience", "bangla": "কর্ম অভিজ্ঞতা" },
  { "id": 144, "title": "Curriculum Vitae", "bangla": "সিভি" },
  { "id": 145, "title": "Freelance", "bangla": "ফ্রিল্যান্স" },
  { "id": 146, "title": "Secretary", "bangla": "সেক্রেটারি" },
  { "id": 147, "title": "Mail Address", "bangla": "মেইল ঠিকানা" },
  { "id": 148, "title": "Receptionist", "bangla": "রিসেপশনিস্ট" },
  { "id": 149, "title": "Pilot", "bangla": "পাইলট" },
  { "id": 150, "title": "Lecturer", "bangla": "প্রভাষক" },
  { "id": 151, "title": "Office Assistant", "bangla": "অফিস সহকারী" },
  { "id": 152, "title": "Clerk", "bangla": "ক্লার্ক" },
  { "id": 153, "title": "Accountant", "bangla": "অ্যাকাউন্ট্যান্ট" },
  { "id": 154, "title": "Guard", "bangla": "প্রহরী" },
  { "id": 155, "title": "Flight Attendant", "bangla": "ফ্লাইট অ্যাটেনডেন্ট" },
  { "id": 156, "title": "Cashier", "bangla": "ক্যাশিয়ার" },
  { "id": 157, "title": "Captain", "bangla": "ক্যাপ্টেন" },
  { "id": 158, "title": "Yoga", "bangla": "যোগ" },
  { "id": 159, "title": "Tai-Chi", "bangla": "তাই-চি" },
  { "id": 160, "title": "Keep-Fit", "bangla": "ফিট থাকা" },
  { "id": 161, "title": "Salad Bar", "bangla": "সালাদ বার" },
  { "id": 162, "title": "Vegetarian", "bangla": "সবজি খাদ্যাভ্যাসী" },
  { "id": 163, "title": "Outdoor Activities", "bangla": "আউটডোর কার্যক্রম" },
  { "id": 164, "title": "Leisure Time", "bangla": "অবসর সময়" },
  { "id": 165, "title": "Disease", "bangla": "রোগ" },
  { "id": 166, "title": "Meal", "bangla": "খাবার" },
  { "id": 167, "title": "Protein", "bangla": "প্রোটিন" },
  { "id": 168, "title": "Balanced Diet", "bangla": "সুষম খাদ্য" },
  { "id": 169, "title": "Food Pyramid", "bangla": "খাদ্য পিরামিড" },
  { "id": 170, "title": "Vitamin", "bangla": "ভিটামিন" },
  { "id": 171, "title": "Carbohydrates", "bangla": "কার্বোহাইড্রেট" },
  { "id": 172, "title": "Rice", "bangla": "চাল" },
  { "id": 173, "title": "Pasta", "bangla": "পাস্তা" },
  { "id": 174, "title": "Potatoes", "bangla": "আলু" },
  { "id": 175, "title": "Pizza", "bangla": "পিজা" },
  { "id": 176, "title": "Tomatoes", "bangla": "টমেটো" },
  { "id": 177, "title": "Bread", "bangla": "রুটি" },
  { "id": 178, "title": "Cereals", "bangla": "শস্য" },
  { "id": 179, "title": "Minerals", "bangla": "খনিজ" },
  { "id": 180, "title": "Zinc", "bangla": "জিঙ্ক" },
  { "id": 181, "title": "Meat", "bangla": "মাংস" },
  { "id": 182, "title": "Seafood", "bangla": "সীফুড" },
  { "id": 183, "title": "Eggs", "bangla": "ডিম" },
  { "id": 184, "title": "Beans", "bangla": "শিম" },
  { "id": 185, "title": "Milk", "bangla": "দুধ" },
  { "id": 186, "title": "Cheese", "bangla": "পনির" },
  { "id": 187, "title": "Yoghurt", "bangla": "দই" },
  { "id": 188, "title": "Fruit", "bangla": "ফল" },
  { "id": 189, "title": "Vegetables", "bangla": "সবজি" },
  { "id": 190, "title": "Citrus Fruits", "bangla": "সাইট্রাস ফল" },
  { "id": 191, "title": "Green Pepper", "bangla": "সবুজ মরিচ" },
  { "id": 192, "title": "Blackcurrant", "bangla": "ব্ল্যাককারেন্ট" },
  { "id": 193, "title": "Nuts", "bangla": "বাদাম" },
  { "id": 194, "title": "Egg Yolk", "bangla": "ডিমের কুসুম" },
  { "id": 195, "title": "Liver", "bangla": "যকৃৎ" },
  { "id": 196, "title": "Medicine", "bangla": "ঔষধ" },
  { "id": 197, "title": "Treatment", "bangla": "চিকিৎসা" },
  { "id": 198, "title": "Remedy", "bangla": "প্রতিকার" },
  { "id": 199, "title": "Nursing Care", "bangla": "নার্সিং যত্ন" },
  { "id": 200, "title": "Nursery", "bangla": "নার্সারি" },
  { "id": 201, "title": "Regular Exercise", "bangla": "নিয়মিত ব্যায়াম" },
  { "id": 202, "title": "Field", "bangla": "মাঠ" },
  { "id": 203, "title": "Footbridge", "bangla": "পায়ে চলার সেতু" },
  { "id": 204, "title": "River", "bangla": "নদী" },
  { "id": 205, "title": "Mountain", "bangla": "পর্বত" },
  { "id": 206, "title": "Forest", "bangla": "বন" },
  { "id": 207, "title": "Village", "bangla": "গ্রাম" },
  { "id": 208, "title": "Environment", "bangla": "পরিবেশ" },
  { "id": 209, "title": "Waterfall", "bangla": "ঝর্ণা" },
  { "id": 210, "title": "Coast", "bangla": "তট" },
  { "id": 211, "title": "Reef", "bangla": "প্রাচীর" },
  { "id": 212, "title": "Lake", "bangla": "হ্রদ" },
  { "id": 213, "title": "Valley", "bangla": "উঁচু অঞ্চল" },
  { "id": 214, "title": "Peninsula", "bangla": "অধিকার" },
  { "id": 215, "title": "Earthquake", "bangla": "ভূমিকম্প" },
  { "id": 216, "title": "Avalanche", "bangla": "তুষারপাত" },
  { "id": 217, "title": "Typhoon", "bangla": "ধ্বংসাত্মক ঘূর্ণিঝড়" },
  { "id": 218, "title": "Hill", "bangla": "টিলা" },
  { "id": 219, "title": "Cliff", "bangla": "চূড়া" },
  { "id": 220, "title": "Island", "bangla": "দ্বীপ" },
  { "id": 221, "title": "Desertification", "bangla": "মরুকরণের" },
  { "id": 222, "title": "Volcano", "bangla": "অগ্ন্যুৎপাত" },
  { "id": 223, "title": "Disaster", "bangla": "দুর্যোগ" },
  { "id": 224, "title": "Landslides", "bangla": "ভূস্মতি" },
  { "id": 225, "title": "Storm", "bangla": "ঝড়" },
  { "id": 226, "title": "Flood", "bangla": "বন্যা" },
  { "id": 227, "title": "Hurricane", "bangla": "ঘূর্ণিঝড়" },
  { "id": 228, "title": "Pond", "bangla": "পুকুর" },
  { "id": 229, "title": "Catastrophe", "bangla": "বিপর্যয়" },
  { "id": 230, "title": "Erosion", "bangla": "ক্ষয়" },
  { "id": 231, "title": "Jungle", "bangla": "জঙ্গল" },
  { "id": 232, "title": "Oasis", "bangla": "উপদ্বীপ" },
  { "id": 233, "title": "Dam", "bangla": "বাঁধ" },
  { "id": 234, "title": "Canyon", "bangla": "গিরিখাত" },
  { "id": 235, "title": "Coal", "bangla": "কয়লা" },
  { "id": 236, "title": "Fossil Fuels", "bangla": "জৈব জ্বালানি" },
  { "id": 237, "title": "Acid Rain", "bangla": "অম্ল বৃষ্টি" },
  { "id": 238, "title": "Global Warming", "bangla": "গ্লোবাল ওয়ার্মিং" },
  { "id": 239, "title": "Carbon Dioxide", "bangla": "কার্বন ডাইঅক্সাইড" },
  { "id": 240, "title": "Greenhouse Effect", "bangla": "গ্রীনহাউস প্রভাব" },
  { "id": 241, "title": "Burning Fossil", "bangla": "জৈব জ্বালানি পোড়ানো" },
  { "id": 242, "title": "Exhaust Fumes", "bangla": "নিষ্কাশিত ধোঁয়া" },
  { "id": 243, "title": "Smog", "bangla": "ধোঁয়া" },
  { "id": 244, "title": "Climate", "bangla": "আবহাওয়া" },
  { "id": 245, "title": "Pollution", "bangla": "দূষণ" },
  { "id": 246, "title": "Temperature", "bangla": "তাপমাত্রা" },
  { "id": 247, "title": "Power Plants", "bangla": "শক্তি উৎপাদন কেন্দ্র" },
  { "id": 248, "title": "Deforestation", "bangla": "বনধ্বংস" },
  { "id": 249, "title": "Nitrogen Oxide", "bangla": "নাইট্রোজেন অক্সাইড" },
  { "id": 250, "title": "Landfill", "bangla": "মাটির স্তর" },
  { "id": 251, "title": "Cattle", "bangla": "গবাদি পশু" },
  { "id": 252, "title": "Wind Turbine", "bangla": "বাতাস টারবাইন" },
  { "id": 253, "title": "Renewable", "bangla": "পুনঃনবীকরণযোগ্য" },
  { "id": 254, "title": "Source Of Energy", "bangla": "শক্তির উৎস" },
  { "id": 255, "title": "Reliable", "bangla": "বিশ্বাসযোগ্য" },
  { "id": 256, "title": "Solar Panels", "bangla": "সৌর প্যানেল" },
  { "id": 257, "title": "Solar Power", "bangla": "সৌর শক্তি" },
  { "id": 258, "title": "Hydroelectric Power", "bangla": "জলবিদ্যুৎ" },
  { "id": 259, "title": "Environmentally Friendly", "bangla": "পরিবেশবান্ধব" },
  { "id": 260, "title": "Oxygen", "bangla": "অক্সিজেন" },
  { "id": 261, "title": "Chemical-Free", "bangla": "রসায়ন মুক্ত" },
  { "id": 262, "title": "Vegetation", "bangla": " উদ্ভিদ" },
  { "id": 263, "title": "Sea Level", "bangla": "সমুদ্র স্তর" },
  { "id": 264, "title": "Ocean Currents", "bangla": "সাগর প্রবাহ" },
  { "id": 265, "title": "Soil Conditioner", "bangla": "মাটি শোধক" },
  { "id": 266, "title": "Firewood", "bangla": "কাঠ" },
  { "id": 267, "title": "Desert", "bangla": "মরুভূমি" },
  { "id": 268, "title": "Degradation", "bangla": "অবনতি" },
  { "id": 269, "title": "Drought", "bangla": "খরা" },
  { "id": 270, "title": "Contaminated", "bangla": "দূষিত" },
  { "id": 271, "title": "Catalogue", "bangla": "ক্যাটালগ" },
  { "id": 272, "title": "Interview", "bangla": "সাক্ষাৎকার" },
  { "id": 273, "title": "Research Method", "bangla": "গবেষণা পদ্ধতি" },
  { "id": 274, "title": "Entertainment Industry", "bangla": "বিনোদন শিল্প" },
  { "id": 275, "title": "Tv Program", "bangla": "টিভি প্রোগ্রাম" },
  { "id": 276, "title": "Strategies", "bangla": "কৌশল" },
  { "id": 277, "title": "Leadership", "bangla": "নেতৃত্ব" },
  { "id": 278, "title": "Management", "bangla": "ব্যবস্থাপনা" },
  { "id": 279, "title": "Customer", "bangla": "গ্রাহক" },
  { "id": 280, "title": "Special Offer", "bangla": "বিশেষ অফার" },
  { "id": 281, "title": "Collecting Data", "bangla": "ডেটা সংগ্রহ" },
  { "id": 282, "title": "Display", "bangla": "প্রদর্শন" },
  { "id": 283, "title": "Products", "bangla": "পণ্য" },
  { "id": 284, "title": "Questionnaire", "bangla": "প্রশ্নাবলী" },
  { "id": 285, "title": "Survey", "bangla": "সমীক্ষা" },
  { "id": 286, "title": "Mass Media", "bangla": "মাধ্যম" },
  { "id": 287, "title": "Poll", "bangla": "ভোট" },
  { "id": 288, "title": "Business Card", "bangla": "ব্যবসায়িক কার্ড" },
  { "id": 289, "title": "Training", "bangla": "প্রশিক্ষণ" },
  { "id": 290, "title": "Trainee", "bangla": "প্রশিক্ষণার্থী" },
  { "id": 291, "title": "Statistic", "bangla": "পরিসংখ্যান" },
  { "id": 292, "title": "Profit Margin", "bangla": "মুনাফা মার্জিন" },
  { "id": 293, "title": "Newsletter", "bangla": "নিউজলেটার" },
  { "id": 294, "title": "Competition", "bangla": "প্রতিযোগিতা" },
  { "id": 295, "title": "Merchandise", "bangla": "বিপণন" },
  { "id": 296, "title": "Manufacture", "bangla": "উত্পাদন" },
  { "id": 297, "title": "Recruitment", "bangla": "নিয়োগ" },
  { "id": 298, "title": "Dome", "bangla": "গম্বুজ" },
  { "id": 299, "title": "Palace", "bangla": "রাজপ্রাসাদ" },
  { "id": 300, "title": "Fort", "bangla": "দুর্গ" },
  { "id": 301, "title": "Castle", "bangla": "দুর্গ" },
  { "id": 302, "title": "Glasshouse", "bangla": "গ্লাসহাউস" },
  { "id": 303, "title": "Pyramid", "bangla": "পিরামিড" },
  { "id": 304, "title": "Log Cabin", "bangla": "লগ ক্যাবিন" },
  { "id": 305, "title": "Lighthouse", "bangla": "প্রকল্প বাতি" },
  { "id": 306, "title": "Hut", "bangla": "ঝুপড়ি" },
  { "id": 307, "title": "Skyscraper", "bangla": "আকাশচুম্বী" },
  { "id": 308, "title": "Sculpture", "bangla": "ভাস্কর্য" },
  { "id": 309, "title": "Chimney", "bangla": "চিমনি" },
  { "id": 310, "title": "Bedroom", "bangla": "শয়নকক্ষ" },
  { "id": 311, "title": "Semi-Detached House", "bangla": "অর্ধ-বিচ্ছিন্ন বাড়ি" },
  { "id": 312, "title": "Duplex", "bangla": "ডুপ্লেক্স" },
  { "id": 313, "title": "Townhouse", "bangla": "টাউনহাউস" },
  { "id": 314, "title": "Row House", "bangla": "সারি বাড়ি" },
  { "id": 315, "title": "Bungalow", "bangla": "বঙ্গালো" },
  { "id": 316, "title": "Thatched Cottage", "bangla": "খড়ের কুটির" },
  { "id": 317, "title": "Mobile Home", "bangla": "মোবাইল হোম" },
  { "id": 318, "title": "Houseboat", "bangla": "বাড়ি-বোট" },
  { "id": 319, "title": "A Block Of Flats", "bangla": "এ ব্লক ফ্ল্যাট" },
  { "id": 320, "title": "Apartment Building", "bangla": "এপার্টমেন্ট বিল্ডিং" },
  { "id": 321, "title": "Condominium", "bangla": "কন্ডোমিনিয়াম" },
  { "id": 322, "title": "Basement", "bangla": "বেসমেন্ট" },
  { "id": 323, "title": "Landlord", "bangla": "জমিদার" },
  { "id": 324, "title": "Terraced House", "bangla": "টারাস বাড়ি" },
  { "id": 325, "title": "Tenant", "bangla": "ভাড়াটিয়া" },
  { "id": 326, "title": "Rent", "bangla": "ভাড়া" },
  { "id": 327, "title": "Lease", "bangla": "চুক্তি" },
  { "id": 328, "title": "Neighbourhood", "bangla": "পাড়া" },
  { "id": 329, "title": "Suburb", "bangla": "উপশহর" },
  { "id": 330, "title": "Dormitory", "bangla": "হোস্টেল" },
  { "id": 331, "title": "Story", "bangla": "কাহিনী" },
  { "id": 332, "title": "Kitchen", "bangla": "রান্নাঘর" },
  { "id": 333, "title": "Refrigerator", "bangla": "ফ্রিজ" },
  { "id": 334, "title": "Microwave", "bangla": "মাইক্রোওয়েভ" },
  { "id": 335, "title": "Sofa", "bangla": "সোফা" },
  { "id": 336, "title": "Coffee Table", "bangla": "কফি টেবিল" },
  { "id": 337, "title": "Ground Floor", "bangla": "মাটির তলা" },
  { "id": 338, "title": "Oven", "bangla": "ওভেন" },
  { "id": 339, "title": "Hallway", "bangla": "হলওয়ে" },
  { "id": 340, "title": "Insurance", "bangla": "বীমা" },
  { "id": 341, "title": "Central Station", "bangla": "কেন্দ্রীয় স্টেশন" },
  { "id": 342, "title": "Cities", "bangla": "শহর" },
  { "id": 343, "title": "Street", "bangla": "রাস্তা" },
  { "id": 344, "title": "Lane", "bangla": "লেন" },
  { "id": 345, "title": "City Centre", "bangla": "শহর কেন্দ্র" },
  { "id": 346, "title": "Car Park", "bangla": "গাড়ি পার্ক" },
  { "id": 347, "title": "Department Store", "bangla": "বিভাগীয় দোকান" },
  { "id": 348, "title": "Bridge", "bangla": "সেতু" },
  { "id": 349, "title": "Temple", "bangla": "মন্দির" },
  { "id": 350, "title": "Hospital", "bangla": "হাসপাতাল" },
  { "id": 351, "title": "Garden", "bangla": "বাগান" },
  { "id": 352, "title": "Avenue", "bangla": "অ্যাভিনিউ" },
  { "id": 353, "title": "Embassy", "bangla": "দূতাবাস" },
  { "id": 354, "title": "Road System", "bangla": "রাস্তা ব্যবস্থা" },
  { "id": 355, "title": "Boat", "bangla": "নৌকা" },
  { "id": 356, "title": "Lifeboat", "bangla": "লাইফবোট" },
  { "id": 357, "title": "Cargo Plane", "bangla": "কার্গো প্লেন" },
  { "id": 358, "title": "Shipment", "bangla": "শিপমেন্ট" },
  { "id": 359, "title": "Container Ship", "bangla": "কন্টেইনার শিপ" },
  { "id": 360, "title": "Ferry", "bangla": "ফেরি" },
  { "id": 361, "title": "Liner", "bangla": "লাইনার" },
  { "id": 362, "title": "Canal Boat", "bangla": "ক্যানাল বোট" },
  { "id": 363, "title": "Narrowboat", "bangla": "ন্যারোবোট" },
  { "id": 364, "title": "Dinghy Sailing", "bangla": "ডিঙ্গি সেলিং" },
  { "id": 365, "title": "Hovercraft", "bangla": "হোভারক্রাফট" },
  { "id": 366, "title": "Hydrofoil", "bangla": "হাইড্রোফয়েল" },
  { "id": 367, "title": "Sailboat", "bangla": "সেইলবোত" },
  { "id": 368, "title": "Paddle Steamer", "bangla": "প্যাডল স্টিমার" },
  { "id": 369, "title": "Cabin Cruiser", "bangla": "কেবিন ক্রুজার" },
  { "id": 370, "title": "Kayak", "bangla": "কায়াক" },
  { "id": 371, "title": "Canoe", "bangla": "কানু" },
  { "id": 372, "title": "Punt", "bangla": "পান্ট" },
  { "id": 373, "title": "Gondola", "bangla": "গন্ডোলা" },
  { "id": 374, "title": "Aircraft", "bangla": "বিমান" },
  { "id": 375, "title": "Rowing Boat", "bangla": "রোইং বোট" },
  { "id": 376, "title": "Rowboat", "bangla": "রোবোট" },
  { "id": 377, "title": "Helicopter", "bangla": "হেলিকপ্টার" },
  { "id": 378, "title": "Seaplane", "bangla": "সীপ্লেন" },
  { "id": 379, "title": "Airship", "bangla": "এয়ারশিপ" },
  { "id": 380, "title": "Hot-Air Balloon", "bangla": "হট-এয়ার বেলুন" },
  { "id": 381, "title": "Airport", "bangla": "বিমানবন্দর" },
  { "id": 382, "title": "Platform", "bangla": "প্ল্যাটফর্ম" },
  { "id": 383, "title": "Hire A Car", "bangla": "গাড়ি ভাড়া করা" },
  { "id": 384, "title": "Automobile", "bangla": "অটোমোবাইল" },
  { "id": 385, "title": "Crew", "bangla": "ক্রীউ" },
  { "id": 386, "title": "Passenger", "bangla": "যাত্রী" },
  { "id": 387, "title": "Staff Selection", "bangla": "স্টাফ সিলেকশন" },
  { "id": 388, "title": "Clinic", "bangla": "ক্লিনিক" },
  { "id": 389, "title": "Dentist", "bangla": "দাঁতের ডাক্তার" },
  { "id": 390, "title": "Reception", "bangla": "রিসেপশন" },
  { "id": 391, "title": "Appointment", "bangla": "অ্যাপয়েন্টমেন্ট" },
  { "id": 392, "title": "Colleague", "bangla": "সহকর্মী" },
  { "id": 393, "title": "Workshop", "bangla": "ওয়ার্কশপ" },
  { "id": 394, "title": "Employer", "bangla": "নিয়োগকারী" },
  { "id": 395, "title": "Employment", "bangla": "কর্মসংস্থান" },
  { "id": 396, "title": "Unemployed", "bangla": "বেকার" },
  { "id": 397, "title": "Technical Cooperation", "bangla": "প্রযুক্তিগত সহযোগিতা" },
  { "id": 398, "title": "Team Leaders", "bangla": "টিম নেতা" },
  { "id": 399, "title": "Showroom", "bangla": "শোরুম" },
  { "id": 400, "title": "Information Desk", "bangla": "তথ্য ডেস্ক" },
  { "id": 401, "title": "Stress", "bangla": "মানসিক চাপ" },
  { "id": 402, "title": "Ability", "bangla": "ক্ষমতা" },
  { "id": 403, "title": "Vision", "bangla": "দৃষ্টি" },
  { "id": 404, "title": "Employee", "bangla": "কর্মচারী" },
  { "id": 405, "title": "Internship", "bangla": "ইন্টার্নশিপ" },
  { "id": 406, "title": "Confidence", "bangla": "আত্মবিশ্বাস" },
  { "id": 407, "title": "Parliament", "bangla": "পার্লামেন্ট" },
  { "id": 408, "title": "Accommodation", "bangla": "আবাসন" },
  { "id": 409, "title": "Local Library", "bangla": "স্থানীয় লাইব্রেরি" },
  { "id": 410, "title": "Swimming Pool", "bangla": "সুইমিং পুল" },
  { "id": 411, "title": "Cafeteria", "bangla": "ক্যাফেটেরিয়া" },
  { "id": 412, "title": "Cottage", "bangla": "কটেজ" },
  { "id": 413, "title": "Restaurant", "bangla": "রেস্টুরেন্ট" },
  { "id": 414, "title": "Bookshop", "bangla": "বইয়ের দোকান" },
  { "id": 415, "title": "Sports Centre", "bangla": "ক্রীড়া কেন্দ্র" },
  { "id": 416, "title": "City Council", "bangla": "শহর পরিষদ" },
  { "id": 417, "title": "Canteen", "bangla": "ক্যানটিন" },
  { "id": 418, "title": "Cafe", "bangla": "ক্যাফে" },
  { "id": 419, "title": "Dance Studio", "bangla": "নৃত্য স্টুডিও" },
  { "id": 420, "title": "Park", "bangla": "পার্ক" },
  { "id": 421, "title": "Conversation Club", "bangla": "আলোচনা ক্লাব" },
  { "id": 422, "title": "Kindergarten", "bangla": "প্রাক-প্রাথমিক বিদ্যালয়" },
  { "id": 423, "title": "Cash", "bangla": "নগদ" },
  { "id": 424, "title": "Debit", "bangla": "ডেবিট" },
  { "id": 425, "title": "Low-Risk Investment", "bangla": "নিম্ন-ঝুঁকি বিনিয়োগ" },
  { "id": 426, "title": "Credit Card", "bangla": "ক্রেডিট কার্ড" },
  { "id": 427, "title": "Cheque", "bangla": "চেক" },
  { "id": 428, "title": "Annual Fee", "bangla": "বার্ষিক ফি" },
  { "id": 429, "title": "Monthly Membership", "bangla": "মাসিক সদস্যপদ" },
  { "id": 430, "title": "Tuition Fees", "bangla": "টিউশন ফি" },
  { "id": 431, "title": "Poverty", "bangla": "দারিদ্র্য" },
  { "id": 432, "title": "Bank Statement", "bangla": "ব্যাংক স্টেটমেন্ট" },
  { "id": 433, "title": "Money Management", "bangla": "মানি ম্যানেজমেন্ট" },
  { "id": 434, "title": "Current Account", "bangla": "কারেন্ট অ্যাকাউন্ট" },
  { "id": 435, "title": "Interest Rate", "bangla": "সুদ হার" },
  { "id": 436, "title": "Deposit", "bangla": "ডিপোজিট" },
  { "id": 437, "title": "Student Account", "bangla": "স্টুডেন্ট অ্যাকাউন্ট" },
  { "id": 438, "title": "Withdraw", "bangla": "অংশগ্রহণ" },
  { "id": 439, "title": "Mortgage", "bangla": "মর্গেজ" },
  { "id": 440, "title": "Grace Period", "bangla": "গ্রেস পিরিয়ড" },
  { "id": 441, "title": "In Advance", "bangla": "অগ্রিম" },
  { "id": 442, "title": "Budget Deficit", "bangla": "বাজেট ঘাটতি" },
  { "id": 443, "title": "Retail Voucher", "bangla": "খুচরা ভাউচার" },
  { "id": 444, "title": "Coupon", "bangla": "কুপন" },
  { "id": 445, "title": "Counterfeit Money", "bangla": "জাল টাকা" },
  { "id": 446, "title": "Debt", "bangla": "ঋণ" },
  { "id": 447, "title": "Interest-Free Credit", "bangla": "সুদ-মুক্ত ঋণ" },
  { "id": 448, "title": "Purchase", "bangla": "ক্রয়" },
  { "id": 449, "title": "Partial Refund", "bangla": "আংশিক রিফান্ড" },
  { "id": 450, "title": "Annuity", "bangla": "এনুইটি" },
  { "id": 451, "title": "Public Money", "bangla": "জনগণের টাকা" },
  { "id": 452, "title": "Taxpayers’ Money", "bangla": "করদাতাদের টাকা" },
  { "id": 453, "title": "Income", "bangla": "আয়" },
  { "id": 454, "title": "Non-Refundable", "bangla": "অরিফান্ডেবল" },
  { "id": 455, "title": "Mastercard", "bangla": "মাস্টারকার্ড" },
  { "id": 456, "title": "Visa", "bangla": "ভিসা" },
  { "id": 457, "title": "Duty-Free Store", "bangla": "ডিউটি-ফ্রি স্টোর" },
  { "id": 458, "title": "Distribution Costs", "bangla": "বিতরণ খরচ" },
  { "id": 459, "title": "Finance Department", "bangla": "আর্থিক বিভাগ" },
  { "id": 460, "title": "Family Finances", "bangla": "পারিবারিক অর্থ" },
  { "id": 461, "title": "Expensive", "bangla": "দামী" },
  { "id": 462, "title": "Cheap", "bangla": "সস্তা" },
  { "id": 463, "title": "Reasonable", "bangla": "যথাযথ" },
  { "id": 464, "title": "Satisfactory", "bangla": "সন্তোষজনক" },
  { "id": 465, "title": "Dangerous", "bangla": "খুব বিপজ্জনক" },
  { "id": 466, "title": "Poor Quality", "bangla": "খারাপ মান" },
  { "id": 467, "title": "Satisfied", "bangla": "সন্তুষ্ট" },
  { "id": 468, "title": "Disappointed", "bangla": "নিরাশ" },
  { "id": 469, "title": "Efficient", "bangla": "কার্যকর" },
  { "id": 470, "title": "Luxurious", "bangla": "আলিশান" },
  { "id": 471, "title": "Safe", "bangla": "নিরাপদ" },
  { "id": 472, "title": "Strongly Recommended", "bangla": "শক্তিশালীভাবে সুপারিশ করা হয়েছে" },
  { "id": 473, "title": "Colored", "bangla": "রঙিন" },
  { "id": 474, "title": "Spotted", "bangla": "স্পটেড" },
  { "id": 475, "title": "Striped", "bangla": "স্ট্রাইপড" },
  { "id": 476, "title": "Souvenir", "bangla": "সুভেনির" },
  { "id": 477, "title": "Trip", "bangla": "ভ্রমণ" },
  { "id": 478, "title": "Tourist Guided Tour", "bangla": "পর্যটক গাইডেড ট্যুর" },
  { "id": 479, "title": "Ticket Office", "bangla": "টিকিট অফিস" },
  { "id": 480, "title": "Guest", "bangla": "অতিথি" },
  { "id": 481, "title": "Reservation", "bangla": "রিজার্ভেশন" },
  { "id": 482, "title": "View", "bangla": "দৃশ্য" },
  { "id": 483, "title": "Culture", "bangla": "সংস্কৃতি" },
  { "id": 484, "title": "Single Double-Bedded Room", "bangla": "একক দ্বৈত বেডেড রুম" },
  { "id": 485, "title": "Picnic", "bangla": "পিকনিক" },
  { "id": 486, "title": "Tourist Attraction", "bangla": "পর্যটক আকর্ষণ" },
  { "id": 487, "title": "Hostel", "bangla": "হোস্টেল" },
  { "id": 488, "title": "Suite", "bangla": "সুইট" },
  { "id": 489, "title": "Memorable", "bangla": "মনে রাখার মতো" },
  { "id": 490, "title": "Aquarium", "bangla": "অ্যাকোরিয়াম" },
  { "id": 491, "title": "Energetic", "bangla": "উদ্যমী" },
  { "id": 492, "title": "Social", "bangla": "সামাজিক" },
  { "id": 493, "title": "Ancient", "bangla": "প্রাচীন" },
  { "id": 494, "title": "Necessary", "bangla": "প্রয়োজনীয়" },
  { "id": 495, "title": "Fantastic", "bangla": "অদ্ভুত" },
  { "id": 496, "title": "Exciting", "bangla": "উত্তেজনাপূর্ণ" },
  { "id": 497, "title": "Fabulous", "bangla": "অসাধারণ" },
  { "id": 498, "title": "Dull", "bangla": "বোরিং" },
  { "id": 499, "title": "Comfortable", "bangla": "সুবিধাজনক" },
  { "id": 500, "title": "Convenient", "bangla": "আরামদায়ক" },
  { "id": 501, "title": "Suitable", "bangla": "উপযুক্ত" },
  { "id": 502, "title": "Affordable", "bangla": "সাশ্রয়ী" },
  { "id": 503, "title": "Voluntary", "bangla": "স্বেচ্ছাসেবী" },
  { "id": 504, "title": "Mandatory", "bangla": "বাধ্যতামূলক" },
  { "id": 505, "title": "Compulsory", "bangla": "বাধ্যতামূলক" },
  { "id": 506, "title": "Temporary", "bangla": "অস্থায়ী" },
  { "id": 507, "title": "Permanent", "bangla": "স্থায়ী" },
  { "id": 508, "title": "Immense", "bangla": "অবিশ্বাস্য" },

  { "id": 509, "title": "Vast", "bangla": "বিশাল" },
  { "id": 510, "title": "Salty", "bangla": "লোনাজাতীয়" },
  { "id": 511, "title": "Extinct", "bangla": "বিলুপ্ত" },
  { "id": 512, "title": "Vulnerable", "bangla": "ঝুঁকিপূর্ণ" },
  { "id": 513, "title": "Pessimistic", "bangla": "নিরাশাবাদী" },
  { "id": 514, "title": "Optimistic", "bangla": "আশাবাদী" },
  { "id": 515, "title": "Realistic", "bangla": "বাস্তববাদী" },
  { "id": 516, "title": "Practical", "bangla": "ব্যবহারিক" },
  { "id": 517, "title": "Knowledgeable", "bangla": "জ্ঞানী" },
  { "id": 518, "title": "Flexible", "bangla": "লচচর" },
  { "id": 519, "title": "Confident", "bangla": "আত্মবিশ্বাসী" },
  { "id": 520, "title": "Western", "bangla": "পশ্চিমা" },
  { "id": 521, "title": "Intensive", "bangla": "তীব্র" },
  { "id": 522, "title": "Tranquil", "bangla": "শান্ত" },
  { "id": 523, "title": "Spectacular", "bangla": "দর্শনীয়" },
  { "id": 524, "title": "Intact", "bangla": "অক্ষুণ্ণ" },
  { "id": 525, "title": "Various", "bangla": "বিভিন্ন" },
  { "id": 526, "title": "Train", "bangla": "প্রশিক্ষণ" },
  { "id": 527, "title": "Develop", "bangla": "উন্নয়ন" },
  { "id": 528, "title": "Collect", "bangla": "সংগ্রহ করা" },
  { "id": 529, "title": "Supervise", "bangla": "পর্যবেক্ষণ করা" },
  { "id": 530, "title": "Mark", "bangla": "চিহ্নিত করা" },
  { "id": 531, "title": "Edit", "bangla": "সম্পাদনা" },
  { "id": 532, "title": "Revise", "bangla": "পুনঃপর্যালোচনা" },
  { "id": 533, "title": "Exhibit", "bangla": "প্রদর্শন করা" },
  { "id": 534, "title": "Donate", "bangla": "দান করা" },
  { "id": 535, "title": "Surpass", "bangla": "অতিক্রম করা" },
  { "id": 536, "title": "Register", "bangla": "নিবন্ধন করা" },
  { "id": 537, "title": "Support", "bangla": "সমর্থন" },
  { "id": 538, "title": "Hunt", "bangla": "শিকার" },
  { "id": 539, "title": "Persuade", "bangla": "অনুপ্রাণিত করা" },
  { "id": 540, "title": "Concentrate", "bangla": "মনোযোগ কেন্দ্রীভূত করা" },
  { "id": 541, "title": "Discuss", "bangla": "আলোচনা করা" },
  { "id": 542, "title": "Suggest", "bangla": "প্রস্তাব করা" },
  { "id": 543, "title": "Arrange", "bangla": "ব্যবস্থা করা" },
  { "id": 544, "title": "Borrow", "bangla": "ধার নেওয়া" },
  { "id": 545, "title": "Immigrate", "bangla": "প্রবাহিত হওয়া" },
  { "id": 546, "title": "Review", "bangla": "পুনঃমূল্যায়ন" },
  { "id": 547, "title": "Learn", "bangla": "শিখা" },
  { "id": 548, "title": "Touch", "bangla": "স্পর্শ করা" },
  { "id": 549, "title": "Jet-Skiing", "bangla": "জেট-স্কিইং" },
  { "id": 550, "title": "Bodyboarding", "bangla": "বডিবোর্ডিং" },
  { "id": 551, "title": "Snowboarding", "bangla": "স্নোবোর্ডিং" },
  { "id": 552, "title": "Cricket", "bangla": "ক্রিকেট" },
  { "id": 553, "title": "Baseball", "bangla": "বেসবল" },
  { "id": 554, "title": "Basketball", "bangla": "বাস্কেটবল" },
  { "id": 555, "title": "Rugby", "bangla": "রাগবি" },
  { "id": 556, "title": "Hang-Gliding", "bangla": "হ্যাং-গ্লাইডিং" },
  { "id": 557, "title": "Skydiving", "bangla": "স্কাইডাইভিং" },
  { "id": 558, "title": "Soccer", "bangla": "সকার" },
  { "id": 559, "title": "American Football", "bangla": "আমেরিকান ফুটবল" },
  { "id": 560, "title": "Hockey", "bangla": "হকি" },
  { "id": 561, "title": "Swimming", "bangla": "সাঁতার" },
  { "id": 562, "title": "Tennis", "bangla": "টেনিস" },
  { "id": 563, "title": "Squash", "bangla": "স্কোয়াশ" },
  { "id": 564, "title": "Javelin", "bangla": "জাভেলিন" },
  { "id": 565, "title": "Badminton", "bangla": "ব্যাডমিন্টন" },
  { "id": 566, "title": "Ping-Pong", "bangla": "পিং-পং" },
  { "id": 567, "title": "Field", "bangla": "মাঠ" },
  { "id": 568, "title": "Court", "bangla": "আদালত" },
  { "id": 569, "title": "Pitch", "bangla": "পিচ" },
  { "id": 570, "title": "Stadium", "bangla": "স্টেডিয়াম" },
  { "id": 571, "title": "Team", "bangla": "টিম" },
  { "id": 572, "title": "Discuss", "bangla": "আলোচনা করা" },
  { "id": 573, "title": "Hammer", "bangla": "হ্যামার" },
  { "id": 574, "title": "High Jump", "bangla": "উচ্চ লাফ" },
  { "id": 575, "title": "Horse Racing", "bangla": "ঘোড়া দৌড়" },
  { "id": 576, "title": "Show Jumping", "bangla": "শো জাম্পিং" },
  { "id": 577, "title": "Polo", "bangla": "পোলো" },
  { "id": 578, "title": "Cycling", "bangla": "সাইক্লিং" },
  { "id": 579, "title": "Canoeing", "bangla": "কানুইং" },
  { "id": 580, "title": "Refreshment", "bangla": "তাজা পানীয়" },
  { "id": 581, "title": "Gymnasium", "bangla": "জিমনেশিয়াম" },
  { "id": 582, "title": "Extreme Sports", "bangla": "এক্সট্রিম খেলাধুলা" },
  { "id": 583, "title": "Paragliding", "bangla": "প্যারাগ্লাইডিং" },
  { "id": 584, "title": "Abseiling", "bangla": "অবসেইলিং" },
  { "id": 586, "title": "Athlete", "bangla": "এথলিট" },
  { "id": 587, "title": "Gym", "bangla": "জিম" },
  { "id": 588, "title": "Bungee Jumping", "bangla": "বাঞ্জি জাম্পিং" },
  { "id": 589, "title": "White-Water Rafting", "bangla": "হোয়াইট-ওয়াটার রাফটিং" },
  { "id": 590, "title": "Surfing", "bangla": "সার্ফিং" },
  { "id": 591, "title": "Windsurfing", "bangla": "উইন্ডসার্ফিং" },
  { "id": 592, "title": "Kitesurfing", "bangla": "কাইটসার্ফিং" },
  { "id": 593, "title": "Mountain Biking", "bangla": "মাউন্টেন বাইকিং" },
  { "id": 594, "title": "Push-Up", "bangla": "পুশ-আপ" },
  { "id": 595, "title": "Judo", "bangla": "জুডো" },
  { "id": 596, "title": "Recreation", "bangla": "বিনোদন" },
  { "id": 597, "title": "Jogging", "bangla": "জগিং" },
  { "id": 598, "title": "Press-Up", "bangla": "প্রেস-আপ" },
  { "id": 599, "title": "Snooker", "bangla": "স্নুকার" },
  { "id": 600, "title": "Walking", "bangla": "হাঁটা" },
  { "id": 601, "title": "Barbell", "bangla": "বারবেল" },
  { "id": 602, "title": "Treadmill", "bangla": "ট্রেডমিল" },
  { "id": 603, "title": "Championship", "bangla": "চ্যাম্পিয়নশিপ" },
  { "id": 604, "title": "Oval", "bangla": "ডিম্বাকৃতির" },
  { "id": 605, "title": "Square", "bangla": "বর্গক্ষেত্র" },
  { "id": 606, "title": "Rectangular", "bangla": "আয়তাকার" },
  { "id": 607, "title": "Triangular", "bangla": "ত্রিভুজাকৃত" },
  { "id": 608, "title": "Polygon", "bangla": "বহুভুজ" },
  { "id": 609, "title": "Spherical", "bangla": "গোলকাকার" },
  { "id": 610, "title": "Circular", "bangla": "বৃত্তাকার" },
  { "id": 611, "title": "Curved", "bangla": "বাঁকা" },
  { "id": 612, "title": "Cylindrical", "bangla": "সিলিন্ড্রিক" },
  { "id": 613, "title": "Three dimensions", "bangla": "তিন মাত্রিক" },
  { "id": 614, "title": "Width", "bangla": "প্রস্থ" },
  { "id": 615, "title": "Length", "bangla": "দৈর্ঘ্য" },
  { "id": 616, "title": "Altitude", "bangla": "উচ্চতা" },
  { "id": 617, "title": "Imperial system", "bangla": "সাম্রাজ্যিক ব্যবস্থা" },
  { "id": 618, "title": "Metric system", "bangla": "মেট্রিক ব্যবস্থা" },
  { "id": 619, "title": "Spiral", "bangla": "সাপেক্ষ" },
  { "id": 620, "title": "Mass", "bangla": "ভর" },
  { "id": 621, "title": "Depth", "bangla": "গভীরতা" },
  { "id": 622, "title": "Breadth", "bangla": "প্রস্থ" },
  { "id": 623, "title": "Height", "bangla": "উচ্চতা" },
  { "id": 624, "title": "Frequency", "bangla": "ফ্রিকোয়েন্সি" },
  { "id": 625, "title": "Humid", "bangla": "আর্দ্র" },
  { "id": 626, "title": "Hot", "bangla": "গরম" },
  { "id": 627, "title": "Sticky", "bangla": "আঠালো" },
  { "id": 628, "title": "Breeze", "bangla": "বাতাস" },
  { "id": 629, "title": "Chilly", "bangla": "ঠান্ডা" },
  { "id": 630, "title": "Cold", "bangla": "ঠান্ডা" },
  { "id": 631, "title": "Cool", "bangla": "শীতল" },
  { "id": 632, "title": "Dry", "bangla": "শুকনো" },
  { "id": 633, "title": "Dusty", "bangla": "ধূসর" },
  { "id": 634, "title": "Freezing", "bangla": "বরফযুক্ত" },
  { "id": 635, "title": "Warm", "bangla": "উষ্ণ" },
  { "id": 636, "title": "Wet", "bangla": "ভেজা" },
  { "id": 637, "title": "Weather forecast", "bangla": "আবহাওয়া পূর্বাভাস" },
  { "id": 638, "title": "Antenna", "bangla": "অ্যান্টেনা" },
  { "id": 639, "title": "Moisture", "bangla": "আর্দ্রতা" },
  { "id": 640, "title": "Helmet", "bangla": "হেলমেট" },
  { "id": 641, "title": "Light", "bangla": "আলো" },
  { "id": 642, "title": "Musical instrument", "bangla": "সঙ্গীত যন্ত্র" },
  { "id": 643, "title": "Cassette", "bangla": "ক্যাসেট" },
  { "id": 644, "title": "Silicon chip", "bangla": "সিলিকন চিপ" },
  { "id": 645, "title": "Digital monitor", "bangla": "ডিজিটাল মনিটর" },
  { "id": 646, "title": "Gadget", "bangla": "যন্ত্রপাতি" },
  { "id": 647, "title": "Device", "bangla": "যন্ত্র" },
  { "id": 648, "title": "Screen", "bangla": "স্ক্রীন" },
  { "id": 649, "title": "Brakes", "bangla": "ব্রেক" },
  { "id": 650, "title": "Wheels", "bangla": "চাকা" },
  { "id": 651, "title": "Mechanical pencil", "bangla": "যান্ত্রিক পেন্সিল" },
  { "id": 652, "title": "Disk", "bangla": "ডিস্ক" },
  { "id": 653, "title": "Backpack", "bangla": "ব্যাকপ্যাক" },
  { "id": 654, "title": "Opera", "bangla": "অপার" },
  { "id": 655, "title": "Orchestra", "bangla": "অর্কেস্ট্রা" },
  { "id": 656, "title": "Concert", "bangla": "কনসার্ট" },
  { "id": 657, "title": "Symphony", "bangla": "সিনফনি" },
  { "id": 658, "title": "The press", "bangla": "দ্য প্রেস" },
  { "id": 659, "title": "Conductor", "bangla": "কন্ডাক্টর" },
  { "id": 660, "title": "Vocalist", "bangla": "গায়ক" },
  { "id": 661, "title": "Audience", "bangla": "দর্শক" },
  { "id": 662, "title": "Festival", "bangla": "উৎসব" },
  { "id": 664, "title": "Exhibition", "bangla": "প্রদর্শনী" },
  { "id": 665, "title": "Classical music", "bangla": "ক্লাসিক্যাল সঙ্গীত" },
  { "id": 666, "title": "Theatre", "bangla": "থিয়েটার" },
  { "id": 667, "title": "Cinemas", "bangla": "সিনেমা" },
  { "id": 668, "title": "Art gallery", "bangla": "শিল্প গ্যালারি" },
  { "id": 669, "title": "Museum", "bangla": "যাদুঘর" },
  { "id": 670, "title": "Ballet", "bangla": "ব্যালে" },
  { "id": 671, "title": "Television", "bangla": "টেলিভিশন" },
  { "id": 672, "title": "Radio", "bangla": "রেডিও" },
  { "id": 673, "title": "Graphics", "bangla": "গ্রাফিক্স" },
  { "id": 674, "title": "Newspaper", "bangla": "সামাচারপত্র" },
  { "id": 675, "title": "Lion", "bangla": "সিংহ" },
  { "id": 676, "title": "Penguin", "bangla": "পেঙ্গুইন" },
  { "id": 677, "title": "Seabirds", "bangla": "সামুদ্রিক পাখি" },
  { "id": 678, "title": "Poultry and game", "bangla": "মুরগি ও খেলার পাখি" },
  { "id": 679, "title": "Birds of prey", "bangla": "শিকারী পাখি" },
  { "id": 680, "title": "Mammals", "bangla": "স্তন্যপায়ী" },
  { "id": 681, "title": "Genus", "bangla": "জেনাস" },
  { "id": 682, "title": "Species", "bangla": "প্রজাতি" },
  { "id": 683, "title": "Cetacean", "bangla": "সেটেসিয়ান" },
  { "id": 684, "title": "Whale", "bangla": "তিমি" },
  { "id": 685, "title": "Primates", "bangla": "প্রাইমেট" },
  { "id": 686, "title": "Rodents", "bangla": "ঁচুড়িপোকা" },
  { "id": 687, "title": "Reptile", "bangla": "সুরঙ্গী" },
  { "id": 688, "title": "Insects", "bangla": "পোকামাকড়" },
  { "id": 689, "title": "Octopus", "bangla": "অক্টোপাস" },
  { "id": 690, "title": "Phylum", "bangla": "ফাইলাম" },
  { "id": 691, "title": "Fish", "bangla": "মাছ" },
  { "id": 692, "title": "Amphibian", "bangla": "অম্ফিবিয়ান" },
  { "id": 693, "title": "Class", "bangla": "শ্রেণী" },
  { "id": 694, "title": "Order", "bangla": "ক্রম" },
  { "id": 695, "title": "Family", "bangla": "পরিবার" },
  { "id": 696, "title": "Livestock", "bangla": "পশুপাখি" },
  { "id": 697, "title": "Creature", "bangla": "প্রাণী" },
  { "id": 698, "title": "Camper", "bangla": "ক্যাম্পার" },
  { "id": 699, "title": "Double-decker bus", "bangla": "ডাবল ডেকার বাস" },
  { "id": 700, "title": "Single-decker", "bangla": "সিঙ্গল ডেকার" },
  { "id": 701, "title": "Minibus", "bangla": "মিনি বাস" },
  { "id": 702, "title": "Forklift truck", "bangla": "ফর্কলিফট ট্রাক" },
  { "id": 703, "title": "School bus", "bangla": "স্কুল বাস" },
  { "id": 704, "title": "Coach", "bangla": "কোচ" },
  { "id": 705, "title": "Truck", "bangla": "ট্রাক" },
  { "id": 706, "title": "Tanker", "bangla": "ট্যাঙ্কার" },
  { "id": 707, "title": "Van", "bangla": "ভ্যান" },
  { "id": 708, "title": "Lorry", "bangla": "লরি" },
  { "id": 709, "title": "Transporter", "bangla": "পরিবহনকারী" },
  { "id": 710, "title": "Tow truck", "bangla": "টোট ট্রাক" },
  { "id": 711, "title": "Breakdown truck", "bangla": "ব্রেকডাউন ট্রাক" },
  { "id": 712, "title": "Pickup", "bangla": "পিকআপ" },
  { "id": 713, "title": "Jeep", "bangla": "জিপ" },
  { "id": 714, "title": "Taxi", "bangla": "ট্যাক্সি" },
  { "id": 715, "title": "Cab", "bangla": "ক্যাব" },
  { "id": 716, "title": "Tram", "bangla": "ট্রাম" },
  { "id": 717, "title": "Underground", "bangla": "আন্ডারগ্রাউন্ড" },
  { "id": 718, "title": "Subway", "bangla": "সাবওয়ে" },
  { "id": 719, "title": "Caravan", "bangla": "কারাভান" },
  { "id": 720, "title": "Tractor", "bangla": "ট্রাক্টর" },
  { "id": 721, "title": "Stream train", "bangla": "স্ট্রিম ট্রেন" },
  { "id": 722, "title": "Freight train", "bangla": "ফ্রেইট ট্রেন" },
  { "id": 723, "title": "Goods train", "bangla": "গুডস ট্রেন" },
  { "id": 724, "title": "Midday", "bangla": "দুপুর" },
  { "id": 725, "title": "Three times", "bangla": "তিন বার" },
  { "id": 726, "title": "Three times per week", "bangla": "সপ্তাহে তিন বার" },
  { "id": 727, "title": "Millennium", "bangla": "সহস্রাব্দ" },
  { "id": 728, "title": "Gap year", "bangla": "গ্যাপ বছর" },
  { "id": 729, "title": "Full-time", "bangla": "পূর্ণকালীন" },
  { "id": 730, "title": "Part-time", "bangla": "অর্ধকালীন" },
  { "id": 731, "title": "Midnight", "bangla": "রাত ১২টা" },
  { "id": 732, "title": "Century", "bangla": "শতাব্দী" },
  { "id": 733, "title": "Decade", "bangla": "দশক" },
  { "id": 734, "title": "Fortnight", "bangla": "পনেরো দিন" },
  { "id": 735, "title": "Aluminum", "bangla": "এলুমিনিয়াম" },
  { "id": 736, "title": "Copper", "bangla": "তামা" },
  { "id": 737, "title": "Fur", "bangla": "ফার" },
  { "id": 738, "title": "Metal", "bangla": "ধাতু" },
  { "id": 739, "title": "Steel", "bangla": "স্টীল" },
  { "id": 740, "title": "Rubber", "bangla": "রাবার" },
  { "id": 742, "title": "Plastic", "bangla": "প্লাস্টিক" },
  { "id": 743, "title": "Ceramics", "bangla": "সিরামিকস" },
  { "id": 744, "title": "Cement", "bangla": "সিমেন্ট" },
  { "id": 745, "title": "Stone", "bangla": "পাথর" },
  { "id": 746, "title": "Textile", "bangla": "বস্ত্র" },
  { "id": 747, "title": "Cotton", "bangla": "সুতা" },
  { "id": 748, "title": "Fabric", "bangla": "ফ্যাব্রিক" },
  { "id": 749, "title": "Wool", "bangla": "উল" },
  { "id": 750, "title": "Glass", "bangla": "গ্লাস" },
  { "id": 751, "title": "Leather", "bangla": "চামড়া" },
  { "id": 752, "title": "Bone", "bangla": "হাড়" },
  { "id": 753, "title": "Paper", "bangla": "কাগজ" },
  { "id": 754, "title": "Lumber/wood", "bangla": "লাকড়ি/কাঠ" },
  { "id": 755, "title": "Glue", "bangla": "আঠা" },
  { "id": 756, "title": "Concrete", "bangla": "কংক্রিট" },
  { "id": 757, "title": "Wax", "bangla": "মোম" },
  { "id": 758, "title": "Silver", "bangla": "রূপা" },
  { "id": 759, "title": "Composite", "bangla": "কম্পোজিট" },
  { "id": 760, "title": "Fiberglass", "bangla": "ফাইবারগ্লাস" },
  { "id": 761, "title": "Gold", "bangla": "সোনা" },
  { "id": 762, "title": "Feather", "bangla": "পক্ষী পালক" },
  { "id": 763, "title": "Sufficient", "bangla": "যথেষ্ট" },
  { "id": 764, "title": "Dialogue", "bangla": "সংলাপ" },
  { "id": 765, "title": "Passport Photo", "bangla": "পাসপোর্ট ছবি" },
  { "id": 766, "title": "State", "bangla": "রাষ্ট্র" },
  { "id": 767, "title": "Variety", "bangla": "বৈচিত্র্য" },
  { "id": 768, "title": "Private Sector", "bangla": "বেসরকারী খাত" },
  { "id": 769, "title": "Practice", "bangla": "অনুশীলন" },
  { "id": 770, "title": "Gender", "bangla": "লিঙ্গ" },
  { "id": 771, "title": "Creativity", "bangla": "সৃজনশীলতা" },
  { "id": 772, "title": "Government", "bangla": "সরকার" },
  { "id": 773, "title": "Individual", "bangla": "ব্যক্তি" },
  { "id": 774, "title": "Original Inhabitant", "bangla": "মূল অধিবাসী" },
  { "id": 775, "title": "Indigenous", "bangla": "আদিবাসী" },
  { "id": 776, "title": "Demonstration", "bangla": "প্রদর্শনী" },
  { "id": 777, "title": "Circuit", "bangla": "সার্কিট" },
  { "id": 778, "title": "Guarantee", "bangla": "গ্যারান্টি" },
  { "id": 779, "title": "Commerce", "bangla": "বাণিজ্য" },
  { "id": 780, "title": "Carriage", "bangla": "বহন" },
  { "id": 781, "title": "Narrative", "bangla": "বর্ণনা" },
  { "id": 782, "title": "Strike", "bangla": "ধর্মঘট" },
  { "id": 783, "title": "Entrance", "bangla": "প্রবেশদ্বার" },
  { "id": 784, "title": "Chocolate", "bangla": "চকলেট" },
  { "id": 785, "title": "Satellite", "bangla": "স্যাটেলাইট" },
  { "id": 786, "title": "Decision", "bangla": "সিদ্ধান্ত" },
  { "id": 787, "title": "Prototype", "bangla": "প্রোটোটাইপ" },
  { "id": 788, "title": "Attitude", "bangla": "মনোভাব" },
  { "id": 789, "title": "Activity", "bangla": "কর্মসূচি" },
  { "id": 790, "title": "Recipient", "bangla": "গ্রহীতা" },
  { "id": 791, "title": "Ultrasound", "bangla": "অল্ট্রাসাউন্ড" },
  { "id": 792, "title": "Pedestrian Safety", "bangla": "পায়ে হাঁটার নিরাপত্তা" },
  { "id": 793, "title": "Daily Routine", "bangla": "দৈনিক রুটিন" },
  { "id": 794, "title": "Personal Fulfillment", "bangla": "ব্যক্তিগত পরিপূর্ণতা" },
  { "id": 795, "title": "Traffic Jams", "bangla": "যানজট" },
  { "id": 796, "title": "Procedures", "bangla": "প্রকৃয়া" },
  { "id": 797, "title": "Creation", "bangla": "সৃষ্টি" },
  { "id": 798, "title": "Senior", "bangla": "জ্যেষ্ঠ" },
  { "id": 799, "title": "Opportunity", "bangla": "সুযোগ" },
  { "id": 800, "title": "Driving License", "bangla": "ড্রাইভিং লাইসেন্স" },
  { "id": 801, "title": "Prize", "bangla": "পুরস্কার" },
  { "id": 802, "title": "Junior", "bangla": "কনিষ্ঠ" },
  { "id": 803, "title": "Process", "bangla": "প্রক্রিয়া" },
  { "id": 804, "title": "Literary", "bangla": "সাহিত্যিক" },
  { "id": 805, "title": "Man-Made", "bangla": "মানবসৃষ্ট" },
  { "id": 806, "title": "Republicans", "bangla": "গণতান্ত্রিক" },
  { "id": 807, "title": "Waiting List", "bangla": "অপেক্ষা তালিকা" },
  { "id": 808, "title": "Sewer Systems", "bangla": "পানি নিষ্কাশন ব্যবস্থা" },
  { "id": 809, "title": "Liberal Democracy", "bangla": "উদার গণতন্ত্র" },
  { "id": 810, "title": "Democrats", "bangla": "গণতান্ত্রিক" },
  { "id": 811, "title": "Umbrella", "bangla": "ছাতা" },
  { "id": 812, "title": "Frequently Updated", "bangla": "প্রায়ই আপডেট করা" },
  { "id": 813, "title": "Lunar Calendar", "bangla": "চন্দ্র পঞ্জিকা" },
  { "id": 814, "title": "Libertarian", "bangla": "স্বাধীনতাবাদী" },
  { "id": 815, "title": "Burger", "bangla": "বার্গার" },
  { "id": 816, "title": "Videos", "bangla": "ভিডিও" },
  { "id": 817, "title": "Fund-Raising Event", "bangla": "অর্থ সংগ্রহের অনুষ্ঠান" },
  { "id": 818, "title": "Magnet", "bangla": "চুম্বক" },
  { "id": 819, "title": "Dialect", "bangla": "উপভাষা" },

  { "id": 821, "title": "Ramification", "bangla": "ফলস্বরূপ" },
  { "id": 822, "title": "Straight", "bangla": "সোজা" },
  { "id": 823, "title": "Nature Conservation", "bangla": "প্রকৃতি সংরক্ষণ" },
  { "id": 824, "title": "Life Expectancy", "bangla": "জীবনকাল প্রত্যাশা" },
  { "id": 825, "title": "Farewell", "bangla": "বিদায়" },
  { "id": 826, "title": "Welfare", "bangla": "কল্যাণ" },
  { "id": 827, "title": "Encyclopedia", "bangla": "বিশ্বকোষ" },
  { "id": 828, "title": "Illiteracy", "bangla": "অশিক্ষা" },
  { "id": 829, "title": "Robot", "bangla": "রোবট" },
  { "id": 830, "title": "Proficiency", "bangla": "দক্ষতা" },
  { "id": 831, "title": "Evolution", "bangla": "বিকাশ" },
  { "id": 832, "title": "Revolution", "bangla": "বিপ্লব" },
  


    
    
  




  ];
  
  export default data;
  