const data = [
  { id: 1, title: "Monday", bangla: "সোমবার" },
  { id: 2, title: "Tuesday", bangla: "মঙ্গলবার" },
  { id: 3, title: "Wednesday", bangla: "বুধবার" },
  { id: 4, title: "Thursday", bangla: "বৃহস্পতিবার" },
  { id: 5, title: "Friday", bangla: "শুক্রবার" },
  { id: 6, title: "Saturday", bangla: "শনিবার" },
  { id: 7, title: "Sunday", bangla: "রবিবার" },
  { id: 8, title: "Weekdays", bangla: "সপ্তাহের দিন" },
  { id: 9, title: "Weekend", bangla: "সপ্তাহান্ত" },
  { id: 10, title: "January", bangla: "জানুয়ারি" },
  { id: 11, title: "February", bangla: "ফেব্রুয়ারি" },
  { id: 12, title: "March", bangla: "মার্চ" },
  { id: 13, title: "April", bangla: "এপ্রিল" },
  { id: 14, title: "May", bangla: "মে" },
  { id: 15, title: "June", bangla: "জুন" },
  { id: 16, title: "July", bangla: "জুলাই" },
  { id: 17, title: "August", bangla: "আগস্ট" },
  { id: 18, title: "September", bangla: "সেপ্টেম্বর" },
  { id: 19, title: "October", bangla: "অক্টোবর" },
  { id: 20, title: "November", bangla: "নভেম্বর" },
  { id: 21, title: "December", bangla: "ডিসেম্বর" },
  { id: 22, title: "Gardening", bangla: "বাগান করা" },
  { id: 23, title: "Stamp Collection", bangla: "টিকেট সংগ্রহ" },
  { id: 24, title: "Orienteering", bangla: "অরিয়েন্টিয়ারিং" },
  { id: 25, title: "Caving", bangla: "গুহায় প্রবেশ" },
  { id: 26, title: "Spelunking", bangla: "গুহা অনুসন্ধান" },
  { id: 27, title: "Scuba Diving", bangla: "স্কুবা ডাইভিং" },
  { id: 28, title: "Snorkelling", bangla: "স্নরকেলিং" },
  { id: 29, title: "Skateboarding", bangla: "স্কেটবোর্ডিং" },
  { id: 30, title: "Bowls", bangla: "বাটি" },
  { id: 31, title: "Archery", bangla: "ধনুকবিদ্যা" },
  { id: 32, title: "Ice Skating", bangla: "আইস স্কেটিং" },
  { id: 33, title: "Dart", bangla: "ডার্ট" },
  { id: 34, title: "Golf", bangla: "গলফ" },
  { id: 35, title: "Billiards", bangla: "বিলিয়ার্ডস" },
  { id: 36, title: "Photography", bangla: "ফটোগ্রাফি" },
  { id: 37, title: "Painting", bangla: "চিত্রকলা" },
  { id: 38, title: "Embroidery", bangla: "কারুকাজ" },
  { id: 39, title: "Climbing", bangla: "পর্বতারোহণ" },
  { id: 40, title: "Chess", bangla: "দাবা" },
  { id: 41, title: "Parachute", bangla: "প্যারাশুট" },
  { id: 42, title: "Pottery", bangla: "মাটির তৈজসপত্র" },
  { id: 43, title: "Woodcarving", bangla: "কাঠ খোদাই" },
  { id: 44, title: "Science", bangla: "বিজ্ঞান" },
  { id: 45, title: "Politics", bangla: "রাজনীতি" },
  { id: 46, title: "Architecture", bangla: "স্থাপত্য" },
  { id: 47, title: "Law", bangla: "আইন" },
  { id: 48, title: "Geography", bangla: "ভূগোল" },
  { id: 49, title: "History", bangla: "ইতিহাস" },
  { id: 50, title: "Biology", bangla: "জীববিজ্ঞান" },
  { id: 51, title: "Archaeology", bangla: "আর্কিওলজি , প্রত্নতত্ত্ব" },
  { id: 52, title: "Statistics", bangla: "পরিসংখ্যান" },
  { id: 54, title: "Mathematics", bangla: "গণিত" },
  { id: 55, title: "Performing Arts", bangla: "প্রদর্শনী শিল্পকলা" },
  { id: 56, title: "Visual Arts", bangla: "দৃশ্য শিল্পকলা" },
  { id: 57, title: "Logic", bangla: "যুক্তি" },
  { id: 58, title: "Physics", bangla: "ভৌত বিজ্ঞান" },
  { id: 59, title: "Psychology", bangla: "মানসিক বিজ্ঞান" },
  { id: 60, title: "Anthropology", bangla: "মানববিদ্যা" },
  { id: 61, title: "Economics", bangla: "অর্থনীতি" },
  { id: 62, title: "Philosophy", bangla: "দর্শনশাস্ত্র" },
  { id: 63, title: "Chemistry", bangla: "রসায়ন" },
  { id: 64, title: "Humanities", bangla: "মানবিক বিজ্ঞান" },
  { id: 65, title: "Business Management", bangla: "ব্যবসা ব্যবস্থাপনা" },
  { id: 66, title: "Agriculture", bangla: "কৃষি" },
  { id: 67, title: "Printer", bangla: "প্রিন্টার" },
  { id: 68, title: "Assessment", bangla: "মূল্যায়ন" },
  { id: 69, title: "Library", bangla: "লাইব্রেরি" },
  { id: 70, title: "Department", bangla: "বিভাগ" },
  { id: 71, title: "Computer Centre", bangla: "কম্পিউটার সেন্টার" },
  { id: 72, title: "Classroom", bangla: "ক্লাসরুম" },
  { id: 73, title: "Attendance", bangla: "উপস্থিতি" },
  { id: 74, title: "Deadline", bangla: "সময়সীমা" },
  { id: 75, title: "Give A Talk", bangla: "একটি আলোচনা দিন" },
  { id: 76, title: "Speech", bangla: "ভাষণ" },
  { id: 77, title: "Lecture", bangla: "বক্তৃতা" },
  { id: 78, title: "Tutor", bangla: "টিউটর" },
  { id: 79, title: "Main Hall", bangla: "প্রধান হল" },
  { id: 80, title: "Computer Laboratory", bangla: "কম্পিউটার ল্যাবরেটরি" },
  { id: 81, title: "Certificate", bangla: "সার্টিফিকেট" },
  { id: 82, title: "Diploma", bangla: "ডিপ্লোমা" },
  { id: 83, title: "Placement Test", bangla: "প্লেসমেন্ট টেস্ট" },
  { id: 84, title: "Facilities", bangla: "সুবিধা" },
  { id: 85, title: "College", bangla: "কলেজ" },
  { id: 86, title: "Dining Room", bangla: "ডাইনিং রুম" },
  { id: 87, title: "Specialist", bangla: "বিশেষজ্ঞ" },
  { id: 88, title: "Knowledge", bangla: "জ্ঞান" },
  { id: 89, title: "International", bangla: "আন্তর্জাতিক" },
  { id: 90, title: "Accommodation", bangla: "আবাসন" },
  { id: 91, title: "Overseas Students", bangla: "বিদেশী শিক্ষার্থী" },
  { id: 92, title: "Full-Time", bangla: "পূর্ণ সময়" },
  { id: 93, title: "Homestay", bangla: "হোমস্টে" },
  { id: 94, title: "Primary", bangla: "প্রাথমিক" },
  { id: 95, title: "Secondary", bangla: "মাধ্যমিক" },
  { id: 96, title: "Intermediate", bangla: "মাঝারি" },
  { id: 97, title: "Media Room", bangla: "মিডিয়া রুম" },
  { id: 98, title: "Commencement", bangla: "আরম্ভ" },
  { id: 99, title: "Dissertation", bangla: "থিসিস" },
  { id: 100, title: "Leaflet", bangla: "লিফলেট" },

  { id: 101, title: "School Reunion", bangla: "স্কুল পুনর্মিলনী" },
  { id: 102, title: "Feedback", bangla: "প্রতিক্রিয়া" },
  { id: 103, title: "Tasks", bangla: "কাজ" },
  { id: 104, title: "Outcomes", bangla: "ফলাফল" },
  { id: 105, title: "Advanced", bangla: "অগ্রসর" },
  { id: 106, title: "Introductory", bangla: "ভূমিকা" },
  { id: 107, title: "Extra Background", bangla: "অতিরিক্ত ব্যাকগ্রাউন্ড" },
  { id: 108, title: "Resources Room", bangla: "সম্পদ কক্ষ" },
  { id: 109, title: "Staff", bangla: "স্টাফ" },
  { id: 110, title: "Higher Education", bangla: "উচ্চ শিক্ষা" },
  { id: 111, title: "Guidelines", bangla: "নির্দেশিকা" },
  { id: 112, title: "Post-Secondary", bangla: "মাধ্যমিক পরবর্তী" },
  { id: 113, title: "Faculty", bangla: "অনুষদ" },
  { id: 114, title: "Pupils", bangla: "শিক্ষার্থী" },
  { id: 115, title: "Pencil", bangla: "পেন্সিল" },
  { id: 116, title: "Supervisor", bangla: "পর্যবেক্ষক" },
  { id: 117, title: "Bachelor’s Degree", bangla: "ব্যাচেলর ডিগ্রী" },
  { id: 118, title: "Compound", bangla: "সংকর" },
  { id: 119, title: "Foreign Students", bangla: "বিদেশী ছাত্র" },
  { id: 120, title: "Schedule", bangla: "সময়সূচী" },
  { id: 121, title: "Vocabulary", bangla: "শব্দভান্ডার" },
  { id: 122, title: "Student Support Services", bangla: "ছাত্র সহায়ক সেবা" },
  { id: 123, title: "Student Retention", bangla: "ছাত্র ধারন" },
  { id: 124, title: "Publication", bangla: "প্রকাশনা" },
  { id: 125, title: "Registrar’s Office", bangla: "রেজিস্ট্রারের অফিস" },
  { id: 126, title: "Stationery", bangla: "কাগজপত্র" },
  { id: 127, title: "Designer", bangla: "ডিজাইনার" },
  { id: 128, title: "Occupation", bangla: "পেশা" },
  { id: 129, title: "Profession", bangla: "পেশাগত" },
  { id: 130, title: "Decorator", bangla: "সাজসজ্জাকারী" },
  { id: 131, title: "Architect", bangla: "স্থপতি" },
  { id: 132, title: "Engineer", bangla: "এঞ্জিনিয়ার" },
  { id: 133, title: "Waiter", bangla: "ওয়েটার" },
  { id: 134, title: "Teacher", bangla: "শিক্ষক" },
  { id: 135, title: "Vacancy", bangla: "খালি পদ" },
  { id: 136, title: "Professor", bangla: "প্রফেসর" },
  { id: 137, title: "Specialist", bangla: "বিশেষজ্ঞ" },
  { id: 138, title: "Manager", bangla: "ম্যানেজার" },
  { id: 139, title: "Waitress", bangla: "ওয়েট্রেস" },
  { id: 140, title: "Psychologist", bangla: "মনোবিজ্ঞানী" },
  { id: 141, title: "Volunteer", bangla: "স্বেচ্ছাসেবক" },
  { id: 142, title: "Craftsman", bangla: "শিল্পী , কারিগর" },
  { id: 143, title: "Work Experience", bangla: "কর্ম অভিজ্ঞতা" },
  { id: 144, title: "Curriculum Vitae", bangla: "সিভি" },
  { id: 145, title: "Freelance", bangla: "ফ্রিল্যান্স" },
  { id: 146, title: "Secretary", bangla: "সেক্রেটারি" },
  { id: 147, title: "Mail Address", bangla: "মেইল ঠিকানা" },
  { id: 148, title: "Receptionist", bangla: "রিসেপশনিস্ট" },
  { id: 149, title: "Pilot", bangla: "পাইলট" },
  { id: 150, title: "Lecturer", bangla: "প্রভাষক" },
  { id: 151, title: "Office Assistant", bangla: "অফিস সহকারী" },
  { id: 152, title: "Clerk", bangla: "ক্লার্ক" },
  { id: 153, title: "Accountant", bangla: "অ্যাকাউন্ট্যান্ট" },
  { id: 154, title: "Guard", bangla: "প্রহরী" },
  { id: 155, title: "Flight Attendant", bangla: "ফ্লাইট অ্যাটেনডেন্ট" },
  { id: 156, title: "Cashier", bangla: "ক্যাশিয়ার" },
  { id: 157, title: "Captain", bangla: "ক্যাপ্টেন" },
  { id: 158, title: "Yoga", bangla: "যোগ" },
  { id: 159, title: "Tai-Chi", bangla: "তাই-চি" },
  { id: 160, title: "Keep-Fit", bangla: "ফিট থাকা" },
  { id: 161, title: "Salad Bar", bangla: "সালাদ বার" },
  { id: 162, title: "Vegetarian", bangla: "সবজি খাদ্যাভ্যাসী" },
  { id: 163, title: "Outdoor Activities", bangla: "আউটডোর কার্যক্রম" },
  { id: 164, title: "Leisure Time", bangla: "অবসর সময়" },
  { id: 165, title: "Disease", bangla: "রোগ" },
  { id: 166, title: "Meal", bangla: "খাবার" },
  { id: 167, title: "Protein", bangla: "প্রোটিন" },
  { id: 168, title: "Balanced Diet", bangla: "সুষম খাদ্য" },
  { id: 169, title: "Food Pyramid", bangla: "খাদ্য পিরামিড" },
  { id: 170, title: "Vitamin", bangla: "ভিটামিন" },
  { id: 171, title: "Carbohydrates", bangla: "কার্বোহাইড্রেট" },
  { id: 172, title: "Rice", bangla: "চাল" },
  { id: 173, title: "Pasta", bangla: "পাস্তা" },
  { id: 174, title: "Potatoes", bangla: "আলু" },
  { id: 175, title: "Pizza", bangla: "পিজা" },
  { id: 176, title: "Tomatoes", bangla: "টমেটো" },
  { id: 177, title: "Bread", bangla: "রুটি" },
  { id: 178, title: "Cereals", bangla: "শস্য" },
  { id: 179, title: "Minerals", bangla: "খনিজ" },
  { id: 180, title: "Zinc", bangla: "জিঙ্ক" },

  { id: 181, title: "Meat", bangla: "মাংস" },
  { id: 182, title: "Seafood", bangla: "সীফুড" },
  { id: 183, title: "Eggs", bangla: "ডিম" },
  { id: 184, title: "Beans", bangla: "মটরশুটি" },
  { id: 185, title: "Milk", bangla: "দুধ" },
  { id: 186, title: "Cheese", bangla: "পনির" },
  { id: 187, title: "Yoghurt", bangla: "দই" },
  { id: 188, title: "Fruit", bangla: "ফল" },
  { id: 189, title: "Vegetables", bangla: "সবজি" },
  { id: 190, title: "Citrus Fruits", bangla: "সাইট্রাস ফল" },
  { id: 191, title: "Green Pepper", bangla: "সবুজ মরিচ" },
  { id: 192, title: "Blackcurrant", bangla: "ব্ল্যাককারেন্ট" },
  { id: 193, title: "Nuts", bangla: "বাদাম" },
  { id: 194, title: "Egg Yolk", bangla: "ডিমের কুসুম" },
  { id: 195, title: "Liver", bangla: "যকৃৎ" },
  { id: 196, title: "Medicine", bangla: "ঔষধ" },
  { id: 197, title: "Treatment", bangla: "চিকিৎসা" },
  { id: 198, title: "Remedy", bangla: "প্রতিকার" },
  { id: 199, title: "Nursing Care", bangla: "নার্সিং যত্ন" },
  { id: 200, title: "Nursery", bangla: "নার্সারি" },
  { id: 201, title: "Rhinoceros", bangla: "গণ্ডার" },
  { id: 202, title: "Field", bangla: "মাঠ" },
  { id: 203, title: "Footbridge", bangla: "পায়ে চলার সেতু" },
  { id: 204, title: "River", bangla: "নদী" },
  { id: 205, title: "Mountain", bangla: "পর্বত" },
  { id: 206, title: "Forest", bangla: "বন" },
  { id: 207, title: "Village", bangla: "গ্রাম" },
  { id: 208, title: "Environment", bangla: "পরিবেশ" },
  { id: 209, title: "Waterfall", bangla: "ঝর্ণা" },
  { id: 210, title: "Cylinder", bangla: "বেলন" },
  { id: 211, title: "Reef", bangla: "প্রাচীর" },
  { id: 212, title: "Lake", bangla: "হ্রদ" },
  { id: 213, title: "Valley", bangla: "উঁচু অঞ্চল" },
  { id: 214, title: "Peninsula", bangla: "উপদ্বীপ" },
  { id: 215, title: "Cushion", bangla: "বালিশ" },
  { id: 216, title: "Avalanche", bangla: "তুষারপাত" },
  { id: 217, title: "Typhoon", bangla: "ধ্বংসাত্মক ঘূর্ণিঝড়" },
  { id: 218, title: "Hill", bangla: "টিলা" },
  { id: 219, title: "Cliff", bangla: "চূড়া" },
  { id: 220, title: "Island", bangla: "দ্বীপ" },
  { id: 221, title: "Desertification", bangla: "মরুকরণের" },
  { id: 222, title: "Volcano", bangla: "অগ্ন্যুৎপাত" },
  { id: 223, title: "Disaster", bangla: "দুর্যোগ" },
  { id: 224, title: "Landslides", bangla: "ভূস্মতি" },
  { id: 225, title: "Storm", bangla: "ঝড়" },
  { id: 226, title: "Flood", bangla: "বন্যা" },
  { id: 227, title: "Hurricane", bangla: "ঘূর্ণিঝড়" },
  { id: 228, title: "Pond", bangla: "পুকুর" },
  { id: 229, title: "Catastrophe", bangla: "বিপর্যয়" },
  { id: 230, title: "Erosion", bangla: "ক্ষয়" },
  { id: 231, title: "Jungle", bangla: "জঙ্গল" },
  { id: 232, title: "Oasis", bangla: "মরুদ্যান" },
  { id: 233, title: "Dam", bangla: "বাঁধ" },
  { id: 234, title: "Canyon", bangla: "গিরিখাত" },
  { id: 235, title: "Coal", bangla: "কয়লা" },
  { id: 236, title: "Fossil Fuels", bangla: "জৈব জ্বালানি" },
  { id: 237, title: "Acid Rain", bangla: "অম্ল বৃষ্টি" },
  { id: 238, title: "Global Warming", bangla: "গ্লোবাল ওয়ার্মিং" },
  { id: 239, title: "Carbon Dioxide", bangla: "কার্বন ডাইঅক্সাইড" },
  { id: 240, title: "Greenhouse Effect", bangla: "গ্রীনহাউস প্রভাব" },
  { id: 241, title: "Burning Fossil", bangla: "জৈব জ্বালানি পোড়ানো" },
  { id: 242, title: "Exhaust Fumes", bangla: "নিষ্কাশিত ধোঁয়া" },
  { id: 243, title: "Smog", bangla: "ধোঁয়া" },
  { id: 244, title: "Climate", bangla: "আবহাওয়া" },
  { id: 245, title: "Pollution", bangla: "দূষণ" },
  { id: 246, title: "Temperature", bangla: "তাপমাত্রা" },
  { id: 247, title: "Power Plants", bangla: "শক্তি উৎপাদন কেন্দ্র" },
  { id: 248, title: "Deforestation", bangla: "বনধ্বংস" },
  { id: 249, title: "Nitrogen Oxide", bangla: "নাইট্রোজেন অক্সাইড" },
  { id: 250, title: "Horizon", bangla: "দিগন্ত" },
  { id: 251, title: "Cattle", bangla: "গবাদি পশু" },
  { id: 252, title: "Wind Turbine", bangla: "বাতাস টারবাইন" },
  { id: 253, title: "Renewable", bangla: "পুনঃনবীকরণযোগ্য" },
  { id: 254, title: "Source Of Energy", bangla: "শক্তির উৎস" },
  { id: 255, title: "Reliable", bangla: "বিশ্বাসযোগ্য" },
  { id: 256, title: "Solar Panels", bangla: "সৌর প্যানেল" },
  { id: 257, title: "Solar Power", bangla: "সৌর শক্তি" },
  { id: 258, title: "Hydroelectric Power", bangla: "জলবিদ্যুৎ" },
  { id: 259, title: "Environmentally Friendly", bangla: "পরিবেশবান্ধব" },
  { id: 260, title: "Oxygen", bangla: "অক্সিজেন" },
  { id: 261, title: "Chemical-Free", bangla: "রসায়ন মুক্ত" },
  { id: 262, title: "Vegetation", bangla: " উদ্ভিদ" },
  { id: 263, title: "Sea Level", bangla: "সমুদ্র স্তর" },
  { id: 264, title: "Ocean Currents", bangla: "সাগর প্রবাহ" },
  { id: 265, title: "Soil Conditioner", bangla: "মাটি শোধক" },
  { id: 266, title: "Firewood", bangla: "কাঠ" },
  { id: 267, title: "Altitude", bangla: "উচ্চতা" },
  { id: 268, title: "Degradation", bangla: "অবনতি" },
  { id: 269, title: "Drought", bangla: "খরা" },
  { id: 270, title: "Contaminated", bangla: "দূষিত" },
  { id: 271, title: "Catalogue", bangla: "ক্যাটালগ" },
  { id: 272, title: "Interview", bangla: "সাক্ষাৎকার" },
  { id: 273, title: "Research Method", bangla: "গবেষণা পদ্ধতি" },
  { id: 274, title: "Entertainment Industry", bangla: "বিনোদন শিল্প" },
  { id: 275, title: "Tv Program", bangla: "টিভি প্রোগ্রাম" },
  { id: 276, title: "Strategies", bangla: "কৌশল" },
  { id: 277, title: "Leadership", bangla: "নেতৃত্ব" },
  { id: 278, title: "Management", bangla: "ব্যবস্থাপনা" },
  { id: 279, title: "Customer", bangla: "গ্রাহক" },
  { id: 280, title: "Special Offer", bangla: "বিশেষ অফার" },
  { id: 281, title: "Collecting Data", bangla: "ডেটা সংগ্রহ" },
  { id: 282, title: "Display", bangla: "প্রদর্শন" },
  { id: 283, title: "Products", bangla: "পণ্য" },
  { id: 284, title: "Questionnaire", bangla: "প্রশ্নাবলী" },
  { id: 285, title: "Survey", bangla: "সমীক্ষা" },
  { id: 286, title: "Mass Media", bangla: "মাধ্যম" },
  { id: 287, title: "Poll", bangla: "ভোট" },
  { id: 288, title: "Business Card", bangla: "ব্যবসায়িক কার্ড" },
  { id: 289, title: "Training", bangla: "প্রশিক্ষণ" },
  { id: 290, title: "Diameter", bangla: "ব্যাসার্ধ" },
  { id: 291, title: "Statistic", bangla: "পরিসংখ্যান" },
  { id: 292, title: "Profit Margin", bangla: "মুনাফা মার্জিন" },
  { id: 293, title: "Newsletter", bangla: "নিউজলেটার" },
  { id: 294, title: "Competition", bangla: "প্রতিযোগিতা" },
  { id: 295, title: "Merchandise", bangla: "বিপণন" },
  { id: 296, title: "Manufacture", bangla: "উত্পাদন" },
  { id: 297, title: "Recruitment", bangla: "নিয়োগ" },
  { id: 298, title: "Dome", bangla: "গম্বুজ" },
  { id: 299, title: "Palace", bangla: "রাজপ্রাসাদ" },
  { id: 300, title: "Fort", bangla: "দুর্গ" },

  { id: 301, title: "Castle", bangla: "দুর্গ" },
  { id: 302, title: "Glasshouse", bangla: "কাচঘর" },
  { id: 303, title: "Pyramid", bangla: "পিরামিড" },
  { id: 304, title: "Log Cabin", bangla: "কাঠের কুটির" },
  { id: 305, title: "Lighthouse", bangla: "বাতিঘর" },
  { id: 306, title: "Hut", bangla: "কুটির" },
  { id: 307, title: "Skyscraper", bangla: "আকাশচুম্বী ভবন" },
  { id: 308, title: "Sculpture", bangla: "ভাস্কর্য" },
  { id: 309, title: "Chimney", bangla: "চিমনি" },
  { id: 310, title: "Bedroom", bangla: "শোবার ঘর" },
  { id: 311, title: "Semi-Detached House", bangla: "অর্ধ-বিচ্ছিন্ন বাড়ি" },
  { id: 312, title: "Duplex", bangla: "ডুপ্লেক্স" },
  { id: 313, title: "Townhouse", bangla: "টাউনহাউস" },
  { id: 314, title: "Row House", bangla: "সারি ঘর" },
  { id: 315, title: "Bungalow", bangla: "বাঙ্গালো" },
  { id: 316, title: "Thatched Cottage", bangla: "খড়ের কুটির" },
  { id: 317, title: "Mobile Home", bangla: "মোবাইল বাড়ি" },
  { id: 318, title: "Houseboat", bangla: "বোট বাড়ি" },
  { id: 319, title: "A Block Of Flats", bangla: "ফ্ল্যাটের ব্লক" },
  { id: 320, title: "Apartment Building", bangla: "এপার্টমেন্ট ভবন" },
  { id: 321, title: "Condominium", bangla: "কনডমিনিয়াম" },
  { id: 322, title: "Basement", bangla: "তলকক্ষ" },
  { id: 323, title: "Landlord", bangla: "মালিক" },
  { id: 324, title: "Terraced House", bangla: "সারি বাড়ি" },
  { id: 325, title: "Tenant", bangla: "ভাড়াটিয়া" },
  { id: 326, title: "Rent", bangla: "ভাড়া" },
  { id: 327, title: "Lease", bangla: "লিজ" },
  { id: 328, title: "Neighbourhood", bangla: "আশপাশ" },
  { id: 329, title: "Suburb", bangla: "উপশহর" },
  { id: 330, title: "Dormitory", bangla: "ডর্মিটরি" },
  { id: 331, title: "Story", bangla: "মহল" },
  { id: 332, title: "Kitchen", bangla: "রান্নাঘর" },
  { id: 333, title: "Refrigerator", bangla: "রেফ্রিজারেটর" },
  { id: 334, title: "Microwave", bangla: "মাইক্রোওয়েভ" },
  { id: 335, title: "Sofa", bangla: "সোফা" },
  { id: 336, title: "Coffee Table", bangla: "কফি টেবিল" },
  { id: 337, title: "Ground Floor", bangla: "ভূতল" },
  { id: 338, title: "Oven", bangla: "চুলা" },
  { id: 339, title: "Hallway", bangla: "পথচলা" },
  { id: 340, title: "Insurance", bangla: "বিমা" },
  { id: 341, title: "Central Station", bangla: "কেন্দ্রীয় স্টেশন" },
  { id: 342, title: "Cities", bangla: "শহরসমূহ" },
  { id: 343, title: "Street", bangla: "রাস্তা" },
  { id: 344, title: "Lane", bangla: "গলি" },
  { id: 345, title: "City Centre", bangla: "শহরের কেন্দ্র" },
  { id: 346, title: "Car Park", bangla: "গাড়ি পার্ক" },
  { id: 347, title: "Department Store", bangla: "ডিপার্টমেন্টাল স্টোর" },
  { id: 348, title: "Bridge", bangla: "সেতু" },
  { id: 349, title: "Temple", bangla: "মন্দির" },
  { id: 350, title: "Hospital", bangla: "হাসপাতাল" },

  { id: 351, title: "Garden", bangla: "বাগান" },
  { id: 352, title: "Avenue", bangla: "অ্যাভিনিউ" },
  { id: 353, title: "Embassy", bangla: "দূতাবাস" },
  { id: 354, title: "Road System", bangla: "রাস্তা ব্যবস্থা" },
  { id: 355, title: "Boat", bangla: "নৌকা" },
  { id: 356, title: "Lifeboat", bangla: "লাইফবোট" },
  { id: 357, title: "Cargo Plane", bangla: "কার্গো বিমান" },
  { id: 358, title: "Shipment", bangla: "পাঠানো" },
  { id: 359, title: "Container Ship", bangla: "কন্টেইনার জাহাজ" },
  { id: 360, title: "Ferry", bangla: "ফেরি" },
  { id: 361, title: "Liner", bangla: "লাইনার" },
  { id: 362, title: "Canal Boat", bangla: "নদীর নৌকা" },
  { id: 363, title: "Narrowboat", bangla: "সংকীর্ণ নৌকা" },
  { id: 364, title: "Dinghy Sailing", bangla: "ডিঙ্গি পালতোলা" },
  { id: 365, title: "Hovercraft", bangla: "হোভারক্রাফট" },
  { id: 366, title: "Hydrofoil", bangla: "হাইড্রোফয়েল" },
  { id: 367, title: "Sailboat", bangla: "পালতোলা নৌকা" },
  { id: 368, title: "Paddle Steamer", bangla: "চাকা চালিত বাষ্পীয় নৌকা" },
  { id: 369, title: "Cabin Cruiser", bangla: "কেবিন ক্রুজার" },
  { id: 370, title: "Kayak", bangla: "কায়াক" },
  { id: 371, title: "Canoe", bangla: "ক্যানো" },
  { id: 372, title: "Punt", bangla: "পান্ট" },
  { id: 373, title: "Gondola", bangla: "গন্ডোলা" },
  { id: 374, title: "Aircraft", bangla: "বিমান" },
  { id: 375, title: "Rowing Boat", bangla: "বৈঠার নৌকা" },
  { id: 376, title: "Pilot", bangla: "পাইলট" },
  { id: 377, title: "Passenger", bangla: "যাত্রী" },
  { id: 378, title: "Crew", bangla: "ক্রু" },
  { id: 379, title: "Terminal", bangla: "টার্মিনাল" },
  { id: 380, title: "Runway", bangla: "রানওয়ে" },
  { id: 381, title: "Hangar", bangla: "হ্যাঙ্গার" },
  { id: 382, title: "Airport", bangla: "বিমানবন্দর" },
  { id: 383, title: "Control Tower", bangla: "নিয়ন্ত্রণ টাওয়ার" },
  { id: 384, title: "Baggage Claim", bangla: "ব্যাগেজ দাবি" },
  { id: 385, title: "Customs", bangla: "কাস্টমস" },
  { id: 386, title: "Security Check", bangla: "নিরাপত্তা পরীক্ষা" },
  { id: 387, title: "Departure", bangla: "প্রস্থান" },
  { id: 388, title: "Arrival", bangla: "আগমন" },
  { id: 389, title: "Duty-Free Shop", bangla: "ডিউটি ফ্রি দোকান" },
  { id: 390, title: "Boarding Pass", bangla: "বোর্ডিং পাস" },
  { id: 391, title: "Check-In", bangla: "চেক-ইন" },
  { id: 392, title: "Flight", bangla: "ফ্লাইট" },
  { id: 393, title: "Destination", bangla: "গন্তব্য" },
  { id: 394, title: "Ticket", bangla: "টিকিট" },
  { id: 395, title: "Travel", bangla: "ভ্রমণ" },
  { id: 396, title: "Journey", bangla: "যাত্রা" },
  { id: 397, title: "Excursion", bangla: "অভিযান" },
  { id: 398, title: "Tour", bangla: "ট্যুর" },
  { id: 399, title: "Holiday", bangla: "ছুটি" },
  { id: 400, title: "Sightseeing", bangla: "ভ্রমণ দর্শন" },
  { id: 401, title: "Guide", bangla: "গাইড" },
  { id: 402, title: "Souvenir", bangla: "স্মারক" },
  { id: 403, title: "Hotel", bangla: "হোটেল" },
  { id: 404, title: "Accommodation", bangla: "আবাসন" },
  { id: 405, title: "Booking", bangla: "বুকিং" },
  { id: 406, title: "Reservation", bangla: "সংরক্ষণ" },
  { id: 407, title: "Reception", bangla: "রিসেপশন" },
  { id: 408, title: "Room Service", bangla: "রুম সার্ভিস" },
  { id: 409, title: "Suite", bangla: "সুইট" },
  { id: 410, title: "Hostel", bangla: "হোস্টেল" },
  { id: 411, title: "Lodging", bangla: "আবাসন" },
  { id: 412, title: "Backpacker", bangla: "পিছনে বস্তাবহনকারী পর্যটক" },
  { id: 413, title: "Campsite", bangla: "ক্যাম্পের স্থান" },
  { id: 414, title: "Tent", bangla: "তাঁবু" },
  { id: 415, title: "Hiking", bangla: "পাহাড় ভ্রমণ" },
  { id: 416, title: "Backpacking", bangla: "পিছনে বস্তাবহন" },
  { id: 417, title: "Adventure", bangla: "অ্যাডভেঞ্চার" },
  { id: 418, title: "Explore", bangla: "অন্বেষণ" },
  { id: 419, title: "Map", bangla: "মানচিত্র" },
  { id: 420, title: "Compass", bangla: "কম্পাস" },
  { id: 421, title: "Itinerary", bangla: "ভ্রমণসূচি" },
  { id: 422, title: "Journey Planner", bangla: "ভ্রমণ পরিকল্পনাকারী" },
  { id: 423, title: "Packing", bangla: "প্যাকিং" },
  { id: 424, title: "Luggage", bangla: "ব্যাগ" },
  { id: 425, title: "Suitcase", bangla: "সুটকেস" },
  { id: 426, title: "Backpack", bangla: "পিঠের ব্যাগ" },
  { id: 427, title: "Travel Bag", bangla: "ভ্রমণ ব্যাগ" },
  { id: 428, title: "Travel Insurance", bangla: "ভ্রমণ বিমা" },
  { id: 429, title: "Guidebook", bangla: "গাইডবুক" },
  { id: 430, title: "Handbook", bangla: "হ্যান্ডবুক" },
  { id: 431, title: "Brochure", bangla: "ব্রোশিওর" },
  { id: 432, title: "Pamphlet", bangla: "পুস্তিকা" },
  { id: 433, title: "Leaflet", bangla: "লিফলেট" },
  { id: 434, title: "Directory", bangla: "ডিরেক্টরি" },
  { id: 435, title: "Voucher", bangla: "ভাউচার" },
  { id: 436, title: "Coupon", bangla: "কুপন" },
  { id: 437, title: "Discount", bangla: "ছাড়" },
  { id: 438, title: "Promotion", bangla: "প্রমোশন" },
  { id: 439, title: "Offer", bangla: "অফার" },
  { id: 440, title: "Deal", bangla: "ডিল" },
  { id: 441, title: "Package", bangla: "প্যাকেজ" },
  { id: 442, title: "Customs Officer", bangla: "কাস্টমস অফিসার" },
  { id: 443, title: "Immigration Officer", bangla: "ইমিগ্রেশন অফিসার" },
  { id: 444, title: "Border", bangla: "সীমান্ত" },
  { id: 445, title: "Embassy", bangla: "দূতাবাস" },
  { id: 446, title: "Consulate", bangla: "কনস্যুলেট" },
  { id: 447, title: "Visa", bangla: "ভিসা" },
  { id: 448, title: "Passport", bangla: "পাসপোর্ট" },
  { id: 449, title: "Visa Application", bangla: "ভিসা আবেদন" },
  { id: 450, title: "Travel Permit", bangla: "ভ্রমণ অনুমতি" },
  { id: 451, title: "Customs Duty", bangla: "কাস্টমস শুল্ক" },
  { id: 452, title: "Duty-Free", bangla: "ডিউটি ফ্রি" },
  { id: 453, title: "Tax-Free", bangla: "করমুক্ত" },
  { id: 454, title: "Currency Exchange", bangla: "মুদ্রা বিনিময়" },

  { id: 455, title: "Mastercard", bangla: "মাস্টারকার্ড" },
  { id: 456, title: "Visa", bangla: "ভিসা" },
  { id: 457, title: "Duty-Free Store", bangla: "ডিউটি-ফ্রি স্টোর" },
  { id: 458, title: "Distribution Costs", bangla: "বিতরণ খরচ" },
  { id: 459, title: "Finance Department", bangla: "আর্থিক বিভাগ" },
  { id: 460, title: "Family Finances", bangla: "পারিবারিক অর্থ" },
  { id: 461, title: "Expensive", bangla: "দামী" },
  { id: 462, title: "Cheap", bangla: "সস্তা" },
  { id: 463, title: "Reasonable", bangla: "যথাযথ" },
  { id: 464, title: "Satisfactory", bangla: "সন্তোষজনক" },
  { id: 465, title: "Dangerous", bangla: "বিপজ্জনক" },
  { id: 466, title: "Poor Quality", bangla: "দরিদ্র গুণমান" },
  { id: 467, title: "Satisfied", bangla: "সন্তুষ্ট" },
  { id: 468, title: "Disappointed", bangla: "নিরাশ , হতাশ" },

  { id: 469, title: "Efficient", bangla: "কার্যকর" },
  { id: 470, title: "Luxurious", bangla: "আলিশান" },
  { id: 471, title: "Safe", bangla: "নিরাপদ" },
  {
    id: 472,
    title: "Strongly Recommended",
    bangla: "শক্তিশালীভাবে সুপারিশ করা হয়েছে",
  },
  { id: 473, title: "Colored", bangla: "রঙিন" },
  { id: 474, title: "Spotted", bangla: "স্পটেড" },
  { id: 475, title: "Striped", bangla: "স্ট্রাইপড" },
  { id: 476, title: "Souvenir", bangla: "সুভেনির" },
  { id: 477, title: "Trip", bangla: "ভ্রমণ" },
  { id: 478, title: "Tourist Guided Tour", bangla: "পর্যটক গাইডেড ট্যুর" },
  { id: 479, title: "Ticket Office", bangla: "টিকিট অফিস" },
  { id: 480, title: "Guest", bangla: "অতিথি" },
  { id: 481, title: "Reservation", bangla: "রিজার্ভেশন" },
  { id: 482, title: "View", bangla: "দৃশ্য" },
  { id: 483, title: "Culture", bangla: "সংস্কৃতি" },
  {
    id: 484,
    title: "Single Double-Bedded Room",
    bangla: "একক দ্বৈত বেডেড রুম",
  },
  { id: 485, title: "Picnic", bangla: "পিকনিক" },
  { id: 486, title: "Tourist Attraction", bangla: "পর্যটক আকর্ষণ" },
  { id: 487, title: "Hostel", bangla: "হোস্টেল" },
  { id: 488, title: "Suite", bangla: "সুইট" },
  { id: 489, title: "Memorable", bangla: "মনে রাখার মতো" },
  { id: 490, title: "Aquarium", bangla: "অ্যাকোরিয়াম" },
  { id: 491, title: "Energetic", bangla: "উদ্যমী" },
  { id: 492, title: "Social", bangla: "সামাজিক" },
  { id: 493, title: "Ancient", bangla: "প্রাচীন" },
  { id: 494, title: "Necessary", bangla: "প্রয়োজনীয়" },
  { id: 495, title: "Fantastic", bangla: "অদ্ভুত" },
  { id: 496, title: "Exciting", bangla: "উত্তেজনাপূর্ণ" },
  { id: 497, title: "Fabulous", bangla: "অসাধারণ" },
  { id: 498, title: "Dull", bangla: "বোরিং" },
  { id: 499, title: "Comfortable", bangla: "সুবিধাজনক" },
  { id: 500, title: "Convenient", bangla: "আরামদায়ক" },
  { id: 501, title: "Suitable", bangla: "উপযুক্ত" },
  { id: 502, title: "Affordable", bangla: "সাশ্রয়ী" },
  { id: 503, title: "Voluntary", bangla: "স্বেচ্ছাসেবী" },
  { id: 504, title: "Mandatory", bangla: "বাধ্যতামূলক" },
  { id: 505, title: "Compulsory", bangla: "বাধ্যতামূলক" },
  { id: 506, title: "Temporary", bangla: "অস্থায়ী" },
  { id: 507, title: "Permanent", bangla: "স্থায়ী" },
  { id: 508, title: "Immense", bangla: "অবিশ্বাস্য" },

  { id: 509, title: "Vast", bangla: "বিশাল" },
  { id: 510, title: "Salty", bangla: "লোনাজাতীয়" },
  { id: 511, title: "Extinct", bangla: "বিলুপ্ত" },
  { id: 512, title: "Vulnerable", bangla: "ঝুঁকিপূর্ণ" },
  { id: 513, title: "Pessimistic", bangla: "নিরাশাবাদী" },
  { id: 514, title: "Optimistic", bangla: "আশাবাদী" },
  { id: 515, title: "Realistic", bangla: "বাস্তববাদী" },
  { id: 516, title: "Practical", bangla: "ব্যবহারিক" },
  { id: 517, title: "Knowledgeable", bangla: "জ্ঞানী" },
  { id: 518, title: "Flexible", bangla: "লচচর" },
  { id: 519, title: "Confident", bangla: "আত্মবিশ্বাসী" },
  { id: 520, title: "Western", bangla: "পশ্চিমা" },
  { id: 521, title: "Intensive", bangla: "তীব্র" },
  { id: 522, title: "Tranquil", bangla: "শান্ত" },
  { id: 523, title: "Spectacular", bangla: "দর্শনীয়" },
  { id: 524, title: "Intact", bangla: "অক্ষুণ্ণ" },
  { id: 525, title: "Various", bangla: "বিভিন্ন" },
  { id: 526, title: "Train", bangla: "প্রশিক্ষণ" },
  { id: 527, title: "Develop", bangla: "উন্নয়ন" },
  { id: 528, title: "Collect", bangla: "সংগ্রহ করা" },
  { id: 529, title: "Supervise", bangla: "পর্যবেক্ষণ করা" },
  { id: 530, title: "Mark", bangla: "চিহ্নিত করা" },
  { id: 531, title: "Edit", bangla: "সম্পাদনা" },
  { id: 532, title: "Revise", bangla: "পুনঃপর্যালোচনা" },
  { id: 533, title: "Exhibit", bangla: "প্রদর্শন করা" },
  { id: 534, title: "Donate", bangla: "দান করা" },
  { id: 535, title: "Surpass", bangla: "অতিক্রম করা" },
  { id: 536, title: "Register", bangla: "নিবন্ধন করা" },
  { id: 537, title: "Support", bangla: "সমর্থন" },
  { id: 538, title: "Hunt", bangla: "শিকার" },
  { id: 539, title: "Persuade", bangla: "অনুপ্রাণিত করা" },
  { id: 540, title: "Concentrate", bangla: "মনোযোগ কেন্দ্রীভূত করা" },
  { id: 541, title: "Discuss", bangla: "আলোচনা করা" },
  { id: 542, title: "Suggest", bangla: "প্রস্তাব করা" },
  { id: 543, title: "Arrange", bangla: "ব্যবস্থা করা" },
  { id: 544, title: "Borrow", bangla: "ধার নেওয়া" },
  { id: 545, title: "Immigrate", bangla: "প্রবাহিত হওয়া" },
  { id: 546, title: "Review", bangla: "পুনঃমূল্যায়ন" },
  { id: 547, title: "Learn", bangla: "শিখা" },
  { id: 548, title: "Touch", bangla: "স্পর্শ করা" },
  { id: 549, title: "Jet-Skiing", bangla: "জেট-স্কিইং" },
  { id: 550, title: "Bodyboarding", bangla: "বডিবোর্ডিং" },
  { id: 551, title: "Snowboarding", bangla: "স্নোবোর্ডিং" },
  { id: 552, title: "Cricket", bangla: "ক্রিকেট" },
  { id: 553, title: "Baseball", bangla: "বেসবল" },
  { id: 554, title: "Basketball", bangla: "বাস্কেটবল" },
  { id: 555, title: "Rugby", bangla: "রাগবি" },
  { id: 556, title: "Hang-Gliding", bangla: "হ্যাং-গ্লাইডিং" },
  { id: 557, title: "Skydiving", bangla: "স্কাইডাইভিং" },
  { id: 558, title: "Soccer", bangla: "সকার" },
  { id: 559, title: "American Football", bangla: "আমেরিকান ফুটবল" },
  { id: 560, title: "Hockey", bangla: "হকি" },
  { id: 561, title: "Swimming", bangla: "সাঁতার" },
  { id: 562, title: "Tennis", bangla: "টেনিস" },
  { id: 563, title: "Squash", bangla: "স্কোয়াশ" },
  { id: 564, title: "Javelin", bangla: "জাভেলিন" },
  { id: 565, title: "Badminton", bangla: "ব্যাডমিন্টন" },
  { id: 566, title: "Ping-Pong", bangla: "পিং-পং" },
  { id: 567, title: "Field", bangla: "মাঠ" },
  { id: 568, title: "Court", bangla: "আদালত" },
  { id: 569, title: "Pitch", bangla: "পিচ" },
  { id: 570, title: "Stadium", bangla: "স্টেডিয়াম" },
  { id: 571, title: "Team", bangla: "টিম" },
  { id: 572, title: "Discuss", bangla: "আলোচনা করা" },
  { id: 573, title: "Hammer", bangla: "হ্যামার" },
  { id: 574, title: "High Jump", bangla: "উচ্চ লাফ" },
  { id: 575, title: "Horse Racing", bangla: "ঘোড়া দৌড়" },
  { id: 576, title: "Show Jumping", bangla: "শো জাম্পিং" },
  { id: 577, title: "Polo", bangla: "পোলো" },
  { id: 578, title: "Cycling", bangla: "সাইক্লিং" },
  { id: 579, title: "Canoeing", bangla: "কানুইং" },
  { id: 580, title: "Refreshment", bangla: "তাজা পানীয়" },
  { id: 581, title: "Gymnasium", bangla: "জিমনেশিয়াম" },
  { id: 582, title: "Extreme Sports", bangla: "এক্সট্রিম খেলাধুলা" },
  { id: 583, title: "Paragliding", bangla: "প্যারাগ্লাইডিং" },

  { id: 585, title: "Abseiling", bangla: "অ্যাবসেলিং" },
  { id: 586, title: "Bungee Jumping", bangla: "বাংজি জাম্পিং" },
  { id: 587, title: "Climbing", bangla: "পাহাড়ে আরোহণ" },
  { id: 588, title: "Wakeboarding", bangla: "ওয়েকবোর্ডিং" },
  { id: 589, title: "Kite Surfing", bangla: "কাইট সার্ফিং" },
  { id: 590, title: "Skiing", bangla: "স্কিইং" },
  { id: 591, title: "Snorkeling", bangla: "স্নোরকেলিং" },
  { id: 592, title: "Motor Racing", bangla: "মোটর রেসিং" },
  { id: 593, title: "Surfing", bangla: "সার্ফিং" },
  { id: 594, title: "Windsurfing", bangla: "উইন্ডসার্ফিং" },
  { id: 595, title: "Caving", bangla: "গুহায় প্রবেশ" },
  { id: 596, title: "Scuba Diving", bangla: "স্কুবা ডাইভিং" },
  { id: 597, title: "Archery", bangla: "ধনুকবিদ্যা" },
  { id: 598, title: "Fencing", bangla: "ফেন্সিং" },
  { id: 599, title: "Equestrian", bangla: "ঘোড়া চালনা" },
  { id: 600, title: "Parkour", bangla: "পারকোর" },
  { id: 601, title: "Slacklining", bangla: "স্ল্যাকলাইনের মাধ্যমে হাঁটা" },
  { id: 602, title: "Volleyball", bangla: "ভলিবল" },
  { id: 603, title: "Rowing", bangla: "রোয়িং" },
  { id: 604, title: "Handball", bangla: "হ্যান্ডবল" },
  { id: 605, title: "Paddleboarding", bangla: "প্যাডেলবোর্ডিং" },
  { id: 606, title: "Powerlifting", bangla: "পাওয়ারলিফটিং" },
  { id: 607, title: "Gymnastics", bangla: "জিমন্যাস্টিকস" },
  { id: 608, title: "Cyclocross", bangla: "সাইক্লোক্রস" },
  { id: 609, title: "Obstacle Racing", bangla: "বাধা প্রতিযোগিতা" },
  { id: 610, title: "Softball", bangla: "সফটবল" },
  { id: 611, title: "Sailing", bangla: "পাল তোলা" },
  { id: 612, title: "Track and Field", bangla: "ট্র্যাক এবং মাঠ" },

  { id: 601, title: "Barbell", bangla: "বারবেল" },
  { id: 602, title: "Treadmill", bangla: "ট্রেডমিল" },
  { id: 603, title: "Championship", bangla: "চ্যাম্পিয়নশিপ" },
  { id: 604, title: "Oval", bangla: "ডিম্বাকৃতির" },
  { id: 605, title: "Square", bangla: "বর্গক্ষেত্র" },
  { id: 606, title: "Rectangular", bangla: "আয়তাকার" },
  { id: 607, title: "Triangular", bangla: "ত্রিভুজাকৃত" },
  { id: 608, title: "Polygon", bangla: "বহুভুজ" },
  { id: 609, title: "Spherical", bangla: "গোলকাকার" },
  { id: 610, title: "Circular", bangla: "বৃত্তাকার" },
  { id: 611, title: "Curved", bangla: "বাঁকা" },
  { id: 612, title: "Cylindrical", bangla: "সিলিন্ড্রিক" },
  { id: 613, title: "Three dimensions", bangla: "তিন মাত্রিক" },
  { id: 614, title: "Width", bangla: "প্রস্থ" },
  { id: 615, title: "Length", bangla: "দৈর্ঘ্য" },
  { id: 616, title: "Altitude", bangla: "উচ্চতা" },
  { id: 617, title: "Imperial system", bangla: "সাম্রাজ্যিক ব্যবস্থা" },
  { id: 618, title: "Metric system", bangla: "মেট্রিক ব্যবস্থা" },
  { id: 619, title: "Spiral", bangla: "সাপের মতো" },
  { id: 620, title: "Mass", bangla: "ভর" },
  { id: 621, title: "Depth", bangla: "গভীরতা" },
  { id: 622, title: "Breadth", bangla: "প্রস্থ" },
  { id: 623, title: "Height", bangla: "উচ্চতা" },
  { id: 624, title: "Frequency", bangla: "ফ্রিকোয়েন্সি" },
  { id: 625, title: "Humid", bangla: "আর্দ্র" },
  { id: 626, title: "Hot", bangla: "গরম" },
  { id: 627, title: "Sticky", bangla: "আঠালো" },
  { id: 628, title: "Breeze", bangla: "বাতাস" },
  { id: 629, title: "Chilly", bangla: "হিমশীতল , ঠান্ডা" },
  { id: 630, title: "Cold", bangla: "ঠান্ডা" },
  { id: 631, title: "Cool", bangla: "শীতল" },
  { id: 632, title: "Dry", bangla: "শুকনো" },
  { id: 633, title: "Dusty", bangla: "ধুলোয় ভরা" },
  { id: 634, title: "Freezing", bangla: "বরফযুক্ত , বরফে ঢাকা" },

  { id: 635, title: "Warm", bangla: "উষ্ণ" },
  { id: 636, title: "Wet", bangla: "ভেজা" },
  { id: 637, title: "Weather forecast", bangla: "আবহাওয়া পূর্বাভাস" },
  { id: 638, title: "Antenna", bangla: "অ্যান্টেনা" },
  { id: 639, title: "Moisture", bangla: "আর্দ্রতা" },
  { id: 640, title: "Helmet", bangla: "হেলমেট" },
  { id: 641, title: "Light", bangla: "আলো" },
  { id: 642, title: "Musical instrument", bangla: "সঙ্গীত যন্ত্র" },
  { id: 643, title: "Cassette", bangla: "ক্যাসেট" },
  { id: 644, title: "Silicon chip", bangla: "সিলিকন চিপ" },
  { id: 645, title: "Digital monitor", bangla: "ডিজিটাল মনিটর" },
  { id: 646, title: "Gadget", bangla: "যন্ত্রপাতি" },
  { id: 647, title: "Device", bangla: "যন্ত্র" },
  { id: 648, title: "Screen", bangla: "স্ক্রীন , পর্দা" },

  { id: 649, title: "Brakes", bangla: "ব্রেক" },
  { id: 650, title: "Wheels", bangla: "চাকা" },

  { id: 651, title: "Mechanical pencil", bangla: "যান্ত্রিক পেন্সিল" },
  { id: 652, title: "Disk", bangla: "ডিস্ক" },
  { id: 653, title: "Backpack", bangla: "ব্যাকপ্যাক" },
  { id: 654, title: "Opera", bangla: "অপার" },
  { id: 655, title: "Orchestra", bangla: "অর্কেস্ট্রা" },
  { id: 656, title: "Concert", bangla: "কনসার্ট" },
  { id: 657, title: "Symphony", bangla: "সিনফনি" },
  { id: 658, title: "The press", bangla: "দ্য প্রেস" },
  { id: 659, title: "Conductor", bangla: "কন্ডাক্টর" },
  { id: 660, title: "Vocalist", bangla: "গায়ক" },
  { id: 661, title: "Audience", bangla: "দর্শক" },
  { id: 662, title: "Festival", bangla: "উৎসব" },
  { id: 664, title: "Exhibition", bangla: "প্রদর্শনী" },
  { id: 665, title: "Classical music", bangla: "ক্লাসিক্যাল সঙ্গীত" },
  { id: 666, title: "Theatre", bangla: "থিয়েটার" },
  { id: 667, title: "Cinemas", bangla: "সিনেমা" },
  { id: 668, title: "Art gallery", bangla: "শিল্প গ্যালারি" },
  { id: 669, title: "Museum", bangla: "যাদুঘর" },
  { id: 670, title: "Ballet", bangla: "ব্যালে" },
  { id: 671, title: "Television", bangla: "টেলিভিশন" },
  { id: 672, title: "Radio", bangla: "রেডিও" },
  { id: 673, title: "Graphics", bangla: "গ্রাফিক্স" },
  { id: 674, title: "Newspaper", bangla: "সামাচারপত্র" },
  { id: 675, title: "Lion", bangla: "সিংহ" },
  { id: 676, title: "Penguin", bangla: "পেঙ্গুইন" },
  { id: 677, title: "Seabirds", bangla: "সামুদ্রিক পাখি" },
  { id: 678, title: "Poultry and game", bangla: "মুরগি ও খেলার পাখি" },
  { id: 679, title: "Birds of prey", bangla: "শিকারী পাখি" },
  { id: 680, title: "Mammals", bangla: "স্তন্যপায়ী" },
  { id: 681, title: "Genus", bangla: "জেনাস" },
  { id: 682, title: "Species", bangla: "প্রজাতি" },
  { id: 683, title: "Cetacean", bangla: "সেটেসিয়ান" },
  { id: 684, title: "Whale", bangla: "তিমি" },
  { id: 685, title: "Primates", bangla: "প্রাইমেট" },
  { id: 686, title: "Rodents", bangla: "ঁচুড়িপোকা" },
  { id: 687, title: "Reptile", bangla: "সুরঙ্গী" },
  { id: 688, title: "Insects", bangla: "পোকামাকড়" },
  { id: 689, title: "Octopus", bangla: "অক্টোপাস" },
  { id: 690, title: "Phylum", bangla: "ফাইলাম" },
  { id: 691, title: "Fish", bangla: "মাছ" },
  { id: 692, title: "Amphibian", bangla: "অম্ফিবিয়ান" },
  { id: 693, title: "Class", bangla: "শ্রেণী" },
  { id: 694, title: "Order", bangla: "ক্রম" },
  { id: 695, title: "Family", bangla: "পরিবার" },
  { id: 696, title: "Livestock", bangla: "পশুপাখি" },
  { id: 697, title: "Creature", bangla: "প্রাণী" },
  { id: 698, title: "Camper", bangla: "ক্যাম্পার" },
  { id: 699, title: "Double-decker bus", bangla: "ডাবল ডেকার বাস" },
  { id: 700, title: "Single-decker", bangla: "সিঙ্গল ডেকার" },
  { id: 701, title: "Minibus", bangla: "মিনি বাস" },
  { id: 702, title: "Forklift truck", bangla: "ফর্কলিফট ট্রাক" },
  { id: 703, title: "School bus", bangla: "স্কুল বাস" },
  { id: 704, title: "Coach", bangla: "কোচ" },
  { id: 705, title: "Truck", bangla: "ট্রাক" },
  { id: 706, title: "Tanker", bangla: "ট্যাঙ্কার" },
  { id: 707, title: "Van", bangla: "ভ্যান" },
  { id: 708, title: "Lorry", bangla: "লরি" },
  { id: 709, title: "Transporter", bangla: "পরিবহনকারী" },
  { id: 710, title: "Tow truck", bangla: "টোট ট্রাক" },
  { id: 711, title: "Breakdown truck", bangla: "ব্রেকডাউন ট্রাক" },
  { id: 712, title: "Pickup", bangla: "পিকআপ" },
  { id: 713, title: "Jeep", bangla: "জিপ" },
  { id: 714, title: "Taxi", bangla: "ট্যাক্সি" },
  { id: 715, title: "Cab", bangla: "ক্যাব" },
  { id: 716, title: "Tram", bangla: "ট্রাম" },
  { id: 717, title: "Underground", bangla: "আন্ডারগ্রাউন্ড" },
  { id: 718, title: "Subway", bangla: "সাবওয়ে" },
  { id: 719, title: "Caravan", bangla: "কারাভান" },
  { id: 720, title: "Tractor", bangla: "ট্রাক্টর" },
  { id: 721, title: "Stream train", bangla: "স্ট্রিম ট্রেন" },
  { id: 722, title: "Freight train", bangla: "ফ্রেইট ট্রেন" },
  { id: 723, title: "Goods train", bangla: "গুডস ট্রেন" },
  { id: 724, title: "Midday", bangla: "দুপুর" },
  { id: 725, title: "Three times", bangla: "তিন বার" },
  { id: 726, title: "Three times per week", bangla: "সপ্তাহে তিন বার" },
  { id: 727, title: "Millennium", bangla: "সহস্রাব্দ" },
  { id: 728, title: "Gap year", bangla: "গ্যাপ বছর" },
  { id: 729, title: "Full-time", bangla: "পূর্ণকালীন" },
  { id: 730, title: "Part-time", bangla: "অর্ধকালীন" },
  { id: 731, title: "Midnight", bangla: "রাত ১২টা" },
  { id: 732, title: "Century", bangla: "শতাব্দী" },
  { id: 733, title: "Decade", bangla: "দশক" },
  { id: 734, title: "Fortnight", bangla: "পনেরো দিন" },
  { id: 735, title: "Aluminum", bangla: "এলুমিনিয়াম" },
  { id: 736, title: "Copper", bangla: "তামা" },
  { id: 737, title: "Fur", bangla: "ফার" },
  { id: 738, title: "Metal", bangla: "ধাতু" },
  { id: 739, title: "Steel", bangla: "স্টীল" },
  { id: 740, title: "Rubber", bangla: "রাবার" },
  { id: 742, title: "Plastic", bangla: "প্লাস্টিক" },
  { id: 743, title: "Ceramics", bangla: "সিরামিকস" },
  { id: 744, title: "Cement", bangla: "সিমেন্ট" },
  { id: 745, title: "Stone", bangla: "পাথর" },
  { id: 746, title: "Textile", bangla: "বস্ত্র" },
  { id: 747, title: "Cotton", bangla: "সুতা" },
  { id: 748, title: "Fabric", bangla: "ফ্যাব্রিক" },
  { id: 749, title: "Wool", bangla: "উল" },
  { id: 750, title: "Glass", bangla: "গ্লাস" },
  { id: 751, title: "Leather", bangla: "চামড়া" },
  { id: 752, title: "Bone", bangla: "হাড়" },
  { id: 753, title: "Paper", bangla: "কাগজ" },
  { id: 754, title: "Lumber/wood", bangla: "লাকড়ি/কাঠ" },
  { id: 755, title: "Glue", bangla: "আঠা" },
  { id: 756, title: "Concrete", bangla: "কংক্রিট" },
  { id: 757, title: "Wax", bangla: "মোম" },
  { id: 758, title: "Silver", bangla: "রূপা" },
  { id: 759, title: "Composite", bangla: "কম্পোজিট" },
  { id: 760, title: "Fiberglass", bangla: "ফাইবারগ্লাস" },
  { id: 761, title: "Gold", bangla: "সোনা" },
  { id: 762, title: "Feather", bangla: "পক্ষী পালক" },
  { id: 763, title: "Sufficient", bangla: "যথেষ্ট" },
  { id: 764, title: "Dialogue", bangla: "সংলাপ" },
  { id: 765, title: "Passport Photo", bangla: "পাসপোর্ট ছবি" },
  { id: 766, title: "State", bangla: "রাষ্ট্র" },
  { id: 767, title: "Variety", bangla: "বৈচিত্র্য" },
  { id: 768, title: "Private Sector", bangla: "বেসরকারী খাত" },
  { id: 769, title: "Practice", bangla: "অনুশীলন" },
  { id: 770, title: "Gender", bangla: "লিঙ্গ" },
  { id: 771, title: "Creativity", bangla: "সৃজনশীলতা" },
  { id: 772, title: "Government", bangla: "সরকার" },
  { id: 773, title: "Individual", bangla: "ব্যক্তি" },
  { id: 774, title: "Original Inhabitant", bangla: "মূল অধিবাসী" },
  { id: 775, title: "Indigenous", bangla: "আদিবাসী" },
  { id: 776, title: "Demonstration", bangla: "প্রদর্শনী" },
  { id: 777, title: "Circuit", bangla: "সার্কিট" },
  { id: 778, title: "Guarantee", bangla: "গ্যারান্টি" },
  { id: 779, title: "Commerce", bangla: "বাণিজ্য" },
  { id: 780, title: "Carriage", bangla: "বহন" },
  { id: 781, title: "Narrative", bangla: "বর্ণনা" },
  { id: 782, title: "Strike", bangla: "ধর্মঘট" },
  { id: 783, title: "Entrance", bangla: "প্রবেশদ্বার" },
  { id: 784, title: "Chocolate", bangla: "চকলেট" },
  { id: 785, title: "Satellite", bangla: "স্যাটেলাইট" },
  { id: 786, title: "Decision", bangla: "সিদ্ধান্ত" },
  { id: 787, title: "Prototype", bangla: "প্রোটোটাইপ" },
  { id: 788, title: "Attitude", bangla: "মনোভাব" },
  { id: 789, title: "Activity", bangla: "কর্মসূচি" },
  { id: 790, title: "Recipient", bangla: "গ্রহীতা" },
  { id: 791, title: "Ultrasound", bangla: "অল্ট্রাসাউন্ড" },
  { id: 792, title: "Pedestrian Safety", bangla: "পায়ে হাঁটার নিরাপত্তা" },
  { id: 793, title: "Daily Routine", bangla: "দৈনিক রুটিন" },
  { id: 794, title: "Personal Fulfillment", bangla: "ব্যক্তিগত পরিপূর্ণতা" },
  { id: 795, title: "Traffic Jams", bangla: "যানজট" },
  { id: 796, title: "Procedures", bangla: "প্রকৃয়া" },
  { id: 797, title: "Creation", bangla: "সৃষ্টি" },
  { id: 798, title: "Senior", bangla: "জ্যেষ্ঠ" },
  { id: 799, title: "Opportunity", bangla: "সুযোগ" },
  { id: 800, title: "Driving License", bangla: "ড্রাইভিং লাইসেন্স" },
  { id: 801, title: "Prize", bangla: "পুরস্কার" },
  { id: 802, title: "Junior", bangla: "কনিষ্ঠ" },
  { id: 803, title: "Process", bangla: "প্রক্রিয়া" },
  { id: 804, title: "Literary", bangla: "সাহিত্যিক" },
  { id: 805, title: "Man-Made", bangla: "মানবসৃষ্ট" },
  { id: 806, title: "Republicans", bangla: "গণতান্ত্রিক" },
  { id: 807, title: "Waiting List", bangla: "অপেক্ষা তালিকা" },
  { id: 808, title: "Sewer Systems", bangla: "পানি নিষ্কাশন ব্যবস্থা" },
  { id: 809, title: "Liberal Democracy", bangla: "উদার গণতন্ত্র" },
  { id: 810, title: "Democrats", bangla: "গণতান্ত্রিক" },
  { id: 811, title: "Umbrella", bangla: "ছাতা" },
  { id: 812, title: "Frequently Updated", bangla: "প্রায়ই আপডেট করা" },
  { id: 813, title: "Lunar Calendar", bangla: "চন্দ্র পঞ্জিকা" },
  { id: 814, title: "Libertarian", bangla: "স্বাধীনতাবাদী" },
  { id: 815, title: "Burger", bangla: "বার্গার" },
  { id: 816, title: "Videos", bangla: "ভিডিও" },
  { id: 817, title: "Fund-Raising Event", bangla: "অর্থ সংগ্রহের অনুষ্ঠান" },
  { id: 818, title: "Magnet", bangla: "চুম্বক" },
  { id: 819, title: "Dialect", bangla: "উপভাষা" },
  { id: 821, title: "Ramification", bangla: "ফলস্বরূপ" },
  { id: 822, title: "Straight", bangla: "সোজা" },
  { id: 823, title: "Nature Conservation", bangla: "প্রকৃতি সংরক্ষণ" },
  { id: 824, title: "Life Expectancy", bangla: "জীবনকাল প্রত্যাশা" },
  { id: 825, title: "Farewell", bangla: "বিদায়" },
  { id: 826, title: "Welfare", bangla: "কল্যাণ" },
  { id: 827, title: "Encyclopedia", bangla: "বিশ্বকোষ" },
  { id: 828, title: "Illiteracy", bangla: "অশিক্ষা" },
  { id: 829, title: "Robot", bangla: "রোবট" },
  { id: 830, title: "Proficiency", bangla: "দক্ষতা" },
  { id: 831, title: "Evolution", bangla: "বিকাশ" },
  { id: 832, title: "Revolution", bangla: "বিপ্লব" },
  { id: 833, title: "IELTS", bangla: "IELTS" },
  { id: 834, title: "Easiest", bangla: "সবচেয়ে সহজ" },
  { id: 835, title: "a, an", bangla: "অব্যক্ত বিশেষণ" },
  { id: 836, title: "act", bangla: "কাজ করা" },
  { id: 837, title: "advertisement", bangla: "বিজ্ঞাপন" },
  { id: 838, title: "ability", bangla: "ক্ষমতা" },
  { id: 839, title: "action", bangla: "কর্ম, কাজ" },
  { id: 840, title: "advice", bangla: "পরামর্শ" },
  { id: 841, title: "advise", bangla: "পরামর্শ দেওয়া" },
  { id: 842, title: "able", bangla: "সক্ষম" },
  { id: 843, title: "unable", bangla: "অক্ষম" },
  { id: 844, title: "active", bangla: "সক্রিয়" },
  { id: 845, title: "activity", bangla: "কার্যকলাপ" },
  { id: 846, title: "afraid", bangla: "ভয় পাওয়া" },
  { id: 847, title: "actor, actress", bangla: "অভিনেতা, অভিনেত্রী" },
  { id: 848, title: "after", bangla: "পরে" },
  { id: 849, title: "absence", bangla: "অনুপস্থিতি" },
  { id: 850, title: "absent", bangla: "অনুপস্থিত" },
  { id: 851, title: "actually", bangla: "আসলে" },
  { id: 852, title: "again", bangla: "আবার" },
  { id: 853, title: "absolute", bangla: "সম্পূর্ণ" },
  { id: 854, title: "absolutely", bangla: "পুরোপুরি" },
  { id: 855, title: "academic", bangla: "একাডেমিক" },
  { id: 856, title: "accept", bangla: "গ্রহণ করা" },
  { id: 857, title: "acceptable", bangla: "গ্রহণযোগ্য" },
  { id: 858, title: "unacceptable", bangla: "অগ্রহণযোগ্য" },
  { id: 859, title: "accident", bangla: "দুর্ঘটনা" },
  { id: 860, title: "admit", bangla: "স্বীকার করা" },
  { id: 861, title: "adult", bangla: "প্রাপ্তবয়স্ক" },
  { id: 862, title: "agree", bangla: "সম্মত হওয়া" },
  { id: 863, title: "agreement", bangla: "চুক্তি" },
  { id: 864, title: "advance", bangla: "অগ্রসর হওয়া, অগ্রিম" },
  { id: 865, title: "ahead", bangla: "সামনে" },
  { id: 866, title: "aid", bangla: "সাহায্য" },
  { id: 867, title: "aim", bangla: "লক্ষ্য" },
  { id: 868, title: "air", bangla: "বাতাস" },
  { id: 869, title: "aircraft", bangla: "বিমান" },
  { id: 870, title: "alcohol", bangla: "মদ" },
  { id: 871, title: "alcoholic", bangla: "মদ্যপ" },
  { id: 872, title: "alive", bangla: "জীবিত" },
  { id: 873, title: "angle", bangla: "কোণ" },
  { id: 874, title: "analysis", bangla: "বিশ্লেষণ" },
  { id: 875, title: "analyze", bangla: "বিশ্লেষণ করা" },
  { id: 876, title: "appropriate", bangla: "উপযুক্ত" },
  { id: 877, title: "approximate", bangla: "আনুমানিক" },
  { id: 878, title: "accurate", bangla: "সঠিক" },
  { id: 879, title: "accurately", bangla: "সঠিকভাবে" },
  { id: 880, title: "achieve", bangla: "অর্জন করা" },
  { id: 881, title: "achievement", bangla: "অর্জন" },
  { id: 882, title: "advertise", bangla: "বিজ্ঞাপন দেওয়া" },
  { id: 883, title: "advertising", bangla: "বিজ্ঞাপন দেওয়া" },
  { id: 884, title: "alarm", bangla: "সংকেত, বিপদ সংকেত" },
  { id: 885, title: "alarming", bangla: "উদ্বেগজনক" },
  { id: 886, title: "analyse", bangla: "বিশ্লেষণ করা (British English)" },
  { id: 887, title: "appointment", bangla: "অ্যাপয়েন্টমেন্ট" },
  { id: 888, title: "alcoholic", bangla: "মদ্যপ" },
  { id: 889, title: "alive", bangla: "জীবিত" },
  { id: 890, title: "All", bangla: "সব" },
  { id: 891, title: "Angry", bangla: "রাগান্বিত" },
  { id: 892, title: "Anniversary", bangla: "বার্ষিকী" },
  { id: 893, title: "Argument", bangla: "যুক্তি, বিতর্ক" },
  { id: 894, title: "Almost", bangla: "প্রায়" },
  { id: 895, title: "Announce", bangla: "ঘোষণা করা" },
  { id: 896, title: "Arise", bangla: "উঠা, সৃষ্টি হওয়া" },
  { id: 897, title: "Alone", bangla: "একা" },
  { id: 898, title: "Annual", bangla: "বার্ষিক" },
  { id: 899, title: "Along", bangla: "বরাবর" },
  { id: 900, title: "Alphabet", bangla: "বর্ণমালা" },
  { id: 901, title: "Another", bangla: "অন্য" },
  { id: 902, title: "Answer", bangla: "উত্তর" },
  { id: 903, title: "Any", bangla: "কোনো" },
  { id: 904, title: "Anyone", bangla: "কেউ" },
  { id: 905, title: "Anything", bangla: "কিছু" },
  { id: 906, title: "Anywhere", bangla: "কোথাও" },
  { id: 907, title: "Arrive", bangla: "পৌঁছানো" },
  { id: 908, title: "Alternative", bangla: "বিকল্প" },
  { id: 909, title: "Apart", bangla: "আলাদা" },
  { id: 910, title: "Apart from", bangla: "ছাড়া" },
  { id: 911, title: "Always", bangla: "সবসময়" },
  { id: 912, title: "Ambition", bangla: "উচ্চাকাঙ্ক্ষা" },
  { id: 913, title: "Apple", bangla: "আপেল" },
  { id: 914, title: "Artist", bangla: "শিল্পী" },
  { id: 915, title: "Ambulance", bangla: "অ্যাম্বুলেন্স" },
  { id: 916, title: "Application", bangla: "আবেদন" },
  { id: 917, title: "Among", bangla: "এর মধ্যে" },
  { id: 918, title: "Amount", bangla: "পরিমাণ" },
  { id: 919, title: "Autumn", bangla: "শরতকাল" },
  { id: 920, title: "Ask", bangla: "প্রশ্ন করা" },
  { id: 921, title: "Available", bangla: "উপলব্ধ" },
  { id: 922, title: "Assist", bangla: "সহায়তা করা" },
  { id: 923, title: "Assistance", bangla: "সহায়তা" },
  { id: 924, title: "Assistant", bangla: "সহকারী" },
  { id: 925, title: "Average", bangla: "গড়" },
  { id: 926, title: "Awake", bangla: "জাগ্রত" },
  { id: 927, title: "Baby", bangla: "শিশু" },
  { id: 928, title: "Battery", bangla: "ব্যাটারি" },
  { id: 929, title: "Background", bangla: "পটভূমি" },
  { id: 930, title: "Back", bangla: "পেছন, ফিরে" },
  { id: 931, title: "At", bangla: "এ" },
  { id: 932, title: "Art", bangla: "শিল্প" },

  { id: 933, title: "Backward", bangla: "পেছনে" },
  { id: 934, title: "Especially", bangla: "বিশেষভাবে" },
  { id: 935, title: "Attach", bangla: "সংযুক্ত করা" },
  { id: 936, title: "Back", bangla: "পেছন" },
  { id: 937, title: "Bear", bangla: "Bear" },
  { id: 938, title: "Attached", bangla: "সংযুক্ত" },
  { id: 939, title: "Bacteria", bangla: "ব্যাকটেরিয়া" },
  { id: 940, title: "Beard", bangla: "দাড়ি" },
  { id: 941, title: "Attack", bangla: "আক্রমণ করা" },
  { id: 942, title: "Bad", bangla: "খারাপ" },
  { id: 943, title: "Beat", bangla: "পেটানো" },
  { id: 944, title: "Attempt", bangla: "চেষ্টা করা" },
  { id: 945, title: "Badly", bangla: "খারাপভাবে" },
  { id: 946, title: "Beautiful", bangla: "সুন্দর" },
  { id: 947, title: "Bad-tempered", bangla: "খিটখিটে" },
  { id: 948, title: "Beauty", bangla: "সৌন্দর্য" },
  { id: 949, title: "Bag", bangla: "ব্যাগ" },
  { id: 950, title: "Because", bangla: "কারণ" },
  { id: 951, title: "Baggage", bangla: "মালপত্র" },
  { id: 952, title: "Balance", bangla: "ভারসাম্য" },
  { id: 953, title: "Become", bangla: "হওয়া" },
  { id: 954, title: "Ball", bangla: "বল" },
  { id: 955, title: "Bed", bangla: "বিছানা" },
  { id: 956, title: "Fear", bangla: "ভয়" },
  { id: 957, title: "Band", bangla: "ব্যান্ড" },
  { id: 958, title: "Bandage", bangla: "ব্যান্ডেজ" },
  { id: 959, title: "Before", bangla: "আগে" },
  { id: 960, title: "Begin", bangla: "শুরু করা" },
  { id: 961, title: "Bargain", bangla: "দরকষাকষি" },
  { id: 962, title: "Beginning", bangla: "শুরু" },
  { id: 963, title: "Barrier", bangla: "বাধা" },
  { id: 964, title: "Both", bangla: "উভয়" },
  { id: 965, title: "Bank", bangla: "ব্যাংক" },
  { id: 966, title: "Bed", bangla: "বিছানা" },
  { id: 967, title: "Begin", bangla: "শুরু" },
  { id: 968, title: "Balance", bangla: "ভারসাম্য" },
  { id: 969, title: "Bitter", bangla: "তিক্ত" },
  { id: 970, title: "Bandage", bangla: "ব্যান্ডেজ" },
  { id: 971, title: "Before", bangla: "আগে" },
  { id: 972, title: "Begin", bangla: "শুরু করা" },
  { id: 973, title: "Bargain", bangla: "দরকষাকষি" },
  { id: 974, title: "Beginning", bangla: "শুরু" },
  { id: 975, title: "Believe", bangla: "বিশ্বাস করা" },
  { id: 976, title: "Behavior", bangla: "আচরণ" },
  { id: 977, title: "Behind", bangla: "পিছনে" },
  { id: 978, title: "Benefit", bangla: "সুবিধা" },
  { id: 979, title: "Beside", bangla: "পাশে" },
  { id: 980, title: "Better", bangla: "ভাল" },
  { id: 981, title: "Beverage", bangla: "পানীয়" },
  { id: 982, title: "Between", bangla: "মধ্যে" },
  { id: 983, title: "Beyond", bangla: "পেরিয়ে" },
  { id: 984, title: "Billion", bangla: "বিলিয়ন" },
  { id: 985, title: "Bitter", bangla: "তিক্ত" },
  { id: 986, title: "Blame", bangla: "দোষ দেওয়া" },
  { id: 987, title: "Blank", bangla: "খালি" },
  { id: 988, title: "Bleed", bangla: "রক্তপাত করা" },
  { id: 989, title: "Blind", bangla: "অন্ধ" },
  { id: 990, title: "Block", bangla: "ব্লক করা" },
  { id: 991, title: "Blood", bangla: "রক্ত" },
  { id: 992, title: "Blow", bangla: "উড়ানো, মারা" },
  { id: 993, title: "Blunt", bangla: "ম্লান" },
  { id: 994, title: "Board", bangla: "বোর্ড" },
  { id: 995, title: "Boat", bangla: "নৌকা" },
  { id: 996, title: "Body", bangla: "দেহ" },
  { id: 997, title: "Book", bangla: "বই" },
  { id: 998, title: "Boss", bangla: "বস" },
  { id: 999, title: "Bottom", bangla: "তল" },
  { id: 1000, title: "Bottle", bangla: "বোতল" },
  { id: 1001, title: "Bother", bangla: "বিরক্ত করা" },
  { id: 1002, title: "Both", bangla: "উভয়" },
  { id: 1003, title: "Bottom", bangla: "তল" },
  { id: 1004, title: "Boundary", bangla: "সীমা" },
  { id: 1005, title: "Bowl", bangla: "বাটি" },
  { id: 1006, title: "Box", bangla: "বাক্স" },
  { id: 1007, title: "Boy", bangla: "ছেলে" },
  { id: 1008, title: "Brave", bangla: "সাহসী" },
  { id: 1009, title: "Break", bangla: "ভাঙা" },
  { id: 1010, title: "Bread", bangla: "রুটি" },
  { id: 1011, title: "Breathe", bangla: "শ্বাস নেওয়া" },
  { id: 1012, title: "Broke", bangla: "ভেঙে গেছে" },
  { id: 1013, title: "Brought", bangla: "আনা" },
  { id: 1014, title: "Brown", bangla: "বাদামী" },
  { id: 1016, title: "PORE", bangla: "ছিদ্র" },
  { id: 1017, title: "Brother", bangla: "ভাই" },
  { id: 1018, title: "Brown", bangla: "বাদামী" },
  { id: 1019, title: "Brush", bangla: "ব্রাশ" },
  { id: 1020, title: "Budget", bangla: "বাজেট" },
  { id: 1021, title: "Build", bangla: "তৈরি করা" },
  { id: 1022, title: "Building", bangla: "ভবন" },
  { id: 1023, title: "Bullet", bangla: "গুলি" },
  { id: 1024, title: "Burn", bangla: "পুড়িয়ে দেওয়া" },
  { id: 1025, title: "Bus", bangla: "বাস" },
  { id: 1026, title: "Bush", bangla: "ঝোঁপ" },
  { id: 1027, title: "Business", bangla: "ব্যবসা" },
  { id: 1028, title: "Busy", bangla: "ব্যস্ত" },
  { id: 1029, title: "But", bangla: "কিন্তু" },
  { id: 1030, title: "Button", bangla: "বোতাম" },
  { id: 1031, title: "Buy", bangla: "কেনা" },
  { id: 1032, title: "Buyer", bangla: "ক্রেতা" },
  { id: 1033, title: "By", bangla: "দ্বারা" },
  { id: 1034, title: "Cab", bangla: "ট্যাক্সি" },
  { id: 1035, title: "Cake", bangla: "কেক" },
  { id: 1036, title: "Calculate", bangla: "গণনা করা" },
  { id: 1037, title: "Camera", bangla: "ক্যামেরা" },
  { id: 1038, title: "Camp", bangla: "ক্যাম্প" },
  { id: 1039, title: "Carrot", bangla: "গাজর" },
  { id: 1040, title: "Carry", bangla: "বহন করা" },
  { id: 1041, title: "Card", bangla: "কার্ড" },
  { id: 1042, title: "Case", bangla: "মামলা" },
  { id: 1043, title: "Cat", bangla: "বিড়াল" },
  { id: 1044, title: "Cancel", bangla: "বাতিল করা" },
  { id: 1045, title: "Cancer", bangla: "ক্যান্সার" },
  { id: 1046, title: "Cap", bangla: "টুপি" },
  { id: 1047, title: "Capability", bangla: "ক্ষমতা" },
  { id: 1048, title: "Celebrate", bangla: "উদযাপন করা" },
  { id: 1049, title: "Celebration", bangla: "উদযাপন" },
  { id: 1050, title: "Cell", bangla: "সেল" },
  { id: 1051, title: "Cent", bangla: "সেন্ট" },
  { id: 1052, title: "Centimeter", bangla: "সেন্টিমিটার" },
  { id: 1053, title: "Central", bangla: "কেন্দ্রীয়" },
  { id: 1054, title: "Center", bangla: "কেন্দ্র" },
  { id: 1055, title: "Century", bangla: "শতাব্দী" },
  { id: 1056, title: "Ceremony", bangla: "অনুষ্ঠান" },
  { id: 1057, title: "Chemical", bangla: "রাসায়নিক" },
  { id: 1058, title: "Chemist", bangla: "ঔষধের দোকান" },
  { id: 1059, title: "Chest", bangla: "বক্ষ" },
  { id: 1060, title: "Chicken", bangla: "মুরগী" },
  { id: 1061, title: "Chocolate", bangla: "চকোলেট" },
  { id: 1062, title: "Choice", bangla: "পছন্দ" },
  { id: 1063, title: "Cloth", bangla: "কাপড়" },
  { id: 1064, title: "Close", bangla: "কাছাকাছি" },
  { id: 1065, title: "Clock", bangla: "ঘড়ি" },
  { id: 1066, title: "Chain", bangla: "চেইন" },
  { id: 1067, title: "Chair", bangla: "চেয়ার" },
  { id: 1068, title: "Chairwoman", bangla: "চেয়ারওমেন" },
  { id: 1069, title: "Child", bangla: "শিশু" },
  { id: 1070, title: "Chocolate", bangla: "চকোলেট" },
  { id: 1071, title: "Complicate", bangla: "জটিল করা" },
  { id: 1072, title: "Comment", bangla: "মন্তব্য করা" },
  { id: 1073, title: "Commercial", bangla: "বাণিজ্যিক" },
  { id: 1074, title: "Commission", bangla: "কমিশন" },
  { id: 1075, title: "Commit", bangla: "প্রতিশ্রুতি দেওয়া" },
  { id: 1076, title: "Contribute", bangla: "অবদান রাখা" },
  { id: 1077, title: "Contribution", bangla: "অবদান" },
  { id: 1078, title: "Control", bangla: "নিয়ন্ত্রণ করা" },
  { id: 1079, title: "Concentration", bangla: "মনোযোগ" },
  { id: 1080, title: "Container", bangla: "ধারক" },
  { id: 1081, title: "Concept", bangla: "ধারণা" },
  { id: 1082, title: "Crime", bangla: "অপরাধ" },
  { id: 1083, title: "Concert", bangla: "কনসার্ট" },
  { id: 1084, title: "Criminal", bangla: "অপরাধী" },
  { id: 1085, title: "Continuous", bangla: "অবিরাম" },
  { id: 1086, title: "Cough", bangla: "কাশি" },
  { id: 1087, title: "Critical", bangla: "সমালোচনামূলক" },
  { id: 1088, title: "Criticize", bangla: "সমালোচনা করা" },
  { id: 1089, title: "Coughing", bangla: "কাশির শব্দ" },
  { id: 1090, title: "Could", bangla: "পারা (মডাল)" },
  { id: 1091, title: "Crop", bangla: "ফসল" },
  { id: 1092, title: "Council", bangla: "কাউন্সিল" },
  { id: 1093, title: "Count", bangla: "গণনা করা" },
  { id: 1094, title: "Crowd", bangla: "জনতা" },
  { id: 1095, title: "Cross", bangla: "পার করা" },
  { id: 1096, title: "Crowded", bangla: "ভিড়যুক্ত" },
  { id: 1097, title: "Crown", bangla: "মুকুট" },
  { id: 1098, title: "Country", bangla: "দেশ" },
  { id: 1099, title: "Cruel", bangla: "নিষ্ঠুর" },
  { id: 1100, title: "Cultural", bangla: "সাংস্কৃতিক" },
  { id: 1101, title: "Culture", bangla: "সংস্কৃতি" },
  { id: 1102, title: "Course", bangla: "কোর্স" },
  { id: 1103, title: "Cousin", bangla: "ভাইবোনের সন্তান" },
  { id: 1104, title: "Cure", bangla: "চিকিৎসা" },
  { id: 1105, title: "Currently", bangla: "বর্তমানে" },
  { id: 1106, title: "Cover", bangla: "আচ্ছাদিত করা" },
  { id: 1107, title: "Cousin", bangla: "চাচাতো ভাই বা বোন" },
  { id: 1108, title: "Custom", bangla: "রীতি" },
  { id: 1109, title: "Customer", bangla: "গ্রাহক" },
  { id: 1110, title: "Cost", bangla: "মূল্য" },
  { id: 1111, title: "Crash", bangla: "সংঘর্ষ" },
  { id: 1112, title: "Crazy", bangla: "পাগল" },
  { id: 1113, title: "Cottage", bangla: "কটেজ" },
  { id: 1114, title: "Customs", bangla: "শুল্ক" },
  { id: 1115, title: "Cut", bangla: "কাটা" },
  { id: 1116, title: "Cycle", bangla: "সাইকেল" },
  { id: 1117, title: "Cycling", bangla: "সাইক্লিং" },
  { id: 1118, title: "Dad", bangla: "বাবা" },
  { id: 1119, title: "Daily", bangla: "দৈনিক" },
  { id: 1120, title: "Damage", bangla: "ক্ষতি" },
  { id: 1121, title: "Damp", bangla: "ভেজা" },
  { id: 1122, title: "Dance", bangla: "নাচা" },
  { id: 1123, title: "Dancing", bangla: "নাচ" },
  { id: 1124, title: "Dancer", bangla: "নৃত্যশিল্পী" },
  { id: 1125, title: "Danger", bangla: "বিপদ" },
  { id: 1126, title: "Dangerous", bangla: "বিপদজনক" },
  { id: 1127, title: "Dark", bangla: "অন্ধকার" },
  { id: 1128, title: "Dare", bangla: "সাহস করা" },
  { id: 1129, title: "Deep", bangla: "গভীর" },
  { id: 1130, title: "Defence", bangla: "প্রতিরক্ষা" },
  { id: 1131, title: "Describe", bangla: "বর্ণনা করা" },
  { id: 1132, title: "Decision", bangla: "সিদ্ধান্ত" },
  { id: 1133, title: "Desk", bangla: "ডেস্ক" },
  { id: 1134, title: "Declare", bangla: "ঘোষণা করা" },
  { id: 1135, title: "Detail", bangla: "বিশদ" },
  { id: 1136, title: "Decorate", bangla: "সজ্জিত করা" },
  { id: 1137, title: "Decoration", bangla: "সজ্জা" },
  { id: 1138, title: "Detailed", bangla: "বিস্তারিত" },
  { id: 1139, title: "Develop", bangla: "উন্নয়ন করা" },
  { id: 1140, title: "Development", bangla: "উন্নয়ন" },
  { id: 1141, title: "Decrease", bangla: "হ্রাস করা" },
  { id: 1142, title: "Device", bangla: "যন্ত্র" },
  { id: 1143, title: "Diagram", bangla: "ডায়াগ্রাম" },
  { id: 1144, title: "Deeply", bangla: "গভীরভাবে" },
  { id: 1145, title: "Diamond", bangla: "হীরা" },
  { id: 1146, title: "Diary", bangla: "ডায়েরি" },
  { id: 1147, title: "Challenge", bangla: "চ্যালেঞ্জ" },
  { id: 1148, title: "Choose", bangla: "নির্বাচন করা" },
  { id: 1149, title: "Clothes", bangla: "পোশাক" },
  { id: 1150, title: "Chamber", bangla: "কক্ষ" },
  { id: 1151, title: "Church", bangla: "গির্জা" },
  { id: 1152, title: "Clothing", bangla: "পোশাক" },
  { id: 1153, title: "Cigarette", bangla: "সিগারেট" },
  { id: 1154, title: "Cloud", bangla: "মেঘ" },
  { id: 1155, title: "Change", bangla: "পরিবর্তন করা" },
  { id: 1156, title: "Cinema", bangla: "সিনেমা" },
  { id: 1157, title: "Club", bangla: "ক্লাব" },
  { id: 1158, title: "Channel", bangla: "চ্যানেল" },
  { id: 1159, title: "Circle", bangla: "বৃত্ত" },
  { id: 1160, title: "Centimeter", bangla: "সেন্টিমিটার" },
  { id: 1161, title: "Chapter", bangla: "অধ্যায়" },
  { id: 1162, title: "Circumstance", bangla: "পরিস্থিতি" },
  { id: 1163, title: "Coach", bangla: "কোচ" },
  { id: 1164, title: "Character", bangla: "চরিত্র" },
  { id: 1165, title: "Citizen", bangla: "নাগরিক" },
  { id: 1166, title: "Coal", bangla: "কয়লা" },
  { id: 1167, title: "City", bangla: "শহর" },
  { id: 1168, title: "Coat", bangla: "কোট" },
  { id: 1169, title: "Charge", bangla: "চার্জ করা" },
  { id: 1170, title: "Civil", bangla: "নাগরিক" },
  { id: 1171, title: "Code", bangla: "কোড" },
  { id: 1172, title: "Chart", bangla: "চার্ট" },
  { id: 1173, title: "Claim", bangla: "দাবি করা" },
  { id: 1174, title: "Class", bangla: "শ্রেণী" },
  { id: 1175, title: "Conclusion", bangla: "উপসংহার" },
  { id: 1176, title: "Cheap", bangla: "সস্তা" },
  { id: 1177, title: "Classic", bangla: "ক্লাসিক" },
  { id: 1178, title: "Concrete", bangla: "কংক্রিট" },
  { id: 1179, title: "Coffee", bangla: "কফি" },
  { id: 1180, title: "Classroom", bangla: "শ্রেণীকক্ষ" },
  { id: 1181, title: "Condition", bangla: "শর্ত" },
  { id: 1182, title: "Coin", bangla: "মুদ্রা" },
  { id: 1183, title: "Commitment", bangla: "প্রতিশ্রুতি" },
  { id: 1184, title: "Confidence", bangla: "আত্মবিশ্বাস" },
  { id: 1185, title: "Cold", bangla: "ঠাণ্ডা" },
  { id: 1186, title: "Committee", bangla: "কমিটি" },
  { id: 1187, title: "Common", bangla: "সাধারণ" },
  { id: 1188, title: "Confirm", bangla: "নিশ্চিত করা" },
  { id: 1189, title: "Commonly", bangla: "সাধারণত" },
  { id: 1190, title: "Confuse", bangla: "বিভ্রান্ত করা" },
  { id: 1191, title: "Collection", bangla: "সংগ্রহ" },
  { id: 1192, title: "Communicate", bangla: "যোগাযোগ করা" },
  { id: 1193, title: "Communication", bangla: "যোগাযোগ" },
  { id: 1194, title: "College", bangla: "কলেজ" },
  { id: 1195, title: "Colour (BrE) / Color (AmE)", bangla: "রং" },
  { id: 1196, title: "Coloured (BrE)", bangla: "রঙিন" },
  { id: 1197, title: "Column", bangla: "স্তম্ভ" },
  { id: 1198, title: "Compare", bangla: "তুলনা করা" },
  { id: 1199, title: "Connect", bangla: "সংযোগ করা" },
  { id: 1200, title: "Combination", bangla: "সংমিশ্রণ" },
  { id: 1201, title: "Competition", bangla: "প্রতিযোগিতা" },
  { id: 1202, title: "Comedic", bangla: "হাস্যকর" },
  { id: 1203, title: "Comfort", bangla: "স্বস্তি" },
  { id: 1204, title: "Comfortably", bangla: "আরামদায়কভাবে" },
  { id: 1205, title: "Complete", bangla: "পূর্ণ" },
  { id: 1206, title: "Consider", bangla: "বিবেচনা করা" },
  { id: 1207, title: "Comfortable", bangla: "আরামদায়ক" },
  {
    id: 1209,
    title: "PORE",
    bangla: "রন্ধ্র",
  },

  {
    id: 1210,
    title: "Data",
    bangla: "তথ্য",
  },
  {
    id: 1211,
    title: "Defend",
    bangla: "রক্ষা করা",
  },
  {
    id: 1212,
    title: "Dictionary",
    bangla: "অভিধান",
  },
  {
    id: 1213,
    title: "Date",
    bangla: "তারিখ",
  },
  {
    id: 1214,
    title: "Define",
    bangla: "সংজ্ঞায়িত করা",
  },
  {
    id: 1215,
    title: "Die",
    bangla: "মারা যাওয়া",
  },
  {
    id: 1216,
    title: "Daughter",
    bangla: "কন্যা",
  },
  {
    id: 1217,
    title: "Definite",
    bangla: "নির্দিষ্ট",
  },
  {
    id: 1218,
    title: "Diet",
    bangla: "খাদ্যাভ্যাস",
  },
  {
    id: 1219,
    title: "Day",
    bangla: "দিন",
  },
  {
    id: 1220,
    title: "Definitely",
    bangla: "নিশ্চিতভাবে",
  },
  {
    id: 1221,
    title: "Difference",
    bangla: "পার্থক্য",
  },
  {
    id: 1222,
    title: "Dead",
    bangla: "মৃত",
  },
  {
    id: 1223,
    title: "Degree",
    bangla: "ডিগ্রী",
  },
  {
    id: 1224,
    title: "Differently",
    bangla: "ভিন্নভাবে",
  },
  {
    id: 1225,
    title: "Deal",
    bangla: "চুক্তি করা",
  },
  {
    id: 1226,
    title: "Delay",
    bangla: "বিলম্ব করা",
  },
  {
    id: 1227,
    title: "Doctor",
    bangla: "ডাক্তার (abbr. Dr.)",
  },
  {
    id: 1228,
    title: "Deal with",
    bangla: "মোকাবেলা করা",
  },
  {
    id: 1229,
    title: "Deliver",
    bangla: "প্রদান করা",
  },
  {
    id: 1230,
    title: "Document",
    bangla: "নথি",
  },
  {
    id: 1231,
    title: "Dear",
    bangla: "প্রিয়",
  },
  {
    id: 1232,
    title: "Delivery",
    bangla: "বিতরণ",
  },
  {
    id: 1233,
    title: "Dog",
    bangla: "কুকুর",
  },
  {
    id: 1234,
    title: "Death",
    bangla: "মৃত্যু",
  },
  {
    id: 1235,
    title: "Demand",
    bangla: "চাহিদা",
  },
  {
    id: 1236,
    title: "Difficult",
    bangla: "কঠিন",
  },
  {
    id: 1237,
    title: "Dentist",
    bangla: "দন্ত চিকিৎসক",
  },
  {
    id: 1238,
    title: "Domestic",
    bangla: "গৃহস্থালির",
  },
  {
    id: 1239,
    title: "Discussion",
    bangla: "আলোচনা",
  },
  {
    id: 1240,
    title: "Disease",
    bangla: "রোগ",
  },
  {
    id: 1241,
    title: "Dinner",
    bangla: "ডিনার",
  },
  {
    id: 1242,
    title: "Disgusting",
    bangla: "অস্বস্তিকর",
  },
  {
    id: 1243,
    title: "Dish",
    bangla: "থালা",
  },
  {
    id: 1244,
    title: "Direct",
    bangla: "সরাসরি",
  },
  {
    id: 1245,
    title: "Dishonest",
    bangla: "অসৎ",
  },
  {
    id: 1246,
    title: "Direction",
    bangla: "দিক",
  },
  {
    id: 1247,
    title: "Dishonestly",
    bangla: "অসতভাবে",
  },
  {
    id: 1248,
    title: "Directly",
    bangla: "সরাসরি",
  },
  {
    id: 1249,
    title: "Director",
    bangla: "পরিচালক",
  },
  {
    id: 1250,
    title: "Distance",
    bangla: "দূরত্ব",
  },
  {
    id: 1251,
    title: "Dirt",
    bangla: "ময়লা",
  },
  {
    id: 1252,
    title: "Dislike",
    bangla: "অপছন্দ করা",
  },
  {
    id: 1253,
    title: "Disk",
    bangla: "ডিস্ক",
  },
  {
    id: 1254,
    title: "Discount",
    bangla: "ছাড়",
  },
  {
    id: 1255,
    title: "Diverge",
    bangla: "বিচ্যুত হওয়া",
  },
  {
    id: 1256,
    title: "Discover",
    bangla: "আবিষ্কার করা",
  },
  {
    id: 1257,
    title: "Discovery",
    bangla: "আবিষ্কার",
  },
  {
    id: 1258,
    title: "Drive",
    bangla: "চালানো",
  },
  {
    id: 1259,
    title: "Doubt",
    bangla: "সন্দেহ",
  },
  {
    id: 1260,
    title: "Divorce",
    bangla: "বিবাহ বিচ্ছেদ",
  },
  {
    id: 1261,
    title: "Drama",
    bangla: "নাটক",
  },
  {
    id: 1262,
    title: "Disagree",
    bangla: "একমত না হওয়া",
  },
  {
    id: 1263,
    title: "Display",
    bangla: "প্রদর্শন করা",
  },
  {
    id: 1264,
    title: "Dressed",
    bangla: "পোশাক পরা",
  },
  {
    id: 1265,
    title: "Disturb",
    bangla: "বিরক্ত করা",
  },
  {
    id: 1266,
    title: "Disturbing",
    bangla: "বিরক্তিকর",
  },
  {
    id: 1267,
    title: "Drink",
    bangla: "পানীয়, পান করা",
  },
  {
    id: 1268,
    title: "Drawer",
    bangla: "টানা",
  },
  {
    id: 1269,
    title: "Dream",
    bangla: "স্বপ্ন, স্বপ্ন দেখা",
  },
  {
    id: 1270,
    title: "Dress",
    bangla: "পোশাক পরা",
  },
  {
    id: 1271,
    title: "Distress",
    bangla: "উদ্বেগ",
  },
  {
    id: 1272,
    title: "Drive",
    bangla: "চালানো",
  },
  {
    id: 1273,
    title: "Disaster",
    bangla: "বিপর্যয়",
  },
  {
    id: 1274,
    title: "Disc",
    bangla: "ডিস্ক",
  },
  {
    id: 1275,
    title: "Divide",
    bangla: "ভাগ করা",
  },
  {
    id: 1276,
    title: "Discount",
    bangla: "ছাড়",
  },

  {
    id: 1280,
    title: "Drunk",
    bangla: "মত্ত",
  },
  {
    id: 1281,
    title: "Educate",
    bangla: "শিক্ষা দেওয়া",
  },
  {
    id: 1282,
    title: "Emphasis",
    bangla: "গুরুত্ব",
  },
  {
    id: 1283,
    title: "Dry",
    bangla: "শুষ্ক",
  },
  {
    id: 1284,
    title: "Educated",
    bangla: "শিক্ষিত",
  },
  {
    id: 1285,
    title: "Emphasize",
    bangla: "গুরুত্ব দেওয়া",
  },
  {
    id: 1286,
    title: "Education",
    bangla: "শিক্ষা",
  },
  {
    id: 1287,
    title: "Employee",
    bangla: "কর্মচারী",
  },
  {
    id: 1288,
    title: "Effective",
    bangla: "কার্যকর",
  },
  {
    id: 1289,
    title: "Employer",
    bangla: "নিয়োগকর্তা",
  },
  {
    id: 1290,
    title: "Effort",
    bangla: "প্রচেষ্টা",
  },
  {
    id: 1291,
    title: "Unemployment",
    bangla: "বেকারত্ব",
  },
  {
    id: 1292,
    title: "Dust",
    bangla: "ধুলো",
  },
  {
    id: 1293,
    title: "Egg",
    bangla: "ডিম",
  },
  {
    id: 1294,
    title: "Enable",
    bangla: "সক্ষম করা",
  },
  {
    id: 1295,
    title: "Empty",
    bangla: "খালি",
  },
  {
    id: 1296,
    title: "Encourage",
    bangla: "উৎসাহিত করা",
  },
  {
    id: 1297,
    title: "Each",
    bangla: "প্রতিটি",
  },
  {
    id: 1298,
    title: "Either",
    bangla: "এক বা অন্য",
  },
  {
    id: 1299,
    title: "Each other",
    bangla: "একে অপর",
  },
  {
    id: 1300,
    title: "Elbow",
    bangla: "কনুই",
  },
  {
    id: 1301,
    title: "Encouragement",
    bangla: "উৎসাহ",
  },
  {
    id: 1302,
    title: "Fear",
    bangla: "ভয়",
  },
  {
    id: 1303,
    title: "Elderly",
    bangla: "বয়স্ক",
  },
  {
    id: 1304,
    title: "End",
    bangla: "শেষ",
  },
  {
    id: 1305,
    title: "Early",
    bangla: "প্রাথমিক, আগে",
  },
  {
    id: 1306,
    title: "Earn",
    bangla: "উপার্জন করা",
  },
  {
    id: 1307,
    title: "Earth",
    bangla: "পৃথিবী",
  },
  {
    id: 1308,
    title: "Electric",
    bangla: "বৈদ্যুতিক",
  },
  {
    id: 1309,
    title: "Ease",
    bangla: "সহজতা",
  },
  {
    id: 1310,
    title: "Electrical",
    bangla: "বৈদ্যুতিক",
  },
  {
    id: 1311,
    title: "East",
    bangla: "পূর্ব",
  },
  {
    id: 1312,
    title: "Eastern",
    bangla: "পূর্বের",
  },
  {
    id: 1313,
    title: "Easily",
    bangla: "সহজভাবে",
  },
  {
    id: 1314,
    title: "Element",
    bangla: "উপাদান",
  },
  {
    id: 1315,
    title: "Elevator",
    bangla: "লিফট",
  },
  {
    id: 1316,
    title: "Excite",
    bangla: "উত্তেজিত করা",
  },
  {
    id: 1317,
    title: "Exchange",
    bangla: "বিনিময়",
  },
  {
    id: 1318,
    title: "In exchange (for)",
    bangla: "বিনিময়ে",
  },
  {
    id: 1319,
    title: "Exception",
    bangla: "ব্যতিক্রম",
  },
  {
    id: 1320,
    title: "Electronic",
    bangla: "বৈদ্যুতিন",
  },
  {
    id: 1321,
    title: "Energy",
    bangla: "শক্তি",
  },
  {
    id: 1322,
    title: "Error",
    bangla: "ভুল",
  },
  {
    id: 1323,
    title: "Exciting",
    bangla: "উত্তেজনাপূর্ণ",
  },
  {
    id: 1324,
    title: "Excited",
    bangla: "উত্তেজিত",
  },
  {
    id: 1325,
    title: "Excitement",
    bangla: "উত্তেজনা",
  },
  {
    id: 1326,
    title: "Engage",
    bangla: "জড়িত করা",
  },
  {
    id: 1327,
    title: "Engaged",
    bangla: "লিপ্ত",
  },
  {
    id: 1328,
    title: "Engine",
    bangla: "ইঞ্জিন",
  },
  {
    id: 1329,
    title: "Engineer",
    bangla: "প্রকৌশলী",
  },
  {
    id: 1330,
    title: "Engineering",
    bangla: "প্রকৌশল",
  },
  {
    id: 1331,
    title: "Essential",
    bangla: "অত্যাবশ্যক",
  },
  {
    id: 1332,
    title: "Exhibition",
    bangla: "প্রদর্শনী",
  },
  {
    id: 1333,
    title: "Essentially",
    bangla: "মূলত",
  },
  {
    id: 1334,
    title: "Exist",
    bangla: "অস্তিত্ব রাখা",
  },
  {
    id: 1335,
    title: "Existence",
    bangla: "অস্তিত্ব",
  },
  {
    id: 1336,
    title: "Euro",
    bangla: "ইউরো",
  },
  {
    id: 1337,
    title: "Exit",
    bangla: "প্রস্থান",
  },
  {
    id: 1338,
    title: "Even",
    bangla: "এমনকি",
  },
  {
    id: 1339,
    title: "Evening",
    bangla: "সন্ধ্যা",
  },
  {
    id: 1340,
    title: "Expect",
    bangla: "আশা করা",
  },
  {
    id: 1341,
    title: "Expected",
    bangla: "প্রত্যাশিত",
  },
  {
    id: 1342,
    title: "Event",
    bangla: "ঘটনা",
  },
  {
    id: 1343,
    title: "Eventually",
    bangla: "অবশেষে",
  },
  {
    id: 1344,
    title: "Unexpected",
    bangla: "অপ্রত্যাশিত",
  },
  {
    id: 1345,
    title: "Unexpectedly",
    bangla: "অপ্রত্যাশিতভাবে",
  },
  {
    id: 1346,
    title: "Enquiry",
    bangla: "অনুসন্ধান",
  },
  {
    id: 1347,
    title: "Ensure",
    bangla: "নিশ্চিত করা",
  },
  {
    id: 1348,
    title: "Enter",
    bangla: "প্রবেশ করা",
  },
  {
    id: 1349,
    title: "Entertain",
    bangla: "বিনোদন দেওয়া",
  },
  {
    id: 1350,
    title: "Everybody",
    bangla: "সবাই",
  },
  {
    id: 1351,
    title: "Entertaining",
    bangla: "বিনোদনমূলক",
  },
  {
    id: 1352,
    title: "Entertainment",
    bangla: "বিনোদন",
  },
  {
    id: 1353,
    title: "Entry",
    bangla: "প্রবেশ",
  },
  {
    id: 1354,
    title: "Evil",
    bangla: "দুষ্ট",
  },
  {
    id: 1355,
    title: "Experiment",
    bangla: "পরীক্ষা",
  },
  {
    id: 1356,
    title: "Envelope",
    bangla: "খাম",
  },
  {
    id: 1357,
    title: "Exact",
    bangla: "সঠিক",
  },
  {
    id: 1358,
    title: "Environment",
    bangla: "পরিবেশ",
  },
  {
    id: 1359,
    title: "Environmental",
    bangla: "পরিবেশগত",
  },
  {
    id: 1360,
    title: "Equal",
    bangla: "সমান",
  },

  {
    id: 1361,
    title: "Equally",
    bangla: "সমানভাবে",
  },
  {
    id: 1362,
    title: "Equipment",
    bangla: "সরঞ্জাম",
  },
  {
    id: 1363,
    title: "Expert",
    bangla: "বিশেষজ্ঞ",
  },
  {
    id: 1364,
    title: "Explain",
    bangla: "ব্যাখ্যা করা",
  },
  {
    id: 1365,
    title: "Explanation",
    bangla: "ব্যাখ্যা",
  },
  {
    id: 1366,
    title: "Expression",
    bangla: "অভিব্যক্তি",
  },
  {
    id: 1367,
    title: "Extra",
    bangla: "অতিরিক্ত",
  },
  {
    id: 1368,
    title: "Extraordinary",
    bangla: "অসাধারণ",
  },
  {
    id: 1369,
    title: "Extreme",
    bangla: "চরম",
  },
  {
    id: 1370,
    title: "Extremely",
    bangla: "অত্যন্ত",
  },
  {
    id: 1371,
    title: "Eye",
    bangla: "চোখ",
  },
  {
    id: 1372,
    title: "Face",
    bangla: "মুখ",
  },
  {
    id: 1373,
    title: "Facility",
    bangla: "সুবিধা",
  },
  {
    id: 1374,
    title: "Fact",
    bangla: "ঘটনা",
  },
  {
    id: 1375,
    title: "Factor",
    bangla: "উপাদান",
  },
  {
    id: 1376,
    title: "Factory",
    bangla: "কারখানা",
  },
  {
    id: 1377,
    title: "Fail",
    bangla: "ব্যর্থ হওয়া",
  },
  {
    id: 1378,
    title: "Failure",
    bangla: "ব্যর্থতা",
  },
  {
    id: 1379,
    title: "Fair",
    bangla: "সৎ",
  },
  {
    id: 1380,
    title: "Fairly",
    bangla: "সঠিকভাবে",
  },
  {
    id: 1381,
    title: "Faith",
    bangla: "বিশ্বাস",
  },
  {
    id: 1382,
    title: "Faithful",
    bangla: "বিশ্বস্ত",
  },
  {
    id: 1383,
    title: "Favor (BrE)",
    bangla: "সহায়তা",
  },
  {
    id: 1384,
    title: "Faithfully",
    bangla: "বিশ্বস্তভাবে",
  },
  {
    id: 1385,
    title: "Favorably",
    bangla: "সদয়ভাবে",
  },
  {
    id: 1386,
    title: "Finely",
    bangla: "সূক্ষ্মভাবে",
  },
  {
    id: 1387,
    title: "Favourite (BrE) / Favorite",
    bangla: "প্রিয়",
  },
  {
    id: 1388,
    title: "Finger",
    bangla: "আঙুল",
  },
  {
    id: 1389,
    title: "Fear",
    bangla: "ভয়",
  },
  {
    id: 1390,
    title: "Freeze",
    bangla: "জমে যাওয়া",
  },
  {
    id: 1391,
    title: "Finish",
    bangla: "সমাপ্তি",
  },
  {
    id: 1392,
    title: "Finished",
    bangla: "সমাপ্ত",
  },
  {
    id: 1393,
    title: "Feather",
    bangla: "পালক",
  },
  {
    id: 1394,
    title: "Frequent",
    bangla: "ঘনঘন",
  },
  {
    id: 1395,
    title: "Frequently",
    bangla: "ঘনঘনভাবে",
  },
  {
    id: 1396,
    title: "Fly",
    bangla: "উড়ানো",
  },
  {
    id: 1397,
    title: "Fresh",
    bangla: "তাজা",
  },
  {
    id: 1398,
    title: "Freshly",
    bangla: "তাজাভাবে",
  },
  {
    id: 1399,
    title: "Friday",
    bangla: "শুক্রবার",
  },
  {
    id: 1400,
    title: "Firmly",
    bangla: "দৃঢ়ভাবে",
  },
  {
    id: 1401,
    title: "First",
    bangla: "প্রথম",
  },
  {
    id: 1402,
    title: "Fold",
    bangla: "ভাঁজ করা",
  },
  {
    id: 1403,
    title: "Friend",
    bangla: "বন্ধু",
  },
  {
    id: 1404,
    title: "Friendly",
    bangla: "বন্ধুত্বপূর্ণ",
  },
  {
    id: 1405,
    title: "Unfriendly",
    bangla: "শত্রুতাপূর্ণ",
  },
  {
    id: 1406,
    title: "Foot",
    bangla: "পা",
  },
  {
    id: 1407,
    title: "Frighten",
    bangla: "ভয় দেখানো",
  },
  {
    id: 1408,
    title: "Fatal",
    bangla: "প্রাণঘাতী",
  },
  {
    id: 1409,
    title: "Football",
    bangla: "ফুটবল",
  },
  {
    id: 1410,
    title: "Frightening",
    bangla: "ভীতিপ্রদ",
  },
  {
    id: 1411,
    title: "Force",
    bangla: "শক্তি",
  },
  {
    id: 1412,
    title: "Foreign",
    bangla: "বিদেশী",
  },
  {
    id: 1413,
    title: "Front",
    bangla: "সামনের",
  },
  {
    id: 1414,
    title: "Forest",
    bangla: "বন",
  },
  {
    id: 1415,
    title: "Forever",
    bangla: "চিরকাল",
  },
  {
    id: 1416,
    title: "Forget",
    bangla: "ভুলে যাওয়া",
  },
  {
    id: 1417,
    title: "Forgive",
    bangla: "ক্ষমা করা",
  },
  {
    id: 1418,
    title: "Formal",
    bangla: "আনুষ্ঠানিক",
  },
  {
    id: 1419,
    title: "Goodbye",
    bangla: "বিদায়",
  },
  {
    id: 1420,
    title: "Formally",
    bangla: "আনুষ্ঠানিকভাবে",
  },
  {
    id: 1421,
    title: "Goods",
    bangla: "পণ্য",
  },
  {
    id: 1422,
    title: "Formula",
    bangla: "সূত্র",
  },
  {
    id: 1423,
    title: "Government",
    bangla: "সরকার",
  },
  {
    id: 1424,
    title: "Fully",
    bangla: "সম্পূর্ণভাবে",
  },
  {
    id: 1425,
    title: "Forward",
    bangla: "এগিয়ে",
  },
  {
    id: 1426,
    title: "Forwards",
    bangla: "সামনে",
  },
  {
    id: 1427,
    title: "Fun",
    bangla: "মজা",
  },
  {
    id: 1428,
    title: "Make fun of",
    bangla: "ঠাট্টা করা",
  },

  { id: 1429, title: "Glasses", bangla: "চশমা" },
  { id: 1430, title: "Grateful", bangla: "কৃতজ্ঞ" },
  { id: 1431, title: "Glad", bangla: "খুশি" },
  { id: 1432, title: "Grass", bangla: "ঘাস" },
  { id: 1433, title: "Gratefully", bangla: "কৃতজ্ঞভাবে" },
  { id: 1434, title: "Global", bangla: "বিশ্বজনীন" },
  { id: 1435, title: "Glove", bangla: "দস্তানা" },
  { id: 1436, title: "Go", bangla: "যাওয়া" },
  { id: 1437, title: "Goal", bangla: "লক্ষ্য" },
  { id: 1438, title: "Goodbye", bangla: "বিদায়" },
  { id: 1439, title: "Fishing", bangla: "মাছ ধরা" },
  { id: 1440, title: "Food", bangla: "খাবার" },
  { id: 1441, title: "Friendship", bangla: "বন্ধুত্ব" },
  { id: 1442, title: "Fit", bangla: "ফিট, উপযুক্ত" },
  { id: 1443, title: "Foot", bangla: "পা" },
  { id: 1444, title: "Frighten", bangla: "ভয় দেখানো" },
  { id: 1445, title: "Football", bangla: "ফুটবল" },
  { id: 1446, title: "Fixed", bangla: "স্থির" },
  { id: 1447, title: "Flag", bangla: "পতাকা" },
  { id: 1448, title: "Force", bangla: "শক্তি" },
  { id: 1449, title: "From", bangla: "থেকে" },
  { id: 1450, title: "Foreign", bangla: "বিদেশী" },
  { id: 1451, title: "Front", bangla: "সামনের" },
  { id: 1452, title: "Forest", bangla: "বন" },
  { id: 1453, title: "In front (of)", bangla: "সামনে" },
  { id: 1454, title: "Forever", bangla: "চিরকাল" },
  { id: 1455, title: "Forget", bangla: "ভুলে যাওয়া" },
  { id: 1456, title: "Forgive", bangla: "ক্ষমা করা" },
  { id: 1457, title: "Formal", bangla: "আনুষ্ঠানিক" },
  { id: 1458, title: "Formally", bangla: "আনুষ্ঠানিকভাবে" },
  { id: 1459, title: "Goods", bangla: "পণ্য" },
  { id: 1460, title: "Formula", bangla: "সূত্র" },
  { id: 1461, title: "Government", bangla: "সরকার" },
  { id: 1462, title: "Fully", bangla: "সম্পূর্ণভাবে" },
  { id: 1463, title: "Forward", bangla: "এগিয়ে" },
  { id: 1464, title: "Forwards", bangla: "সামনে" },
  { id: 1465, title: "Generate", bangla: "উৎপন্ন করা" },
  { id: 1466, title: "Gradually", bangla: "ধীরে ধীরে" },
  { id: 1467, title: "Function", bangla: "কার্যক্রম" },
  { id: 1468, title: "Fund", bangla: "তহবিল" },
  { id: 1469, title: "Fundamental", bangla: "মৌলিক" },
  { id: 1470, title: "Funny", bangla: "মজার" },
  { id: 1471, title: "Furniture", bangla: "আসবাবপত্র" },
  { id: 1472, title: "Future", bangla: "ভবিষ্যত" },
  { id: 1473, title: "Gain", bangla: "লাভ" },
  { id: 1474, title: "Get", bangla: "পাওয়া" },
  { id: 1475, title: "Gift", bangla: "উপহার" },
  { id: 1476, title: "Girl", bangla: "মেয়ে" },
  { id: 1477, title: "Goal", bangla: "লক্ষ্য" },
  { id: 1478, title: "Garage", bangla: "গ্যারেজ" },
  { id: 1479, title: "Garden", bangla: "বাগান" },
  { id: 1480, title: "Gas", bangla: "গ্যাস" },
  { id: 1481, title: "Gate", bangla: "দরজা" },
  { id: 1482, title: "Gather", bangla: "একত্রিত করা" },
  { id: 1483, title: "Gear", bangla: "যন্ত্রপাতি" },
  { id: 1484, title: "General", bangla: "সাধারণ" },
  { id: 1485, title: "Generally", bangla: "সাধারণভাবে" },
  { id: 1486, title: "Grey (BrE)", bangla: "ধূসর" },
  { id: 1487, title: "Great", bangla: "মহান" },
  { id: 1488, title: "Duty-Free Shop", bangla: "ডিউটি ফ্রি দোকান" },
  
];

export default data;
